In [3]:
import pyorbital
from pyorbital.orbital import Orbital
import datetime as dt
from matplotlib import colormaps as cmap
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import numpy as np
import pandas as pd
import bisect
import uuid
from enum import Enum

from fame import *
import copy

In [4]:
# Behind the scenes, this pulls from Celestrak if we do not specify tle_file

satellites = [
    Satellite("LOFT YAM-3", Orbital("YAM-3", tle_file="TLEs.txt")),
    Satellite("LOFT YAM-5", Orbital("YAM-5", tle_file="TLEs.txt")),
    Satellite("LOFT YAM-6", Orbital("YAM-6", tle_file="TLEs.txt")),
    Satellite("LOFT YAM-7", Orbital("YAM-7", tle_file="TLEs.txt")),
    Satellite("LOFT YAM-8", Orbital("YAM-8", tle_file="TLEs.txt")),
    Satellite("LOFT YAM-10", Orbital("YAM-10", tle_file="TLEs.txt")),
    Satellite("Ubotica CogniSat-6 HAMMER", Orbital("HAMMER", tle_file="TLEs.txt")),
    # "LOFT YAM-3": Orbital("YAM-3"),
]

In [5]:

ground_stations = [
    Location(
        -79.55,
        8.9833,
        0.028,
        "KSAT Panama",
    ),
    Location(
        -51.73363,
        64.182789,
        0,
        "KSAT Nuuk",
    ),
    Location(
        2.53219,
        -72.01243,
        0,
        "KSAT Troll",
    ),
    Location(
        142.3689,
        43.8,
        0,
        "KSAT Hokkaido",
    ),
    Location(
        103.9915,
        1.3661,
        0,
        "KSAT Singapore",
    ),
    Location(
        -70.85021,
        -52.93279,
        0,
        "KSAT Punta Arenas",
    ),
    Location(
        127.7766,
        26.4055,
        0,
        "KSAT Okinawa",
    ),
    Location(
        57.5565,
        -20.1142,
        0,
        "KSAT Mauritius",
    ),
    Location(
        22.62216,
        37.84604,
        0,
        "KSAT Nemea",
    ),
    Location(
        31.12509,
        70.36779,
        0,
        "KSAT Vardo",
    ),
    Location(
        15.39964,
        78.22875,
        0,
        "KSAT Svalbard",
    ),
]

# ground_station_opportunities = [
#     observation_request(
#         lon_deg=gs.lon_deg,
#         lat_deg=gs.lat_deg,
#         alt_km=gs.alt_km,
#         min_time=dt.datetime.now(dt.timezone.utc),
#         max_time=dt.datetime.now(dt.timezone.utc)+ dt.timedelta(seconds=3600*24*2)
#     )
#     for gs in ground_stations
# ]

In [6]:
stride_s = 60
plot_range_s = 10800

min_time = dt.datetime.now(dt.timezone.utc).replace(tzinfo=None)
max_time = min_time + dt.timedelta(hours=24)

In [7]:


cities_of_the_world = pd.read_csv("simplemaps_worldcities_basicv1.901/worldcities.csv")
sampled_world_cities = cities_of_the_world.sample(n=100,weights='population',axis=0, random_state=0)
one_hundred_sampled_cities = [
    ObservationRequest(city[1].lng, city[1].lat, min_time=min_time, max_time=max_time, alt_km=0.307, request_name=city[1].city,)
    for city in sampled_world_cities.iterrows()
]

# Simulation

Let's talk about simulation.

We want an event-based sim. There is a global ordered timeline and the sim jumps from event to event.

Continuous transitions (power, thermal, etc) are discretized in this setting.

We need a few entities here.

Agent: a satellite, a constellation manager, a requestor. 

Event: something on the ground turning on or off.

Communication: something that affects the state of two entities.

Observation: a query of an agent to (event, empty set). If we want to be fancy, a query of an agent to a region, where events are or are 
not associated with regions.

Prototype:
- A Satellite class with a list of Observations
- A ConstellationManager class with a list of Satellites which can query Observations and add new ones.
  - A ConstellationManager class that updates the Satellites' Observations when a Communication event occurs.
- An Observation of a Region.
    - Observe. Returns an image of the region.
    - Search. Returns True if there is an Event in the Region. The event is stored.
    - Monitor. Returns True if the event is still active.
    - Something for moving events?
- Phenomenon: something with a spatial position, start time, end time, potentially internal states.

The simulator holds:
- Agents (Satellites, ConstellationManagers)
- Phenomena.
- A list of Events (Observation, Communication, Phenomenon transitions), encoded as functions.
The output of the functions affects the agents and phenomena.

We need to define:

- An Observation Opportunity (observation_opportunity)
- An Observer, which has an Orbit, a list of Observation Opportunities to execute, a list of ObservedEvents it has observed (with their state), and a list of DataProducts.
- A ConstellationManager, which has a list of ObserverStates (Orbit, ObservationOpportunities) and a list of CommunicationOpportunities with Observers. When there is a CommunicationOpportunity the ConstellationManager can push an updated list of ObservationOpportunities.
- An Event, with a lonlatalt, a State (enum), and times for StateTransitions.
-

In [8]:
MIN_HORIZON_ANGLE_FOR_PASS_DEG = 15
MIN_HORIZON_ANGLE_FOR_OBS_DEG = 15

class Event():
    def __init__(self, time: dt.datetime, action_callable, name: str="", id: str=None):
        self.time = time
        self.action_callable = action_callable
        self.name = name
        if id is None:
            id = uuid.uuid4()
        self.id = id
    def __str__(self):
        return "Event {} at {}".format(self.name, self.time)
    def __repr__(self):
        return self.__str__()

class ObservationEvent(Event):
    def __init__(self, time: dt.datetime, action_callable, name: str="", id: str=None, satellite: Satellite=None, opportunity: ObservationOpportunity=None):
        super().__init__(time, action_callable, name, id)
        self.satellite = satellite
        self.opportunity = opportunity

class CommunicationEvent(Event):
    def __init__(self, time: dt.datetime, action_callable, name: str="", id: str=None, satellite: Satellite=None, station: Location=None, comm_pass: ObservationPass=None):
        super().__init__(time, action_callable, name, id)
        self.satellite = satellite
        self.station = station
        self.comm_pass = comm_pass

class Phenomenon(Location):
    def __init__(self, lon_deg: float, lat_deg: float, alt_km: float, start_time: dt.datetime, end_time: dt.datetime, name: str=""):
        super().__init__(lon_deg=lon_deg, lat_deg=lat_deg, alt_km=alt_km, name=name)
        # self.lon_deg = lon_deg
        # self.lat_deg = lat_deg
        # self.alt_km = alt_km
        self.start_time = start_time
        self.end_time = end_time
        # self.name = name
    def __str__(self):
        return "{}: Lon {}, lat {}, alt {}, start {}, end {}".format(self.name, self.lon_deg,self.lat_deg,self.alt_km, self.start_time, self.end_time)
    def __repr__(self):
        return self.__str__()

   
class World():
    def __init__(self, satellites: list=[], constellations: list = [], brokers: list = [], phenomena: list = [], events: list = []):
        self.satellites = satellites
        self.constellations = constellations
        self.brokers = brokers
        self.phenomena = phenomena
        self.events = events
        self.time = dt.datetime.min
        self.history = []
    
    def tick(self, print_forbidden_prefixes=[]):
        if len(self.events):
            _event = self.events.pop(0)

            _print_event_name = True
            for forbidden_names in print_forbidden_prefixes:
                if _event.name.startswith(forbidden_names):
                    _print_event_name = False
                    break
            if _print_event_name:
                print("Executing {}".format(_event))

            outcome = _event.action_callable()
            self.time = _event.time

            self.history.append({
                'time': _event.time,
                'event': _event,
                'states': {
                    'satellites': [copy.deepcopy(s) for s in self.satellites],
                    # Constellations and brokers have a pointer to World, which has a pointer to constellations, which...recursion!
                    # 'constellations': [copy.deepcopy(c) for c in self.constellations],
                    # 'brokers': [copy.deepcopy(b) for b in self.brokers],
                }
            })
            
        else:
            print("No more events")
            
        return len(self.events)

    def add_satellite(self, satellite):
        self.satellite.append(satellite)

    def add_constellation(self, constellation):
        self.constellations.append(constellation)
    
    def add_broker(self, broker):
        self.brokers.append(broker)
    
    def add_event(self, event):
        # print("Adding {}".format(event))
        if (event.time<self.time):
            raise ValueError("Event {} is earlier than sim time {}".format(event, self.time)) 
        bisect.insort(self.events, event, key=lambda x: x.time)
        
    def do_observation(self, observation: ObservationOpportunity, spacecraft: Satellite):
        # Find phenomena close to the observation location in space and at the right time
        # Return a data product and a list of event states
        # print("Obs opp {}".format(observation))
        observed_phenomena = []

        # Now let's see what we observed
        for _phenomenon in self.phenomena:
            if (_phenomenon.start_time <= observation.time and _phenomenon.end_time > observation.time):
                
                # Compute phenomenon location on the planet
                _ph_location_ecf = np.array(pyorbital.astronomy.observer_position(observation.time, _phenomenon.lon_deg, _phenomenon.lat_deg, _phenomenon.alt_km)[0][:3])
                # Compute observation location on the planet
                _obs_location_ecf = np.array(pyorbital.astronomy.observer_position(observation.time, observation.lon_deg, observation.lat_deg, observation.alt_km)[0][:3])
                # Compute SC location
                _sc_location_ecf = np.array(spacecraft.orbit.get_position(observation.time, normalize=False)[0][:3])
                # Compute angle between sc-observation and sc-phenomenon
                _ph_sc_vector = _ph_location_ecf-_sc_location_ecf
                _obs_sc_vector = _obs_location_ecf - _sc_location_ecf
                # print("PhSc {} || ObsSc {}".format(_ph_sc_vector, _obs_sc_vector))
                # print("Dot: {} || N1: {} N2: {}".format(np.dot(_ph_sc_vector,_obs_sc_vector),np.linalg.norm(_ph_sc_vector,2), np.linalg.norm(_obs_sc_vector,2))) 
                # print("Acos: {}, angle: {}".format(np.dot(_ph_sc_vector,_obs_sc_vector)/(np.linalg.norm(_ph_sc_vector,2)*np.linalg.norm(_obs_sc_vector,2)), np.arccos(np.dot(_ph_sc_vector,_obs_sc_vector)/(np.linalg.norm(_ph_sc_vector,2)*np.linalg.norm(_obs_sc_vector,2)))))
                _ph_obs_angle_rad = np.arccos(np.clip(np.dot(_ph_sc_vector,_obs_sc_vector)/(np.linalg.norm(_ph_sc_vector,2)*np.linalg.norm(_obs_sc_vector,2)),-1,1))
                # print("Obs angle (rad) {}".format(_ph_obs_angle_rad))
                # If angle<FOV, return phobservation
                if _ph_obs_angle_rad < spacecraft.instrument_fov_rad[observation.instrument]:
                    # print("Close enough")
                    observed_phenomena.append(_phenomenon)
                else:
                    # print("Too far")
                    pass
        # Store SOMETHING for the completed observation
        spacecraft.data_products.append(observation)
        spacecraft.known_phenomena.append(observed_phenomena)
        
        return True

In [9]:
def do_downlink(spacecraft: Satellite, scheduler, comm_pass: ObservationPass): # scheduler is a ConstellationGroundScheduler,defined next 
    # Simple: downlink all. Future: downlink up to x.
    
    # Duration is unused for now
    duration = comm_pass.fall.time - comm_pass.rise.time

    _downlinked = []
    if len(spacecraft.data_products):
        print("Spacecraft {} has {} data products to download".format(spacecraft, len(spacecraft.data_products)))
        
    for data_product in spacecraft.data_products:
        print("  Downlinked {}".format(data_product))
        _downlinked.append(data_product)
        
        matching_requests = scheduler._requests[scheduler._requests['observation']==data_product]
        # print(scheduler._requests)
        # print(matching_requests)
        if len(matching_requests):
            # my_request = matching_requests[0]
            scheduler._requests.loc[scheduler._requests['observation']==data_product, 'status'] = "OK! Data received"
            scheduler._requests.loc[scheduler._requests['observation']==data_product, 'data_product'] = data_product
            scheduler._requests.loc[scheduler._requests['observation']==data_product, 'ready_callback'].item()(data_product)
        

    for _dp in _downlinked:
        spacecraft.data_products.remove(_dp)

In [10]:
class ConstellationGroundScheduler():
    def __init__(self, satellites: list, ground_stations: list, world: World, name="Constellation"):
        self.name = name
        self.satellites = satellites
        self.ground_stations = ground_stations
        self.world = world
        # self.requests = {}
        self._requests = pd.DataFrame(columns=['request', 'satellite', 'observation', 'uplink', 'downlink', 'status', 'data_product', 'scheduled_callback', 'unscheduled_callback', 'ready_callback'])

    def screen_request_for_feasibility(self, _request: ObservationRequest, screen_against_comm_passes:bool=True):
        # Check if a given request conflicts with existing requests.
        # TODO this is horrifyingly expensive because we do not exploit the fact that
        #  requests are sorted. We should improve this, ideally without rebuilding a full on timeline library.
        conflicting_requests = self._requests.loc[
            self._requests.apply(
            lambda x: 
                (x['status']=="Scheduled") and # We have actually scheduled this
                (x['observation'].time+x['observation'].duration > _request.time) and # The end of the other observation is after we start
                (x['observation'].time < _request.time+_request.duration)  # The start of the other observation is before we end
            , axis=1)]
        if len(conflicting_requests):
            return False
        if (screen_against_comm_passes):
            conflicting_uplinks = self._requests.loc[
                self._requests.apply(
                lambda x: 
                    (x['status']=="Scheduled") and # We have actually scheduled this
                    (x['uplink'].fall.time > _request.time) and # The end of the comm pass is after we start
                    (x['uplink'].rise.time < _request.time + _request.duration) # The start of the comm pass is before we end
                , axis=1)]
            if len(conflicting_uplinks):
                return False
            conflicting_downlinks = self._requests.loc[
                self._requests.apply(
                lambda x: 
                    (x['status']=="Scheduled") and # We have actually scheduled this
                    (x['downlink'].fall.time > _request.time) and # The end of the comm pass is after we start
                    (x['downlink'].rise.time < _request.time + _request.duration) # The start of the comm pass is before we end
                , axis=1)]
            if len(conflicting_downlinks):
                return False
        return True
    
    def screen_pass_for_feasibility(self, _obs_pass: ObservationPass, screen_against_comm_passes:bool=False):
        # Check if a given pass conflicts with existing requests.
        # TODO this is horrifyingly expensive because we do not exploit the fact that
        #  requests are sorted. We should improve this, ideally without rebuilding a full on timeline library.
        conflicting_requests = self._requests.loc[
            self._requests.apply(
            lambda x: 
                (x['status']=="Scheduled") and # We have actually scheduled this
                (x['observation'].time+x['observation'].duration > _obs_pass.rise.time) and # The end of the other observation is after we start
                (x['observation'].time < _obs_pass.fall.time)  # The start of the other observation is before we end
            , axis=1)]
        if len(conflicting_requests):
            return False
        if (screen_against_comm_passes):
            conflicting_uplinks = self._requests.loc[
                self._requests.apply(
                lambda x: 
                    (x['status']=="Scheduled") and # We have actually scheduled this
                    (x['uplink'].fall.time > _obs_pass.rise.time) and # The end of the comm pass is after we start
                    (x['uplink'].rise.time < _obs_pass.fall.time) # The start of the comm pass is before we end
                , axis=1)]
            if len(conflicting_uplinks):
                return False
            conflicting_downlinks = self._requests.loc[
                self._requests.apply(
                lambda x: 
                    (x['status']=="Scheduled") and # We have actually scheduled this
                    (x['downlink'].fall.time > _obs_pass.rise.time) and # The end of the comm pass is after we start
                    (x['downlink'].rise.time < _obs_pass.fall.time) # The start of the comm pass is before we end
                , axis=1)]
            if len(conflicting_downlinks):
                return False
        return True

    def schedule_request(
            self,
            request: ObservationRequest,
            current_time: dt.datetime=dt.datetime.now(dt.timezone.utc).replace(tzinfo=None),
            callback_request_scheduled=lambda req_pass: None,
            callback_request_unscheduled=lambda reason: None,
            callback_request_ready=lambda data_product: None,
            ):
        # Pick the best satellite to fulfill this. This is where we'll need to be smarter. Or not! Just pick something starting the day after.
        print("[{}] Scheduling request {}".format(self.name, request))
        # self.requests[request] = {
        _request_dict = {
            'request': request,
            'satellite': None,
            'observation': None,
            'uplink': None,
            'downlink': None,
            'status': None,
            'data_product': None,
            'scheduled_callback': callback_request_scheduled,
            'unscheduled_callback': callback_request_unscheduled,
            'ready_callback': callback_request_ready,
        }

        _pdrequest = pd.DataFrame([_request_dict])

        self._requests = pd.concat([self._requests, _pdrequest], ignore_index=True)
              
        _opportunities = find_observation_opportunities(
            [request,],
            satellites=self.satellites,
            passes_error_s=60,
            passes_horizon_deg=MIN_HORIZON_ANGLE_FOR_OBS_DEG
        )
        if len(_opportunities):
            # best_request = None
            passes = _opportunities[request]
            # for request, passes in _opportunities.items(): # Only one request, so this just unpacks the opportunities and its OK to reset best_quality below
            if len(passes):
                _best_quality = - np.inf
                _best_satellite = None
                _best_pass = None
                for satellite, satpasses in passes.items():
                    for satpass in satpasses:
                        # Check if the satellite is free at this time.
                        # Query the table of observations for 1. planned, 2. on the satellite we are examining.
                        # Check by time if there is something nearby.
                        # If there is, back off.
                        _pass_is_feasible = self.screen_request_for_feasibility(satpass.highest)
                        if (_pass_is_feasible == False):
                            continue

                        _quality = observation_quality(satpass.highest)
                        if _quality >= _best_quality:
                            _best_quality = _quality
                            _best_satellite = satellite
                            _best_pass = satpass
                        # print("{}: quality {}".format(satpass.highest, observation_quality(satpass.highest)))

                print("Best request: {} with {}".format(_best_pass, _best_satellite))
                if (_best_pass is None):
                    print("All observation opportunities are conflicting")
                    self._requests.loc[self._requests['request']==request, 'status'] = "All observation opportunities are conflicting"
                    callback_request_unscheduled("All observation opportunities are conflicting")
                    return -5
            else:
                print("No observation opportunities here")
                print(_opportunities)
                # self.requests[request]['status'] = "No observation opportunities"
                self._requests.loc[self._requests['request']==request, 'status'] = "No observation opportunities"
                callback_request_unscheduled("No observation opportunities")
                return -1
        else:
            print("Something wrong with requests list, did you pass a request?")
        
        # Pick the best contact to tell the satellite. What if the contact is after the request? Whoops.
        _, ul_comm_opportunities = find_contact_opportunities(
            ground_stations=self.ground_stations,
            satellites=self.satellites,
            min_time=current_time,
            max_time=_best_pass.highest.time,
            passes_error_s=60,
            passes_horizon_deg=MIN_HORIZON_ANGLE_FOR_PASS_DEG,
        )

        if ((_best_satellite in ul_comm_opportunities.keys()) and (len(ul_comm_opportunities[_best_satellite])))==0:
            # No contacts!
            print("No timely contact! Maybe we were too greedy")
            # self.requests[request]['status'] = "No timely contact";
            self._requests.loc[self._requests['request']==request, 'status'] = "No timely contact";
            callback_request_unscheduled("No timely contact")
            return -2
        
        earliest_comm_opportunity = None
        earliest_comm_opportunity_station = None
        for comm_opportunity in ul_comm_opportunities[_best_satellite]:
            if self.screen_pass_for_feasibility(comm_opportunity[1], screen_against_comm_passes=False):
                earliest_comm_opportunity = comm_opportunity[1]
                earliest_comm_opportunity_station = comm_opportunity[0]

        if ((earliest_comm_opportunity is None) or (earliest_comm_opportunity_station is None)):
            print("No timely unconflicted contact! Maybe we were too greedy")
            # self.requests[request]['status'] = "No timely contact";
            self._requests.loc[self._requests['request']==request, 'status'] = "No timely unconflicted contact";
            callback_request_unscheduled("No timely unconflicted contact")
            return -2.5

        _best_sat_object = None
        for sat in self.satellites:
            if sat.name == _best_satellite.name:
                _best_sat_object = sat
        if (_best_sat_object is None):
            print("ERROR! Something wrong with finding the satellite")
            # self.requests[request]['status'] = "Could not find best satellite";
            self._requests.loc[self._requests['request']==request, 'status'] = "Could not find best satellite";

            callback_request_unscheduled("Could not find best satellite")
            return -3

        # Let's also schedule a downlink after the event
        # Find downlink opportunities
        _, _dl_comm_opportunities = find_contact_opportunities(
            ground_stations=self.ground_stations,
            satellites=[_best_sat_object, ],
            min_time=_best_pass.highest.time+_best_pass.highest.duration,
            max_time=_best_pass.highest.time+_best_pass.highest.duration+dt.timedelta(hours=48),
            passes_error_s=60,
            passes_horizon_deg=MIN_HORIZON_ANGLE_FOR_PASS_DEG,
        )
        # # Schedule downlink events for those
        if _best_sat_object not in _dl_comm_opportunities.keys() or len(_dl_comm_opportunities[_best_sat_object]) == 0:
            print("  Could not find a suitable downlink")
            # self.requests[request]['status'] = "Could not find best satellite";
            self._requests.loc[self._requests['request']==request, 'status'] = "No timely downlink";
            callback_request_unscheduled("No timely downlink")
            return -4
        
        ## 

        # Passes are sorted by time. An we checked above that there is at least one pass
        _preferred_downlink_pass = _dl_comm_opportunities[_best_sat_object][0]
        _dl_station = _preferred_downlink_pass[0]
        _dl_pass = _preferred_downlink_pass[1]

        _dl_station = None
        _dl_pass = None
        for comm_opportunity in _dl_comm_opportunities[_best_sat_object]:
            if self.screen_pass_for_feasibility(comm_opportunity[1], screen_against_comm_passes=False):
                _dl_pass = comm_opportunity[1]
                _dl_station = comm_opportunity[0]

        if ((_dl_pass is None) or (_dl_station is None)):
            print("  Could not find a suitable unconflicted downlink")
            self._requests.loc[self._requests['request']==request, 'status'] = "No timely unconflicted downlink";
            callback_request_unscheduled("No timely unconflicted downlink")
            return -4.5

        #

        schedule_observation_uplink(self.world, _best_sat_object, earliest_comm_opportunity, _best_pass.highest, earliest_comm_opportunity_station)
        schedule_sat_downlink(_world=self.world, satellite=_best_sat_object, comm_pass = _dl_pass, station = _dl_station, constellation_scheduler=self)
        # # Do downlink
        
        # # Schedule an event where we tell the satellite about this. The event calls schedule_observation
        # - pick the earliest opportunity
        # - check it's early enough (if not return)
        # - schedule an Event at the comm opportunity time that, when triggered, calls schedule_observation with best_request
        self._requests.loc[self._requests['request']==request, 'satellite'] = _best_sat_object
        self._requests.loc[self._requests['request']==request, 'observation'] = _best_pass.highest
        self._requests.loc[self._requests['request']==request, 'uplink'] = earliest_comm_opportunity
        self._requests.loc[self._requests['request']==request, 'downlink'] = _dl_pass
        self._requests.loc[self._requests['request']==request, 'status'] = "Scheduled";

        callback_request_scheduled(_best_pass.highest)
        return 0

    def schedule_downlinks(
        self,
        current_time: dt.datetime=dt.datetime.now(dt.timezone.utc).replace(tzinfo=None),
        max_time: dt.datetime=dt.datetime.now(dt.timezone.utc).replace(tzinfo=None)+dt.timedelta(hours=24)
    ):
        # Find downlink opportunities
        _, comm_opportunities = find_contact_opportunities(
            ground_stations=self.ground_stations,
            satellites=self.satellites,
            min_time=current_time,
            max_time=max_time,
            passes_error_s=60,
            passes_horizon_deg=MIN_HORIZON_ANGLE_FOR_PASS_DEG,
        )
        # Schedule downlink events for those
        for _sat, _comm_passes_and_stations in comm_opportunities.items():
            # print(_comm_pass_and_station)
            # print(_sat)
            for _comm_pass_and_station in _comm_passes_and_stations:
                _station = _comm_pass_and_station[0]
                _comm_pass = _comm_pass_and_station[1]
                schedule_sat_downlink(_world=self.world, satellite=_sat, comm_pass = _comm_pass, station = _station, constellation_scheduler=self)
        # Do downlink
    
    def get_request_status(self, request: ObservationRequest):
        return self._requests[self._requests['request'] == request].status
        if request in self.requests:
            return self.requests[request].status
        else:
            return None

In [11]:
def schedule_observation(_world, satellite: Satellite, obs_opportunity):
    # An observation fires at the time of the observation. It adds known events to the satellite's known_phenomena store.
    # TODO it also adds an observation product to the satellite's 

    # This first bit is quite redundant. What you want is to maintain events for individual agents and then a global copy, right?
    satellite.scheduled_observations.append(obs_opportunity)

    def unlock_satellite(_satellite):
        if _satellite.attitude_controller_state == AttitudeController.INSTRUMENT:
            _satellite.attitude_controller_state = AttitudeController.FREE
            _satellite.busy_with = None
            return True
        else:
            return False

    def lock_satellite_and_observe(_satellite, _obs_opportunity, __world):
        if _satellite.attitude_controller_state != AttitudeController.FREE:
            print("Satellite busy ({})! Sat {} attempted observation {}".format(_satellite.attitude_controller_state, _satellite, _obs_opportunity))
            return False
        _satellite.attitude_controller_state = AttitudeController.INSTRUMENT
        _satellite.busy_with = _obs_opportunity

        _unlock_event = Event(
            name = "Unlock satellite after obs, sat {}".format(_satellite.name),
            time = _obs_opportunity.time+_obs_opportunity.duration,
            action_callable = lambda _sate=satellite: unlock_satellite(_sate)
        )
        _world.add_event(_unlock_event)
        return __world.do_observation(_obs_opportunity, _satellite)
    
    _event = ObservationEvent(
        name = "Obs, sat {}".format(satellite.name),
        time = obs_opportunity.time,
        # Note the kludge of default inputs to make sure the closure works and we capture the variables at the time of creation
        action_callable = lambda _opp=obs_opportunity, _sate=satellite, __world=_world: lock_satellite_and_observe(_sate, _opp, __world),
        satellite=satellite,
        opportunity=obs_opportunity
    )
    _world.add_event(_event)

    return 0

def schedule_observation_uplink(_world: World, satellite: Satellite, comm_opportunity: ObservationPass, obs_opportunity: ObservationOpportunity, station: Location):
    # An observation uplink fires at the time of the uplink. It adds an event that will trigger the observation at the appropriate time. 
    if (comm_opportunity.highest.time>obs_opportunity.time):
        raise ValueError("Uplink {} is after related observation {}".format(comm_opportunity, obs_opportunity))
    
    def unlock_satellite(_satellite, verbose=False):
        if (_satellite.attitude_controller_state == AttitudeController.COMMUNICATION 
            and _satellite.busy_with == comm_opportunity):
            _satellite.attitude_controller_state = AttitudeController.FREE
            _satellite.busy_with = None
            return True
        else:
            if verbose:
                print("Could not unlock satellite after ul comm opportunity with station {} at {}!".format(station, comm_opportunity.highest.time))
            return False
        
    def do_uplink_event(__world: World, __satellite: Satellite, __obsopp: ObservationOpportunity):
        if __satellite.attitude_controller_state == AttitudeController.INSTRUMENT:
            print("Satellite busy! Attempted uplink to sat {} from station {}".format(__satellite, station))
            return False
        __satellite.attitude_controller_state == AttitudeController.COMMUNICATION
        __satellite.busy_with = comm_opportunity
        _unlock_event = Event(
            name = "Unlock uplink, station {} to sat {}".format(station.name, __satellite.name),
            time = comm_opportunity.fall.time,
            action_callable = lambda _sate=satellite: unlock_satellite(_sate)
        )
        __world.add_event(_unlock_event)
        return schedule_observation(__world, __satellite, __obsopp)

    _event = CommunicationEvent(
        name="Uplink, station {} to sat {}".format(station.name, satellite.name),
        time = comm_opportunity.highest.time,
        # action_callable = lambda _w=_world, _s=satellite, _o=obs_opportunity: schedule_observation(_w, _s, _o)
        action_callable = lambda _w=_world, _s=satellite, _o=obs_opportunity: do_uplink_event(_w, _s, _o),
        satellite=satellite,
        station=station,
        comm_pass=comm_opportunity,
    )
    _world.add_event(_event)

def schedule_sat_downlink(
    _world: World,
    satellite: Satellite,
    comm_pass: ObservationPass,
    station: Location,
    constellation_scheduler: ConstellationGroundScheduler
):
    
    def unlock_satellite(_satellite, verbose=False):
        if (_satellite.attitude_controller_state == AttitudeController.COMMUNICATION 
            and _satellite.busy_with == comm_pass):
            _satellite.attitude_controller_state = AttitudeController.FREE
            _satellite.busy_with = None
            return True
        else:
            if verbose:
                print("Could not unlock satellite after dl comm opportunity with station {} at {}!".format(station, comm_pass.highest.time))
            return False
        
    def end_downlink_event(_spacecraft: Satellite, _scheduler: ConstellationGroundScheduler, _comm_pass: ObservationPass):
        do_downlink(spacecraft=_spacecraft, scheduler=_scheduler, comm_pass=_comm_pass)
        return unlock_satellite(_spacecraft)

    def start_downlink_event(_spacecraft: Satellite, _scheduler: ConstellationGroundScheduler, _comm_pass: ObservationPass):
        if _spacecraft.attitude_controller_state == AttitudeController.INSTRUMENT:
            print("Satellite busy! Attempted downlink to sat {} from station {} at ".format(_spacecraft, station, _comm_pass.rise.time))
            return False
        _spacecraft.attitude_controller_state = AttitudeController.COMMUNICATION
        _spacecraft.busy_with = _comm_pass

        _end_event = Event(
            name="End of downlink, station {} from sat {}".format(station.name, satellite.name),
            time = _comm_pass.fall.time,
            # action_callable = lambda _cs=_scheduler, _s=_spacecraft, _c=_comm_pass: do_downlink(spacecraft=_s, scheduler=_cs, comm_pass=_c)
            action_callable = lambda _cs=_scheduler, _s=_spacecraft, _c=_comm_pass: end_downlink_event(_spacecraft=_s, _scheduler=_cs, _comm_pass=_c)
        )
        _world.add_event(_end_event)
        return True


    _event = CommunicationEvent(
        name="Downlink, station {} from sat {}".format(station.name, satellite.name),
        time = comm_pass.rise.time,
        # action_callable = lambda _cs=constellation_scheduler, _s=satellite, _c=comm_pass: do_downlink(spacecraft=_s, scheduler=_cs, comm_pass=_c)
        action_callable = lambda _cs=constellation_scheduler, _s=satellite, _c=comm_pass: start_downlink_event(_spacecraft=_s, _scheduler=_cs, _comm_pass=_c),
        satellite=satellite,
        station=station,
        comm_pass=comm_pass
    )
    _world.add_event(_event)

Something simple. 
- [X] Create a world.
- [X] Add satellites to it.
- [X] Add observation opportunities to the satellites manually
- [X] Click until out of events
- [X] Add a better way to add observation opportunities!
- [X] Add a ConstellationScheduler

In [12]:
phenomena = [
    Phenomenon(
        lon_deg = -118.,
        lat_deg = 34.,
        alt_km=0.307,
        start_time=min_time,
        end_time=max_time,

    ),
    Phenomenon(8., 45.,  alt_km=0.216, start_time=min_time, end_time=max_time),
    Phenomenon(-80., 34., alt_km=0.041, start_time=min_time, end_time=max_time),
]

In [13]:
phenomena_cities = [
    Phenomenon(
        lon_deg = city.lon_deg,
        lat_deg = city.lat_deg,
        alt_km=city.alt_km,
        start_time=city.min_time,
        end_time=city.max_time,
        name=city.name
    ) for city in one_hundred_sampled_cities
]

In [14]:
one_hundred_sampled_cities[0].min_time

datetime.datetime(2025, 12, 17, 19, 36, 56, 704608)

In [15]:
satellite_agents_simple = [
    Satellite("LOFT YAM-3", Orbital("YAM-3", tle_file="TLEs.txt")),
    Satellite("LOFT YAM-5", Orbital("YAM-5", tle_file="TLEs.txt")),
    Satellite("LOFT YAM-6", Orbital("YAM-6", tle_file="TLEs.txt")),
    Satellite("LOFT YAM-7", Orbital("YAM-7", tle_file="TLEs.txt")),
    Satellite("LOFT YAM-8", Orbital("YAM-8", tle_file="TLEs.txt")),
    Satellite("LOFT YAM-10", Orbital("YAM-10", tle_file="TLEs.txt")),
    Satellite("Ubotica CogniSat-6 HAMMER", Orbital("HAMMER", tle_file="TLEs.txt")),
    # "LOFT YAM-3": Orbital("YAM-3"),
]

In [16]:
world = World(satellites = satellite_agents_simple, phenomena=phenomena)

Manually add observation opportunities

In [17]:
obs_requests = [
    ObservationRequest(-118., 34., min_time=min_time, max_time=max_time, alt_km=0.307),
    ObservationRequest(8., 45., min_time=min_time, max_time=max_time, alt_km=0.216),
    ObservationRequest(-80., 34., min_time=min_time, max_time=max_time, alt_km=0.041),
]

In [18]:
observation_opportunities = find_observation_opportunities(obs_requests, satellites)

In [19]:
best_request = {r: None for r in obs_requests}

for request, passes in observation_opportunities.items():
    _best_quality = - np.inf
    _best_satellite = None
    _best_pass = None
    for satellite, satpasses in passes.items():
        for satpass in satpasses:
            _quality = observation_quality(satpass.highest)
            if _quality >= _best_quality:
                _best_quality = _quality
                _best_satellite = satellite
                _best_pass = satpass
            # print("{}: quality {}".format(satpass.highest, observation_quality(satpass.highest)))
    best_request[request] = (_best_satellite, _best_pass)

In [20]:
for req, opp in best_request.items():
    for _sat in world.satellites:
        if _sat.name == opp[0].name:
            _opportunity = opp[1].highest
            print("{} {} {}".format(_sat.name, req, _opportunity))

            schedule_observation(world, _sat, _opportunity)

LOFT YAM-8 Request  | Lon -118.0°, lat 34.0°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB Observation  at 2025-12-18 07:22:59.796290 with RGB. Look angle 286.87826626482735 | 35.83454664082302 az/dec deg, zenith angle 168.00268117738023 deg, range 854.8809556481538 km, duration 0:01:00
Ubotica CogniSat-6 HAMMER Request  | Lon 8.0°, lat 45.0°, alt 0.216 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB Observation  at 2025-12-18 02:08:15.875739 with RGB. Look angle 256.044871170689 | 40.86937767277908 az/dec deg, zenith angle 140.4418619010881 deg, range 536.0091425489915 km, duration 0:01:00
Ubotica CogniSat-6 HAMMER Request  | Lon -80.0°, lat 34.0°, alt 0.041 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB Observation  at 2025-12-18 08:12:43.064180 with RGB. Look angle 263.8518606145309 | 32.50217122116019 az/dec deg, zenith angle 140.2826118540574 deg, range 633.2634279108207 km, duration 0:01:00

In [21]:
retcode = 1
while (retcode !=0):
    print("\nTick!")
    print(world.events)
    # print({sat.name: sat.scheduled_observations for sat in world.agents if len(sat.scheduled_observations)})
    retcode = world.tick()

Tick!
[Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 02:08:15.875739, Event Obs, sat LOFT YAM-8 at 2025-12-18 07:22:59.796290, Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 08:12:43.064180]
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 02:08:15.875739

Tick!
[Event Unlock satellite after obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 02:09:15.875739, Event Obs, sat LOFT YAM-8 at 2025-12-18 07:22:59.796290, Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 08:12:43.064180]
Executing Event Unlock satellite after obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 02:09:15.875739

Tick!
[Event Obs, sat LOFT YAM-8 at 2025-12-18 07:22:59.796290, Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 08:12:43.064180]
Executing Event Obs, sat LOFT YAM-8 at 2025-12-18 07:22:59.796290

Tick!
[Event Unlock satellite after obs, sat LOFT YAM-8 at 2025-12-18 07:23:59.796290, Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 08:12:43.064180]
Executing Event Unlock satellite after obs, sat LOFT YAM-8 at 2025-12-18 07:23:59.796290

Tick!
[Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 08:12:43.064180]
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 08:12:43.064180

Tick!
[Event Unlock satellite after obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 08:13:43.064180]
Executing Event Unlock satellite after obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 08:13:43.064180

In [22]:
[sat.known_phenomena for sat in world.satellites]

[[],
 [],
 [],
 [],
 [[: Lon -118.0, lat 34.0, alt 0.307, start 2025-12-17 19:36:56.704608, end 2025-12-18 19:36:56.704608]],
 [],
 [[: Lon 8.0, lat 45.0, alt 0.216, start 2025-12-17 19:36:56.704608, end 2025-12-18 19:36:56.704608],
  [: Lon -80.0, lat 34.0, alt 0.041, start 2025-12-17 19:36:56.704608, end 2025-12-18 19:36:56.704608]]]

In [23]:
satellite_agents_world = [
    Satellite("LOFT YAM-3", Orbital("YAM-3", tle_file="TLEs.txt")),
    Satellite("LOFT YAM-5", Orbital("YAM-5", tle_file="TLEs.txt")),
    Satellite("LOFT YAM-6", Orbital("YAM-6", tle_file="TLEs.txt")),
    Satellite("LOFT YAM-7", Orbital("YAM-7", tle_file="TLEs.txt")),
    Satellite("LOFT YAM-8", Orbital("YAM-8", tle_file="TLEs.txt")),
    Satellite("LOFT YAM-10", Orbital("YAM-10", tle_file="TLEs.txt")),
    Satellite("Ubotica CogniSat-6 HAMMER", Orbital("HAMMER", tle_file="TLEs.txt")),
    # "LOFT YAM-3": Orbital("YAM-3"),
]

In [24]:
world_with_cities = World(satellites = satellite_agents_world, phenomena=phenomena_cities)

In [25]:
best_request_cities = {r: None for r in one_hundred_sampled_cities}

observation_opportunities_cities = find_observation_opportunities(one_hundred_sampled_cities, satellite_agents_world)

for request, passes in observation_opportunities_cities.items():
    _best_quality = - np.inf
    _best_satellite = None
    _best_pass = None
    for satellite, satpasses in passes.items():
        for satpass in satpasses:
            _quality = observation_quality(satpass.highest)
            if _quality >= _best_quality:
                _best_quality = _quality
                _best_satellite = satellite
                _best_pass = satpass
            # print("{}: quality {}".format(satpass.highest, observation_quality(satpass.highest)))
    best_request_cities[request] = (_best_satellite, _best_pass)

In [26]:
for req, opp in best_request_cities.items():
    for _sat in world_with_cities.satellites:
        # Give the event to the right agent
        if _sat.name == opp[0].name:
            # The opportunity is the middle of the pass
            _opportunity = opp[1].highest
            # print("{} {} {}".format(_sat.name, req, _opportunity))

            # This is quite redundant. What you want is to maintain events for individual agents and then a global copy, right?
            _sat.scheduled_observations.append(_opportunity)
            _event = Event(
                name="Observation for {}: {}".format(opp[0].name, opp[1]),
                time = _opportunity.time,
                # The magic is here: we add an event that does an observation and stores the result in the agent's known_phenomena bin
                # Note the kludge of default inputs to make sure the closure works and we capture the variables at the time of creation
                # action_callable = lambda _opp=_opportunity, _satname=_sat.name: print("{} with {}".format(_opp, _satname)) #_sat.known_phenomena.append(world.do_observation(_opportunity, _sat))
                action_callable = lambda _opp=_opportunity, _sate=_sat: world_with_cities.do_observation(_opp, _sate)
            )
            world_with_cities.add_event(_event)

In [27]:
retcode = 1
while (retcode !=0):
    # print("Tick!")
    # print(world_cities.events)
    # print({sat.name: sat.scheduled_observations for sat in world.agents if len(sat.scheduled_observations)})
    retcode = world_with_cities.tick()

Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-17 19:47:55.586547, highest: 2025-12-17 19:52:32.873357, fall: 2025-12-17 19:57:05.470163 at 2025-12-17 19:52:32.873357
Executing Event Observation for LOFT YAM-5: Pass start: 2025-12-17 19:47:40.763658, highest: 2025-12-17 19:53:03.875040, fall: 2025-12-17 19:58:29.982965 at 2025-12-17 19:53:03.875040
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-17 19:52:43.590449, highest: 2025-12-17 19:57:19.145453, fall: 2025-12-17 20:02:00.699128 at 2025-12-17 19:57:19.145453
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-17 19:52:48.409123, highest: 2025-12-17 19:57:27.955638, fall: 2025-12-17 20:02:07.501741 at 2025-12-17 19:57:27.955638
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-17 19:56:30.406949, highest: 2025-12-17 20:00:55.427479, fall: 2025-12-17 20:05:20.908590 at 2025-12-17 20:00:55.427479
Executing Event Observation for LOFT YAM-8: Pass start: 2025-12-17 20:09:03.542877, highest: 2025-12-17 20:14:53.770192, fall: 2025-12-17 20:20:40.144450 at 2025-12-17 20:14:53.770192
Executing Event Observation for LOFT YAM-8: Pass start: 2025-12-17 20:15:12.805278, highest: 2025-12-17 20:21:01.232783, fall: 2025-12-17 20:26:51.640673 at 2025-12-17 20:21:01.232783
Executing Event Observation for LOFT YAM-8: Pass start: 2025-12-17 20:22:28.622811, highest: 2025-12-17 20:28:15.013954, fall: 2025-12-17 20:34:11.005747 at 2025-12-17 20:28:15.013954
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-17 20:27:56.235086, highest: 2025-12-17 20:33:06.901875, fall: 2025-12-17 20:38:21.586305 at 2025-12-17 20:33:06.901875
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-17 20:30:03.234827, highest: 2025-12-17 20:35:41.602626, fall: 2025-12-17 20:41:12.950911 at 2025-12-17 20:35:41.602626
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-17 20:30:07.447786, highest: 2025-12-17 20:35:46.173251, fall: 2025-12-17 20:41:17.741830 at 2025-12-17 20:35:46.173251
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-17 20:30:16.996815, highest: 2025-12-17 20:35:52.165744, fall: 2025-12-17 20:41:25.461494 at 2025-12-17 20:35:52.165744
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-17 20:31:01.622779, highest: 2025-12-17 20:36:18.096906, fall: 2025-12-17 20:41:40.099036 at 2025-12-17 20:36:18.096906
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-17 21:20:12.858026, highest: 2025-12-17 21:24:57.079526, fall: 2025-12-17 21:29:40.445475 at 2025-12-17 21:24:57.079526
Executing Event Observation for LOFT YAM-10: Pass start: 2025-12-17 21:34:32.079833, highest: 2025-12-17 21:40:46.842469, fall: 2025-12-17 21:46:59.230665 at 2025-12-17 21:40:46.842469
Executing Event Observation for LOFT YAM-8: Pass start: 2025-12-17 21:50:36.582240, highest: 2025-12-17 21:56:12.036627, fall: 2025-12-17 22:01:51.264789 at 2025-12-17 21:56:12.036627
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-17 21:55:11.056536, highest: 2025-12-17 22:00:47.379054, fall: 2025-12-17 22:06:15.187857 at 2025-12-17 22:00:47.379054
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-17 21:55:11.956787, highest: 2025-12-17 22:00:48.202562, fall: 2025-12-17 22:06:16.244408 at 2025-12-17 22:00:48.202562
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-17 21:58:50.665814, highest: 2025-12-17 22:04:13.972007, fall: 2025-12-17 22:09:41.238126 at 2025-12-17 22:04:13.972007
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-17 21:59:43.800109, highest: 2025-12-17 22:05:00.483900, fall: 2025-12-17 22:10:17.766857 at 2025-12-17 22:05:00.483900
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-17 22:54:32.283364, highest: 2025-12-17 22:59:08.610253, fall: 2025-12-17 23:03:53.563414 at 2025-12-17 22:59:08.610253
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-17 22:57:49.235372, highest: 2025-12-17 23:02:20.120954, fall: 2025-12-17 23:06:55.810869 at 2025-12-17 23:02:20.120954
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-17 23:33:54.979195, highest: 2025-12-17 23:39:12.720098, fall: 2025-12-17 23:44:34.911280 at 2025-12-17 23:39:12.720098
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 00:32:09.575452, highest: 2025-12-18 00:36:52.091468, fall: 2025-12-18 00:41:31.206350 at 2025-12-18 00:36:52.091468
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 00:33:54.857807, highest: 2025-12-18 00:38:10.048407, fall: 2025-12-18 00:42:28.891197 at 2025-12-18 00:38:10.048407
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 00:36:06.040394, highest: 2025-12-18 00:40:53.217603, fall: 2025-12-18 00:45:36.834566 at 2025-12-18 00:40:53.217603
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-18 01:03:04.018508, highest: 2025-12-18 01:08:36.256539, fall: 2025-12-18 01:14:00.830839 at 2025-12-18 01:08:36.256539
Executing Event Observation for LOFT YAM-6: Pass start: 2025-12-18 01:06:41.286192, highest: 2025-12-18 01:12:01.204149, fall: 2025-12-18 01:17:24.553610 at 2025-12-18 01:12:01.204149
Executing Event Observation for LOFT YAM-6: Pass start: 2025-12-18 01:07:50.705644, highest: 2025-12-18 01:13:07.151793, fall: 2025-12-18 01:18:28.381898 at 2025-12-18 01:13:07.151793
Executing Event Observation for LOFT YAM-8: Pass start: 2025-12-18 01:09:46.005586, highest: 2025-12-18 01:15:42.597422, fall: 2025-12-18 01:21:35.587455 at 2025-12-18 01:15:42.597422
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 01:54:11.551889, highest: 2025-12-18 01:58:50.190309, fall: 2025-12-18 02:03:22.522116 at 2025-12-18 01:58:50.190309
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 02:01:20.322173, highest: 2025-12-18 02:05:53.955238, fall: 2025-12-18 02:10:26.647920 at 2025-12-18 02:05:53.955238
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 02:05:49.198385, highest: 2025-12-18 02:10:40.499191, fall: 2025-12-18 02:15:19.952308 at 2025-12-18 02:10:40.499191
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 02:06:04.741966, highest: 2025-12-18 02:10:53.392349, fall: 2025-12-18 02:15:35.751903 at 2025-12-18 02:10:53.392349
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 02:07:10.638587, highest: 2025-12-18 02:11:52.174644, fall: 2025-12-18 02:16:32.154420 at 2025-12-18 02:11:52.174644
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-18 02:30:11.601606, highest: 2025-12-18 02:35:48.334452, fall: 2025-12-18 02:41:15.747090 at 2025-12-18 02:35:48.334452
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-18 02:33:36.598692, highest: 2025-12-18 02:39:04.979793, fall: 2025-12-18 02:44:34.181216 at 2025-12-18 02:39:04.979793
Executing Event Observation for LOFT YAM-8: Pass start: 2025-12-18 04:10:26.328905, highest: 2025-12-18 04:16:00.300893, fall: 2025-12-18 04:21:35.180756 at 2025-12-18 04:16:00.300893
Executing Event Observation for LOFT YAM-8: Pass start: 2025-12-18 04:10:46.687647, highest: 2025-12-18 04:16:18.041150, fall: 2025-12-18 04:21:51.790032 at 2025-12-18 04:16:18.041150
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-18 04:14:05.656523, highest: 2025-12-18 04:19:22.328976, fall: 2025-12-18 04:24:40.528707 at 2025-12-18 04:19:22.328976
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-18 04:17:04.550640, highest: 2025-12-18 04:22:41.007345, fall: 2025-12-18 04:28:09.239762 at 2025-12-18 04:22:41.007345
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-18 04:20:00.958428, highest: 2025-12-18 04:25:16.478424, fall: 2025-12-18 04:30:37.181629 at 2025-12-18 04:25:16.478424
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-18 04:24:08.929717, highest: 2025-12-18 04:29:44.749631, fall: 2025-12-18 04:35:16.703405 at 2025-12-18 04:29:44.749631
Executing Event Observation for LOFT YAM-8: Pass start: 2025-12-18 05:45:33.837359, highest: 2025-12-18 05:51:23.683459, fall: 2025-12-18 05:57:15.232083 at 2025-12-18 05:51:23.683459
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 06:22:27.657109, highest: 2025-12-18 06:27:11.866635, fall: 2025-12-18 06:31:59.437295 at 2025-12-18 06:27:11.866635
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 06:38:54.060528, highest: 2025-12-18 06:43:13.699713, fall: 2025-12-18 06:47:37.485196 at 2025-12-18 06:43:13.699713
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 06:38:52.943346, highest: 2025-12-18 06:43:15.727931, fall: 2025-12-18 06:47:43.005542 at 2025-12-18 06:43:15.727931
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 06:39:04.849520, highest: 2025-12-18 06:43:21.079136, fall: 2025-12-18 06:47:39.990187 at 2025-12-18 06:43:21.079136
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 06:38:54.344294, highest: 2025-12-18 06:43:33.048376, fall: 2025-12-18 06:48:08.714960 at 2025-12-18 06:43:33.048376
Executing Event Observation for LOFT YAM-8: Pass start: 2025-12-18 07:16:27.138560, highest: 2025-12-18 07:22:20.853353, fall: 2025-12-18 07:28:17.560884 at 2025-12-18 07:22:20.853353
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 08:08:40.981248, highest: 2025-12-18 08:13:19.380167, fall: 2025-12-18 08:18:05.977076 at 2025-12-18 08:13:19.380167
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 08:10:11.008486, highest: 2025-12-18 08:14:53.379517, fall: 2025-12-18 08:19:34.052506 at 2025-12-18 08:14:53.379517
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 09:43:45.519331, highest: 2025-12-18 09:48:04.138453, fall: 2025-12-18 09:52:25.802439 at 2025-12-18 09:48:04.138453
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-18 13:29:23.373581, highest: 2025-12-18 13:35:00.482803, fall: 2025-12-18 13:40:35.513224 at 2025-12-18 13:35:00.482803
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-18 13:47:31.336519, highest: 2025-12-18 13:52:55.122571, fall: 2025-12-18 13:58:21.196267 at 2025-12-18 13:52:55.122571
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-18 13:47:29.340357, highest: 2025-12-18 13:52:55.200584, fall: 2025-12-18 13:58:23.307073 at 2025-12-18 13:52:55.200584
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-18 15:10:17.176166, highest: 2025-12-18 15:15:55.324244, fall: 2025-12-18 15:21:28.363023 at 2025-12-18 15:15:55.324244
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-18 15:11:05.824402, highest: 2025-12-18 15:16:37.587138, fall: 2025-12-18 15:22:01.594926 at 2025-12-18 15:16:37.587138
Executing Event Observation for LOFT YAM-8: Pass start: 2025-12-18 15:11:42.521605, highest: 2025-12-18 15:17:36.833524, fall: 2025-12-18 15:23:23.063227 at 2025-12-18 15:17:36.833524
Executing Event Observation for LOFT YAM-8: Pass start: 2025-12-18 15:14:46.538957, highest: 2025-12-18 15:20:34.641484, fall: 2025-12-18 15:26:17.481063 at 2025-12-18 15:20:34.641484
Executing Event Observation for LOFT YAM-8: Pass start: 2025-12-18 15:14:47.339492, highest: 2025-12-18 15:20:45.523765, fall: 2025-12-18 15:26:33.459507 at 2025-12-18 15:20:45.523765
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-18 15:15:41.978961, highest: 2025-12-18 15:21:10.187349, fall: 2025-12-18 15:26:47.169954 at 2025-12-18 15:21:10.187349
Executing Event Observation for LOFT YAM-8: Pass start: 2025-12-18 15:16:10.578258, highest: 2025-12-18 15:21:58.025488, fall: 2025-12-18 15:27:45.067089 at 2025-12-18 15:21:58.025488
Executing Event Observation for LOFT YAM-8: Pass start: 2025-12-18 15:16:14.288581, highest: 2025-12-18 15:22:04.067880, fall: 2025-12-18 15:27:58.352380 at 2025-12-18 15:22:04.067880
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-18 15:18:39.289593, highest: 2025-12-18 15:24:03.273701, fall: 2025-12-18 15:29:32.265356 at 2025-12-18 15:24:03.273701
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-18 15:19:30.388948, highest: 2025-12-18 15:24:58.595991, fall: 2025-12-18 15:30:30.367991 at 2025-12-18 15:24:58.595991
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-18 15:19:31.752816, highest: 2025-12-18 15:25:00.226682, fall: 2025-12-18 15:30:32.955557 at 2025-12-18 15:25:00.226682
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-18 15:19:38.693556, highest: 2025-12-18 15:25:02.985090, fall: 2025-12-18 15:30:32.540187 at 2025-12-18 15:25:02.985090
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-18 15:20:41.784623, highest: 2025-12-18 15:25:58.377782, fall: 2025-12-18 15:31:18.060231 at 2025-12-18 15:25:58.377782
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-18 15:21:06.451862, highest: 2025-12-18 15:26:22.514907, fall: 2025-12-18 15:31:42.901216 at 2025-12-18 15:26:22.514907
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-18 16:51:32.263398, highest: 2025-12-18 16:57:00.249538, fall: 2025-12-18 17:02:31.251413 at 2025-12-18 16:57:00.249538
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-18 16:51:58.839473, highest: 2025-12-18 16:57:19.846236, fall: 2025-12-18 17:02:44.323036 at 2025-12-18 16:57:19.846236
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-18 16:52:09.510180, highest: 2025-12-18 16:57:37.797713, fall: 2025-12-18 17:03:01.925128 at 2025-12-18 16:57:37.797713
Executing Event Observation for LOFT YAM-8: Pass start: 2025-12-18 16:51:55.353617, highest: 2025-12-18 16:57:51.151062, fall: 2025-12-18 17:03:40.610640 at 2025-12-18 16:57:51.151062
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-18 16:53:41.823098, highest: 2025-12-18 16:59:10.159991, fall: 2025-12-18 17:04:50.223811 at 2025-12-18 16:59:10.159991
Executing Event Observation for LOFT YAM-8: Pass start: 2025-12-18 16:53:27.666931, highest: 2025-12-18 16:59:14.780255, fall: 2025-12-18 17:05:05.656925 at 2025-12-18 16:59:14.780255
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-18 16:54:46.651507, highest: 2025-12-18 17:00:11.611002, fall: 2025-12-18 17:05:44.460319 at 2025-12-18 17:00:11.611002
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 17:00:43.088963, highest: 2025-12-18 17:05:27.438739, fall: 2025-12-18 17:10:04.576566 at 2025-12-18 17:05:27.438739
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 17:19:12.888297, highest: 2025-12-18 17:23:55.517423, fall: 2025-12-18 17:28:37.794720 at 2025-12-18 17:23:55.517423
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 17:19:55.446455, highest: 2025-12-18 17:24:26.607779, fall: 2025-12-18 17:28:58.694798 at 2025-12-18 17:24:26.607779
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 17:20:31.045692, highest: 2025-12-18 17:24:54.943572, fall: 2025-12-18 17:29:18.937819 at 2025-12-18 17:24:54.943572
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 17:20:56.222014, highest: 2025-12-18 17:25:15.724689, fall: 2025-12-18 17:29:39.205969 at 2025-12-18 17:25:15.724689
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 17:20:51.017582, highest: 2025-12-18 17:25:18.419739, fall: 2025-12-18 17:29:50.642574 at 2025-12-18 17:25:18.419739
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 17:21:04.653903, highest: 2025-12-18 17:25:28.002958, fall: 2025-12-18 17:29:51.624645 at 2025-12-18 17:25:28.002958
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 17:22:42.074066, highest: 2025-12-18 17:27:11.994605, fall: 2025-12-18 17:31:48.943230 at 2025-12-18 17:27:11.994605
Executing Event Observation for LOFT YAM-8: Pass start: 2025-12-18 18:25:08.070867, highest: 2025-12-18 18:30:53.997960, fall: 2025-12-18 18:36:37.083082 at 2025-12-18 18:30:53.997960
Executing Event Observation for LOFT YAM-8: Pass start: 2025-12-18 18:25:23.439662, highest: 2025-12-18 18:31:06.514450, fall: 2025-12-18 18:36:51.524692 at 2025-12-18 18:31:06.514450
Executing Event Observation for LOFT YAM-7: Pass start: 2025-12-18 18:27:32.481355, highest: 2025-12-18 18:32:54.172608, fall: 2025-12-18 18:38:17.152662 at 2025-12-18 18:32:54.172608
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 18:44:30.167617, highest: 2025-12-18 18:49:01.532556, fall: 2025-12-18 18:53:33.990129 at 2025-12-18 18:49:01.532556
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 18:46:03.678416, highest: 2025-12-18 18:50:50.428741, fall: 2025-12-18 18:55:28.061147 at 2025-12-18 18:50:50.428741
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 18:49:41.240777, highest: 2025-12-18 18:53:59.149188, fall: 2025-12-18 18:58:17.652572 at 2025-12-18 18:53:59.149188
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 18:50:37.734038, highest: 2025-12-18 18:55:00.206361, fall: 2025-12-18 18:59:24.174471 at 2025-12-18 18:55:00.206361
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 18:50:33.037990, highest: 2025-12-18 18:55:08.402414, fall: 2025-12-18 18:59:53.483328 at 2025-12-18 18:55:08.402414
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 18:50:37.852346, highest: 2025-12-18 18:55:14.486092, fall: 2025-12-18 19:00:02.274211 at 2025-12-18 18:55:14.486092
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 18:50:41.780410, highest: 2025-12-18 18:55:22.835675, fall: 2025-12-18 19:00:09.925105 at 2025-12-18 18:55:22.835675
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 18:50:50.660969, highest: 2025-12-18 18:55:31.420813, fall: 2025-12-18 19:00:09.807041 at 2025-12-18 18:55:31.420813
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 18:50:53.183447, highest: 2025-12-18 18:55:36.961014, fall: 2025-12-18 19:00:13.594364 at 2025-12-18 18:55:36.961014
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 18:51:03.906869, highest: 2025-12-18 18:55:45.492974, fall: 2025-12-18 19:00:20.265564 at 2025-12-18 18:55:45.492974
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 18:51:38.072969, highest: 2025-12-18 18:56:15.734286, fall: 2025-12-18 19:01:06.979562 at 2025-12-18 18:56:15.734286
Executing Event Observation for Ubotica CogniSat-6 HAMMER: Pass start: 2025-12-18 18:52:02.929847, highest: 2025-12-18 18:56:41.730320, fall: 2025-12-18 19:01:16.075956 at 2025-12-18 18:56:41.730320

In [28]:
satellite_agents_sched = [
    Satellite("LOFT YAM-3", Orbital("YAM-3", tle_file="TLEs.txt")),
    Satellite("LOFT YAM-5", Orbital("YAM-5", tle_file="TLEs.txt")),
    Satellite("LOFT YAM-6", Orbital("YAM-6", tle_file="TLEs.txt")),
    Satellite("LOFT YAM-7", Orbital("YAM-7", tle_file="TLEs.txt")),
    Satellite("LOFT YAM-8", Orbital("YAM-8", tle_file="TLEs.txt")),
    Satellite("LOFT YAM-10", Orbital("YAM-10", tle_file="TLEs.txt")),
    Satellite("Ubotica CogniSat-6 HAMMER", Orbital("HAMMER", tle_file="TLEs.txt")),
    # "LOFT YAM-3": Orbital("YAM-3"),
]

world_with_scheduler = World(satellites = satellite_agents_sched, phenomena=phenomena)

scheduler = ConstellationGroundScheduler(satellites=satellite_agents_sched, ground_stations=ground_stations, world=world_with_scheduler)

world_with_scheduler.add_constellation(scheduler)

In [29]:
for request in obs_requests:
    scheduler.schedule_request(
        request=request,
        current_time=dt.datetime.now(dt.timezone.utc).replace(tzinfo=None),
        callback_request_scheduled=lambda obs: print("Request {} scheduled for observation {}!".format(request, obs)),
        callback_request_ready=lambda dp: print("Request {} ready with DP {}!".format(request, dp)),
        )

[Constellation] Scheduling request Request  | Lon -118.0°, lat 34.0°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-18 07:20:15.304105, highest: 2025-12-18 07:22:59.796290, fall: 2025-12-18 07:25:45.008209 with LOFT YAM-8
Request Request  | Lon -118.0°, lat 34.0°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB scheduled for observation Observation  at 2025-12-18 07:22:59.796290 with RGB. Look angle 286.87826626482735 | 35.83454664082302 az/dec deg, zenith angle 168.00268117738023 deg, range 854.8809556481538 km, duration 0:01:00!
[Constellation] Scheduling request Request  | Lon 8.0°, lat 45.0°, alt 0.216 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-18 02:06:14.598605, highest: 2025-12-18 02:08:15.875739, fall: 2025-12-18 02:10:25.553094 with Ubotica CogniSat-6 HAMMER
Request Request  | Lon 8.0°, lat 45.0°, alt 0.216 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB scheduled for observation Observation  at 2025-12-18 02:08:15.875739 with RGB. Look angle 256.044871170689 | 40.86937767277908 az/dec deg, zenith angle 140.4418619010881 deg, range 536.0091425489915 km, duration 0:01:00!
[Constellation] Scheduling request Request  | Lon -80.0°, lat 34.0°, alt 0.041 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-18 08:10:43.248176, highest: 2025-12-18 08:12:43.064180, fall: 2025-12-18 08:14:36.478198 with Ubotica CogniSat-6 HAMMER
Request Request  | Lon -80.0°, lat 34.0°, alt 0.041 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB scheduled for observation Observation  at 2025-12-18 08:12:43.064180 with RGB. Look angle 263.8518606145309 | 32.50217122116019 az/dec deg, zenith angle 140.2826118540574 deg, range 633.2634279108207 km, duration 0:01:00!

In [30]:
scheduler.schedule_downlinks()

In [31]:
retcode = 1
while (retcode !=0):
    # print("Tick!")
    retcode = world_with_scheduler.tick(print_forbidden_prefixes=["Downlink", "End of downlink"])
    # print(world_with_scheduler.events)

Executing Event Uplink, station KSAT Svalbard to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 00:45:09.716044
Executing Event Unlock uplink, station KSAT Svalbard to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 00:47:11.148030
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 02:08:15.875739
Executing Event Unlock satellite after obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 02:09:15.875739
Spacecraft Ubotica CogniSat-6 HAMMER has 1 data products to download
  Downlinked Observation  at 2025-12-18 02:08:15.875739 with RGB. Look angle 256.044871170689 | 40.86937767277908 az/dec deg, zenith angle 140.4418619010881 deg, range 536.0091425489915 km, duration 0:01:00
Request Request  | Lon -80.0°, lat 34.0°, alt 0.041 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB ready with DP Observation  at 2025-12-18 02:08:15.875739 with RGB. Look angle 256.044871170689 | 40.86937767277908 az/dec deg, zenith angle 140.4418619010881 deg, range 536.0091425489915 km, duration 0:01:00!
Executing Event Uplink, station KSAT Svalbard to sat LOFT YAM-8 at 2025-12-18 07:06:11.638327
Executing Event Unlock uplink, station KSAT Svalbard to sat LOFT YAM-8 at 2025-12-18 07:09:23.596354
Executing Event Obs, sat LOFT YAM-8 at 2025-12-18 07:22:59.796290
Executing Event Unlock satellite after obs, sat LOFT YAM-8 at 2025-12-18 07:23:59.796290
Executing Event Uplink, station KSAT Panama to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 08:06:18.880966
Executing Event Unlock uplink, station KSAT Panama to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 08:08:41.120496
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 08:12:43.064180
Executing Event Unlock satellite after obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 08:13:43.064180
Spacecraft LOFT YAM-8 has 1 data products to download
  Downlinked Observation  at 2025-12-18 07:22:59.796290 with RGB. Look angle 286.87826626482735 | 35.83454664082302 az/dec deg, zenith angle 168.00268117738023 deg, range 854.8809556481538 km, duration 0:01:00
Request Request  | Lon -80.0°, lat 34.0°, alt 0.041 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB ready with DP Observation  at 2025-12-18 07:22:59.796290 with RGB. Look angle 286.87826626482735 | 35.83454664082302 az/dec deg, zenith angle 168.00268117738023 deg, range 854.8809556481538 km, duration 0:01:00!
Spacecraft Ubotica CogniSat-6 HAMMER has 1 data products to download
  Downlinked Observation  at 2025-12-18 08:12:43.064180 with RGB. Look angle 263.8518606145309 | 32.50217122116019 az/dec deg, zenith angle 140.2826118540574 deg, range 633.2634279108207 km, duration 0:01:00
Request Request  | Lon -80.0°, lat 34.0°, alt 0.041 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB ready with DP Observation  at 2025-12-18 08:12:43.064180 with RGB. Look angle 263.8518606145309 | 32.50217122116019 az/dec deg, zenith angle 140.2826118540574 deg, range 633.2634279108207 km, duration 0:01:00!

In [32]:
# scheduler.requests

In [33]:
scheduler._requests

,request,satellite,observation,uplink,downlink,status,data_product,scheduled_callback,unscheduled_callback,ready_callback
0,"Request | Lon -118.0°, lat 34.0°, alt 0.307 k...",LOFT YAM-8,Observation at 2025-12-18 07:22:59.796290 wit...,"Pass start: 2025-12-18 07:03:01.423364, highes...","Pass start: 2025-12-20 06:43:43.973353, highes...",OK! Data received,Observation at 2025-12-18 07:22:59.796290 wit...,<function <lambda> at 0x12a433560>,<function ConstellationGroundScheduler.<lambda...,<function <lambda> at 0x12a4336a0>
1,"Request | Lon 8.0°, lat 45.0°, alt 0.216 km f...",Ubotica CogniSat-6 HAMMER,Observation at 2025-12-18 02:08:15.875739 wit...,"Pass start: 2025-12-18 00:43:06.288187, highes...","Pass start: 2025-12-20 01:40:12.534339, highes...",OK! Data received,Observation at 2025-12-18 02:08:15.875739 wit...,<function <lambda> at 0x12a5d4680>,<function ConstellationGroundScheduler.<lambda...,<function <lambda> at 0x12a5d4720>
2,"Request | Lon -80.0°, lat 34.0°, alt 0.041 km...",Ubotica CogniSat-6 HAMMER,Observation at 2025-12-18 08:12:43.064180 wit...,"Pass start: 2025-12-18 08:04:11.138383, highes...","Pass start: 2025-12-20 07:30:37.419572, highes...",OK! Data received,Observation at 2025-12-18 08:12:43.064180 wit...,<function <lambda> at 0x12a5e8040>,<function ConstellationGroundScheduler.<lambda...,<function <lambda> at 0x12a5e80e0>

Where do we go from here?

The obvious: add conflicts between observations. For now, we can stay in discrete land where an opportunity is an instantaneous thing. Or we can create multiple copies all along the path.
Conflict: two opportunities are on the same satellite and closer than some amount of time. The time should account for (i) some fixed setup (think "wait for the mirror to stop flapping") plus some time related to reorientation.
This misses the fact that one could point the spacecraft slightly away from the target and still get it. 
Can we get that in pre-processing?

Solve the one-off scheduling problem with constraints (greedy, find the best observation that is feasible).

Solve the one-off scheduling problem with constraints including comms (greedy, find the best observation that is feasible after we can talk to a given satellite).

Solve the batch scheduling problem with constraints (ILP? For old times' sake).

Multiple instruments. Spacecraft should have an instrument attached. Requests and S/C have an instrument.

Follow-on requests. A detection causes a follow-up request. Simulate.

Write up the three cases of interest:
- Submit a request and you immediately hear back. Unsubmitting requests is free.
    - Use your favorite black-box scheduling algorithm. Submitting a request==evaluating a constraint.
- Submit a request and you immediately hear back. Unsubmitting requests is expensive.
    - Use your favorite non-backtracking scheduling algorithm. Once you choose, no regrets.
- Submit a request and you don't hear back. This is a DMU problem.
    - State:
    - Actions: schedule an observation on a satellite.
    - Transitions: from "unscheduled" to "scheduled" to "executed" or "rejected" for every observation. 
    - Observations: when a file is downloaded, we find out.
    - Rewards: k if we get an observation, 0 otherwise.

- [ ] Constellation: 
  - Input:
      - [X] A new request
      - [X] A schedule of observations assigned to agents
      - [X] (can compute) Alternate windows for the assigned observations
  - Output:
      - A new schedule of observations assigned to agents
      - [X] A bool indicating whether the request was assigned
  - Formulate the optimization problem:
      - Identify which observations can be unscheduled (are not yet committed)
      - Formulate the profit-maximizing problem of assigning everything
      - Solve the problem
      - Check if the new observation is in.
- [ ] Broker
  - Input:
      - A new request
  - Output:
      - Time when the request is scheduled
  - List all windows across all constellations
  - Pick the best one
  - Send the request
- API:
    - [ ] Constellation
        - Input:
            - [X] Submit a request
            - [X] Retrieve a request status
        - Output:
            - [X] Report data acquired
            - [X] Report event
            - [X] Report unscheduled task
    - [ ] Broker
        - Input:
            - Submit a workflow request
            - Status update on observation request
        - Output
            -  Observation requests
            -  Status updates on workflow requests

In [34]:
# Let's have multiple constellations!

# Behind the scenes, this pulls from Celestrak if we do not specify tle_file

satellites_LOFT = [
    # Satellite("LOFT YAM-3", Orbital("YAM-3", tle_file="TLEs.txt")),
    # Satellite("LOFT YAM-5", Orbital("YAM-5", tle_file="TLEs.txt")),
    Satellite("LOFT YAM-6", Orbital("YAM-6", tle_file="TLEs.txt")),
    # Satellite("LOFT YAM-7", Orbital("YAM-7", tle_file="TLEs.txt")),
    # Satellite("LOFT YAM-8", Orbital("YAM-8", tle_file="TLEs.txt")),
    Satellite("LOFT YAM-10", Orbital("YAM-10", tle_file="TLEs.txt")),
    # Satellite("Ubotica CogniSat-6 HAMMER", Orbital("HAMMER", tle_file="TLEs.txt")),
    # "LOFT YAM-3": Orbital("YAM-3"),
]

satellites_ubotica = [
    Satellite("Ubotica CogniSat-6 HAMMER", Orbital("HAMMER", tle_file="TLEs.txt")),
    ]

satellites_aerospace = [
        Satellite("AEROCUBE 18A", Orbital("AEROCUBE 18A", tle_file="TLEs.txt")),
        Satellite("AEROCUBE 18B", Orbital("AEROCUBE 18B", tle_file="TLEs.txt")),   

]

satellites_multischedulers = satellites_LOFT+satellites_ubotica+satellites_aerospace

In [35]:
world_with_schedulers = World(satellites = satellites_multischedulers, phenomena=phenomena_cities)

scheduler_LOFT = ConstellationGroundScheduler(satellites=satellites_LOFT, ground_stations=ground_stations, world=world_with_schedulers, name="LOFT")
scheduler_ubotica = ConstellationGroundScheduler(satellites=satellites_ubotica, ground_stations=ground_stations, world=world_with_schedulers, name="UBOTICA")
scheduler_aerospace = ConstellationGroundScheduler(satellites=satellites_aerospace, ground_stations=ground_stations, world=world_with_schedulers, name="AC")

world_with_schedulers.add_constellation(scheduler_LOFT)
world_with_schedulers.add_constellation(scheduler_ubotica)
world_with_schedulers.add_constellation(scheduler_aerospace)

In [36]:
sampled_world_cities_LOFT = cities_of_the_world.sample(n=50,weights='population',axis=0, random_state=0)
sampled_world_cities_ubotica = cities_of_the_world.sample(n=50,weights='population',axis=0, random_state=1)
sampled_world_cities_aerospace = cities_of_the_world.sample(n=50,weights='population',axis=0, random_state=2)

obs_request_LOFT = [
    ObservationRequest(city[1].lng, city[1].lat, min_time=min_time, max_time=max_time, alt_km=0.307, request_name=city[1].city,)
    for city in sampled_world_cities_LOFT.iterrows()
]

obs_request_ubotica = [
    ObservationRequest(city[1].lng, city[1].lat, min_time=min_time, max_time=max_time, alt_km=0.307, request_name=city[1].city,)
    for city in sampled_world_cities_ubotica.iterrows()
]

obs_request_aerospace = [
    ObservationRequest(city[1].lng, city[1].lat, min_time=min_time, max_time=max_time, alt_km=0.307, request_name=city[1].city,)
    for city in sampled_world_cities_aerospace.iterrows()
]

In [37]:
sim_start_time = dt.datetime.now(dt.timezone.utc).replace(tzinfo=None)

for request in obs_request_LOFT:
    scheduler_LOFT.schedule_request(
        request=request,
        current_time=sim_start_time,
        callback_request_scheduled=lambda obs: print("[LOFT] Request {} scheduled for observation {}!".format(request, obs)),
        callback_request_ready=lambda dp: print("[LOFT] Request {} ready with DP {}!".format(request, dp)),
        )
    
for request in obs_request_ubotica:
    scheduler_ubotica.schedule_request(
        request=request,
        current_time=sim_start_time,
        callback_request_scheduled=lambda obs: print("[UBOTICA] Request {} scheduled for observation {}!".format(request, obs)),
        callback_request_ready=lambda dp: print("[UBOTICA] Request {} ready with DP {}!".format(request, dp)),
        )
    
for request in obs_request_aerospace:
    scheduler_aerospace.schedule_request(
        request=request,
        current_time=sim_start_time,
        callback_request_scheduled=lambda obs: print("[AC] Request {} scheduled for observation {}!".format(request, obs)),
        callback_request_ready=lambda dp: print("[AC] Request {} ready with DP {}!".format(request, dp)),
        )

[LOFT] Scheduling request Request Korla | Lon 86.1746°, lat 41.7259°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-18 18:32:45.529681, highest: 2025-12-18 18:36:01.969305, fall: 2025-12-18 18:39:23.567292 with LOFT YAM-10
[LOFT] Request Request Korla | Lon 86.1746°, lat 41.7259°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB scheduled for observation Observation  at 2025-12-18 18:36:01.969305 with RGB. Look angle 75.78471807320632 | 55.15375053352562 az/dec deg, zenith angle 161.01343050939184 deg, range 712.6799490620754 km, duration 0:01:00!
[LOFT] Scheduling request Request Đà Lạt | Lon 108.4383°, lat 11.9417°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-18 07:56:12.688837, highest: 2025-12-18 07:57:43.756604, fall: 2025-12-18 07:59:12.754801 with LOFT YAM-6
[LOFT] Request Request Đà Lạt | Lon 108.4383°, lat 11.9417°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB scheduled for observation Observation  at 2025-12-18 07:57:43.756604 with RGB. Look angle 282.84155111391755 | 19.384476945797708 az/dec deg, zenith angle 59.31139000797458 deg, range 1128.6707037879603 km, duration 0:01:00!
[LOFT] Scheduling request Request Luanzhou | Lon 118.704°, lat 39.741°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-18 16:55:17.932824, highest: 2025-12-18 16:58:44.731166, fall: 2025-12-18 17:02:04.056437 with LOFT YAM-10
[LOFT] Request Request Luanzhou | Lon 118.704°, lat 39.741°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB scheduled for observation Observation  at 2025-12-18 16:58:44.731166 with RGB. Look angle 265.81320945366605 | 63.59268192508186 az/dec deg, zenith angle 159.73587446870462 deg, range 658.7172544278094 km, duration 0:01:00!
[LOFT] Scheduling request Request Karīmnagar | Lon 79.1288°, lat 18.4386°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-17 19:55:15.984256, highest: 2025-12-17 19:58:30.094000, fall: 2025-12-17 20:01:42.769920 with LOFT YAM-10
No timely contact! Maybe we were too greedy
[LOFT] Scheduling request Request Shangzhou | Lon 109.9186°, lat 33.8734°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-18 16:54:33.914869, highest: 2025-12-18 16:57:38.784053, fall: 2025-12-18 17:00:40.629497 with LOFT YAM-10
[LOFT] Request Request Shangzhou | Lon 109.9186°, lat 33.8734°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB scheduled for observation Observation  at 2025-12-18 16:57:38.784053 with RGB. Look angle 72.23112713585955 | 38.226107179669214 az/dec deg, zenith angle 168.60944665240402 deg, range 903.5239712854506 km, duration 0:01:00!
[LOFT] Scheduling request Request Wŏnsan | Lon 127.4461°, lat 39.1475°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-18 16:47:06.795171, highest: 2025-12-18 16:48:53.340371, fall: 2025-12-18 16:50:39.189429 with LOFT YAM-6
[LOFT] Request Request Wŏnsan | Lon 127.4461°, lat 39.1475°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB scheduled for observation Observation  at 2025-12-18 16:48:53.340371 with RGB. Look angle 70.03472958967508 | 21.40698769560121 az/dec deg, zenith angle 156.57366762040155 deg, range 1086.9894253070804 km, duration 0:01:00!
[LOFT] Scheduling request Request Lubumbashi | Lon 27.4794°, lat -11.6647°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-17 23:00:37.497479, highest: 2025-12-17 23:03:51.135991, fall: 2025-12-17 23:07:00.805346 with LOFT YAM-10
[LOFT] Request Request Lubumbashi | Lon 27.4794°, lat -11.6647°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB scheduled for observation Observation  at 2025-12-17 23:03:51.135991 with RGB. Look angle 78.40897756559953 | 44.75787829997254 az/dec deg, zenith angle 142.25221624343683 deg, range 809.8795515143996 km, duration 0:01:00!
[LOFT] Scheduling request Request Port-Margot | Lon -72.4301°, lat 19.7518°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-18 05:34:42.158922, highest: 2025-12-18 05:38:01.741937, fall: 2025-12-18 05:41:28.713194 with LOFT YAM-10
[LOFT] Request Request Port-Margot | Lon -72.4301°, lat 19.7518°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB scheduled for observation Observation  at 2025-12-18 05:38:01.741937 with RGB. Look angle 84.68672644058127 | 70.58337260339655 az/dec deg, zenith angle 167.44483917363124 deg, range 625.2433459297067 km, duration 0:01:00!
[LOFT] Scheduling request Request Libagon | Lon 125.05°, lat 10.3°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-18 16:47:22.063727, highest: 2025-12-18 16:50:47.571657, fall: 2025-12-18 16:54:05.198825 with LOFT YAM-10
[LOFT] Request Request Libagon | Lon 125.05°, lat 10.3°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB scheduled for observation Observation  at 2025-12-18 16:50:47.571657 with RGB. Look angle 264.906744165912 | 63.49012011940639 az/dec deg, zenith angle 157.9866509168089 deg, range 654.926434786588 km, duration 0:01:00!
[LOFT] Scheduling request Request Brazzaville | Lon 15.2667°, lat -4.2667°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-18 00:56:02.012341, highest: 2025-12-18 00:58:02.200260, fall: 2025-12-18 01:00:03.287692 with LOFT YAM-6
[LOFT] Request Request Brazzaville | Lon 15.2667°, lat -4.2667°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB scheduled for observation Observation  at 2025-12-18 00:58:02.200260 with RGB. Look angle 79.82180594664108 | 24.031963445901578 az/dec deg, zenith angle 139.2796860090578 deg, range 1009.3875605709629 km, duration 0:01:00!
[LOFT] Scheduling request Request Al Ḩajar al Aswad | Lon 36.3042°, lat 33.4576°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-17 23:30:58.942173, highest: 2025-12-17 23:33:49.980189, fall: 2025-12-17 23:36:32.063330 with LOFT YAM-6
[LOFT] Request Request Al Ḩajar al Aswad | Lon 36.3042°, lat 33.4576°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB scheduled for observation Observation  at 2025-12-17 23:33:49.980189 with RGB. Look angle 67.58563301916995 | 63.91416464065135 az/dec deg, zenith angle 151.35916416615322 deg, range 520.8296515285058 km, duration 0:01:00!
[LOFT] Scheduling request Request Ashmūn | Lon 30.9764°, lat 30.2974°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-17 23:11:35.528334, highest: 2025-12-17 23:14:36.068501, fall: 2025-12-17 23:17:34.573762 with LOFT YAM-10
[LOFT] Request Request Ashmūn | Lon 30.9764°, lat 30.2974°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB scheduled for observation Observation  at 2025-12-17 23:14:36.068501 with RGB. Look angle 262.41460689934524 | 35.27464533625163 az/dec deg, zenith angle 160.4741390515813 deg, range 953.3154701896577 km, duration 0:01:00!
[LOFT] Scheduling request Request Guankou | Lon 103.647°, lat 30.988°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-18 18:29:54.131381, highest: 2025-12-18 18:32:33.162044, fall: 2025-12-18 18:35:11.310165 with LOFT YAM-10
[LOFT] Request Request Guankou | Lon 103.647°, lat 30.988°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB scheduled for observation Observation  at 2025-12-18 18:32:33.162044 with RGB. Look angle 263.1112351185475 | 27.297092939297162 az/dec deg, zenith angle 158.59083837011548 deg, range 1135.5899135698778 km, duration 0:01:00!
[LOFT] Scheduling request Request Westhoughton | Lon -2.529°, lat 53.549°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-18 01:11:07.895013, highest: 2025-12-18 01:13:27.274485, fall: 2025-12-18 01:15:46.607209 with LOFT YAM-6
[LOFT] Request Request Westhoughton | Lon -2.529°, lat 53.549°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB scheduled for observation Observation  at 2025-12-18 01:13:27.274485 with RGB. Look angle 66.1973145196422 | 30.257227460660925 az/dec deg, zenith angle 147.3069215127825 deg, range 859.9372237460127 km, duration 0:01:00!
[LOFT] Scheduling request Request New York | Lon -73.9249°, lat 40.6943°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-18 07:22:23.898807, highest: 2025-12-18 07:24:54.828080, fall: 2025-12-18 07:27:25.195945 with LOFT YAM-6
[LOFT] Request Request New York | Lon -73.9249°, lat 40.6943°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB scheduled for observation Observation  at 2025-12-18 07:24:54.828080 with RGB. Look angle 262.0924094910313 | 36.20526711070479 az/dec deg, zenith angle 143.72108676684516 deg, range 753.2146982590613 km, duration 0:01:00!
[LOFT] Scheduling request Request Buenos Aires | Lon -58.3814°, lat -34.6036°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-18 07:02:25.893216, highest: 2025-12-18 07:05:02.360095, fall: 2025-12-18 07:07:40.674746 with LOFT YAM-6
[LOFT] Request Request Buenos Aires | Lon -58.3814°, lat -34.6036°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB scheduled for observation Observation  at 2025-12-18 07:05:02.360095 with RGB. Look angle 252.9806632577697 | 40.07383276646976 az/dec deg, zenith angle 105.83740059737802 deg, range 717.3814842697866 km, duration 0:01:00!
[LOFT] Scheduling request Request Guangzhou | Lon 113.26°, lat 23.13°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-18 18:15:49.799527, highest: 2025-12-18 18:18:13.601866, fall: 2025-12-18 18:20:42.141469 with LOFT YAM-6
[LOFT] Request Request Guangzhou | Lon 113.26°, lat 23.13°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB scheduled for observation Observation  at 2025-12-18 18:18:13.601866 with RGB. Look angle 77.67671716217795 | 34.01362577139824 az/dec deg, zenith angle 153.7655707155119 deg, range 785.938238910255 km, duration 0:01:00!
[LOFT] Scheduling request Request Požarevac | Lon 21.1897°, lat 44.62°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-17 23:36:04.326897, highest: 2025-12-17 23:37:24.129230, fall: 2025-12-17 23:38:44.974298 with LOFT YAM-6
[LOFT] Request Request Požarevac | Lon 21.1897°, lat 44.62°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB scheduled for observation Observation  at 2025-12-17 23:37:24.129230 with RGB. Look angle 66.94652264742386 | 18.183225364819357 az/dec deg, zenith angle 154.8833001731398 deg, range 1206.298322985142 km, duration 0:01:00!
[LOFT] Scheduling request Request El Pueblito | Lon -100.4414°, lat 20.5397°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-18 08:51:01.129927, highest: 2025-12-18 08:53:53.106884, fall: 2025-12-18 08:56:37.342650 with LOFT YAM-6
[LOFT] Request Request El Pueblito | Lon -100.4414°, lat 20.5397°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB scheduled for observation Observation  at 2025-12-18 08:53:53.106884 with RGB. Look angle 65.52283457978929 | 73.84643990089215 az/dec deg, zenith angle 148.53548707468815 deg, range 488.83077362915947 km, duration 0:01:00!
[LOFT] Scheduling request Request South Brunswick | Lon -74.5256°, lat 40.384°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-18 05:40:05.728479, highest: 2025-12-18 05:43:35.074519, fall: 2025-12-18 05:46:57.428729 with LOFT YAM-10
[LOFT] Request Request South Brunswick | Lon -74.5256°, lat 40.384°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB scheduled for observation Observation  at 2025-12-18 05:43:35.074519 with RGB. Look angle 273.5000612933977 | 78.51166874689704 az/dec deg, zenith angle 160.135279268712 deg, range 607.4746476582773 km, duration 0:01:00!
[LOFT] Scheduling request Request Sedgley | Lon -2.123°, lat 52.54°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-18 02:44:06.620451, highest: 2025-12-18 02:46:11.087367, fall: 2025-12-18 02:48:18.867219 with LOFT YAM-6
[LOFT] Request Request Sedgley | Lon -2.123°, lat 52.54°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB scheduled for observation Observation  at 2025-12-18 02:46:11.087367 with RGB. Look angle 264.3650618026098 | 25.190698543903352 az/dec deg, zenith angle 137.80911033433742 deg, range 977.2400809989234 km, duration 0:01:00!
[LOFT] Scheduling request Request Kingsport | Lon -82.5454°, lat 36.5224°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-17 20:51:42.267526, highest: 2025-12-17 20:53:54.165330, fall: 2025-12-17 20:56:04.554029 with LOFT YAM-6
[LOFT] Request Request Kingsport | Lon -82.5454°, lat 36.5224°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB scheduled for observation Observation  at 2025-12-17 20:53:54.165330 with RGB. Look angle 287.2281285352365 | 28.031216946412677 az/dec deg, zenith angle 77.30715976820888 deg, range 886.2398631941658 km, duration 0:01:00!
[LOFT] Scheduling request Request Vijayavāda | Lon 80.6305°, lat 16.5193°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-17 19:54:48.732766, highest: 2025-12-17 19:57:55.208043, fall: 2025-12-17 20:01:01.574005 with LOFT YAM-10
No timely contact! Maybe we were too greedy
[LOFT] Scheduling request Request Balāngīr | Lon 83.48°, lat 20.72°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-17 20:20:10.152980, highest: 2025-12-17 20:22:45.857667, fall: 2025-12-17 20:25:16.100628 with LOFT YAM-6
[LOFT] Request Request Balāngīr | Lon 83.48°, lat 20.72°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB scheduled for observation Observation  at 2025-12-17 20:22:45.857667 with RGB. Look angle 74.59459104370838 | 39.012681070016505 az/dec deg, zenith angle 152.0530346443318 deg, range 712.7439875808273 km, duration 0:01:00!
[LOFT] Scheduling request Request Xi’an | Lon 108.9422°, lat 34.2611°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-18 07:49:33.116218, highest: 2025-12-18 07:52:04.852553, fall: 2025-12-18 07:54:41.357215 with LOFT YAM-6
[LOFT] Request Request Xi’an | Lon 108.9422°, lat 34.2611°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB scheduled for observation Observation  at 2025-12-18 07:52:04.852553 with RGB. Look angle 287.65711215079335 | 43.52005444625827 az/dec deg, zenith angle 73.38194176374296 deg, range 645.5876827784346 km, duration 0:01:00!
[LOFT] Scheduling request Request Zanjān | Lon 48.4953°, lat 36.6864°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-17 21:36:37.844947, highest: 2025-12-17 21:39:59.264828, fall: 2025-12-17 21:43:25.249472 with LOFT YAM-10
[LOFT] Request Request Zanjān | Lon 48.4953°, lat 36.6864°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB scheduled for observation Observation  at 2025-12-17 21:39:59.264828 with RGB. Look angle 256.21990535685234 | 66.99387834517343 az/dec deg, zenith angle 161.8209940000454 deg, range 641.9869849964061 km, duration 0:01:00!
[LOFT] Scheduling request Request Wuhan | Lon 114.3046°, lat 30.5934°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-18 18:17:21.114764, highest: 2025-12-18 18:20:01.614485, fall: 2025-12-18 18:22:47.758476 with LOFT YAM-6
[LOFT] Request Request Wuhan | Lon 114.3046°, lat 30.5934°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB scheduled for observation Observation  at 2025-12-18 18:20:01.614485 with RGB. Look angle 79.99817206637381 | 54.290141577861235 az/dec deg, zenith angle 152.32911854204642 deg, range 570.0842199180321 km, duration 0:01:00!
[LOFT] Scheduling request Request Sonāimukh | Lon 92.8903°, lat 24.7333°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-18 18:27:59.379066, highest: 2025-12-18 18:31:17.558265, fall: 2025-12-18 18:34:44.058359 with LOFT YAM-10
[LOFT] Request Request Sonāimukh | Lon 92.8903°, lat 24.7333°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB scheduled for observation Observation  at 2025-12-18 18:31:17.558265 with RGB. Look angle 83.21416153087962 | 65.91920811767048 az/dec deg, zenith angle 169.42087665293295 deg, range 644.5654171889289 km, duration 0:01:00!
[LOFT] Scheduling request Request Hwasu-dong | Lon 126.8314°, lat 37.1997°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-18 15:20:23.955779, highest: 2025-12-18 15:22:27.865259, fall: 2025-12-18 15:24:31.805940 with LOFT YAM-10
[LOFT] Request Request Hwasu-dong | Lon 126.8314°, lat 37.1997°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB scheduled for observation Observation  at 2025-12-18 15:22:27.865259 with RGB. Look angle 68.82997245203093 | 21.097912433267055 az/dec deg, zenith angle 166.11956482652982 deg, range 1341.985089099588 km, duration 0:01:00!
[LOFT] Scheduling request Request Awka | Lon 7.0678°, lat 6.2069°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-18 00:41:23.575536, highest: 2025-12-18 00:44:48.876740, fall: 2025-12-18 00:48:06.712040 with LOFT YAM-10
[LOFT] Request Request Awka | Lon 7.0678°, lat 6.2069°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB scheduled for observation Observation  at 2025-12-18 00:44:48.876740 with RGB. Look angle 264.2931036273393 | 63.66680716808509 az/dec deg, zenith angle 154.81105569068697 deg, range 654.0031913158203 km, duration 0:01:00!
[LOFT] Scheduling request Request Suqian | Lon 118.275°, lat 33.963°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Best request: Pass start: 2025-12-18 06:16:52.197864, highest: 2025-12-18 06:18:52.006641, fall: 2025-12-18 06:20:50.000346 with LOFT YAM-6

In [38]:
# scheduler_LOFT.schedule_downlinks(current_time=sim_start_time, max_time=sim_start_time+dt.timedelta(hours=36))
# scheduler_ubotica.schedule_downlinks(current_time=sim_start_time, max_time=sim_start_time+dt.timedelta(hours=36))
# scheduler_aerospace.schedule_downlinks(current_time=sim_start_time, max_time=sim_start_time+dt.timedelta(hours=36))

In [39]:
world_with_schedulers.events

[Event Uplink, station KSAT Punta Arenas to sat LOFT YAM-6 at 2025-12-17 19:43:33.284779,
 Event Uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-17 19:43:35.672242,
 Event Uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-17 19:43:35.672242,
 Event Uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-17 19:43:35.672242,
 Event Uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-17 19:43:35.672242,
 Event Uplink, station KSAT Singapore to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 19:50:12.223878,
 Event Uplink, station KSAT Singapore to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 19:50:12.223878,
 Event Uplink, station KSAT Singapore to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 19:50:12.223878,
 Event Uplink, station KSAT Singapore to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 19:50:12.223878,
 Event Uplink, station KSAT Singapore to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 19:50:12.223878,
 Event Uplink, station KSAT Nuuk to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 20:18:15.798808,
 Event Uplink, station KSAT Panama to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 20:33:01.575060,
 Event Uplink, station KSAT Panama to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 20:33:01.575060,
 Event Uplink, station KSAT Panama to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 20:33:01.575060,
 Event Uplink, station KSAT Panama to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 20:33:01.575060,
 Event Uplink, station KSAT Panama to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 20:33:01.575060,
 Event Uplink, station KSAT Nuuk to sat LOFT YAM-6 at 2025-12-17 20:45:23.279075,
 Event Uplink, station KSAT Vardo to sat AEROCUBE 18A at 2025-12-17 20:50:20.511755,
 Event Uplink, station KSAT Vardo to sat AEROCUBE 18A at 2025-12-17 20:50:20.511755,
 Event Uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-17 21:18:08.395048,
 Event Uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-17 21:18:08.395048,
 Event Uplink, station KSAT Mauritius to sat LOFT YAM-10 at 2025-12-17 21:24:56.797471,
 Event Uplink, station KSAT Svalbard to sat LOFT YAM-10 at 2025-12-17 21:51:37.976371,
 Event Uplink, station KSAT Svalbard to sat LOFT YAM-10 at 2025-12-17 21:51:37.976371,
 Event Uplink, station KSAT Svalbard to sat LOFT YAM-10 at 2025-12-17 21:51:37.976371,
 Event Uplink, station KSAT Svalbard to sat LOFT YAM-10 at 2025-12-17 21:51:37.976371,
 Event Uplink, station KSAT Vardo to sat AEROCUBE 18A at 2025-12-17 22:24:16.144589,
 Event Uplink, station KSAT Vardo to sat AEROCUBE 18A at 2025-12-17 22:24:16.144589,
 Event Uplink, station KSAT Vardo to sat AEROCUBE 18A at 2025-12-17 22:24:16.144589,
 Event Uplink, station KSAT Mauritius to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 22:48:24.297365,
 Event Uplink, station KSAT Mauritius to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 22:48:24.297365,
 Event Uplink, station KSAT Mauritius to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 22:48:24.297365,
 Event Uplink, station KSAT Mauritius to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 22:48:24.297365,
 Event Uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-17 22:51:46.616338,
 Event Uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-17 22:51:46.616338,
 Event Uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-17 22:51:46.616338,
 Event Uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-17 22:51:46.616338,
 Event Uplink, station KSAT Mauritius to sat LOFT YAM-6 at 2025-12-17 23:19:10.839353,
 Event Uplink, station KSAT Mauritius to sat LOFT YAM-6 at 2025-12-17 23:19:10.839353,
 Event Uplink, station KSAT Svalbard to sat LOFT YAM-6 at 2025-12-17 23:45:27.122649,
 Event Uplink, station KSAT Troll to sat LOFT YAM-10 at 2025-12-18 00:24:00.070497,
 Event Uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-18 00:24:53.404986,
 Event Uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-18 00:24:53.404986,
 Event Uplink, station KSAT Nemea to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 00:35:09.574550,
 Event Uplink, station KSAT Nemea to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 00:35:09.574550,
 Event Uplink, station KSAT Svalbard to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 00:45:10.745029,
 Event Uplink, station KSAT Svalbard to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 00:45:10.745029,
 Event Uplink, station KSAT Svalbard to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 00:45:10.745029,
 Event Uplink, station KSAT Svalbard to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 00:45:10.745029,
 Event Uplink, station KSAT Nemea to sat LOFT YAM-6 at 2025-12-18 01:08:23.977744,
 Event Uplink, station KSAT Nemea to sat LOFT YAM-6 at 2025-12-18 01:08:23.977744,
 Event Uplink, station KSAT Punta Arenas to sat AEROCUBE 18A at 2025-12-18 02:07:12.518686,
 Event Uplink, station KSAT Troll to sat LOFT YAM-6 at 2025-12-18 02:13:59.294897,
 Event Uplink, station KSAT Singapore to sat AEROCUBE 18B at 2025-12-18 03:08:46.571953,
 Event Uplink, station KSAT Troll to sat LOFT YAM-10 at 2025-12-18 03:35:42.698920,
 Event Uplink, station KSAT Nuuk to sat AEROCUBE 18B at 2025-12-18 03:37:51.212898,
 Event Uplink, station KSAT Nuuk to sat AEROCUBE 18B at 2025-12-18 03:37:51.212898,
 Event Uplink, station KSAT Nuuk to sat AEROCUBE 18B at 2025-12-18 03:37:51.212898,
 Event Uplink, station KSAT Nuuk to sat AEROCUBE 18B at 2025-12-18 03:37:51.212898,
 Event Uplink, station KSAT Nuuk to sat AEROCUBE 18B at 2025-12-18 03:37:51.212898,
 Event Uplink, station KSAT Nuuk to sat LOFT YAM-10 at 2025-12-18 04:13:18.361367,
 Event Uplink, station KSAT Troll to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 04:41:25.714245,
 Event Uplink, station KSAT Nuuk to sat AEROCUBE 18A at 2025-12-18 04:43:28.812727,
 Event Uplink, station KSAT Svalbard to sat AEROCUBE 18B at 2025-12-18 05:05:11.172578,
 Event Uplink, station KSAT Panama to sat LOFT YAM-10 at 2025-12-18 05:35:43.487554,
 Event Uplink, station KSAT Panama to sat LOFT YAM-10 at 2025-12-18 05:35:43.487554,
 Event Uplink, station KSAT Panama to sat LOFT YAM-10 at 2025-12-18 05:35:43.487554,
 Event Uplink, station KSAT Troll to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 06:12:08.570493,
 Event Uplink, station KSAT Troll to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 06:12:08.570493,
 Event Uplink, station KSAT Troll to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 06:12:08.570493,
 Event Uplink, station KSAT Troll to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 06:12:08.570493,
 Event Uplink, station KSAT Troll to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 06:12:08.570493,
 Event Uplink, station KSAT Hokkaido to sat LOFT YAM-6 at 2025-12-18 06:15:16.089871,
 Event Uplink, station KSAT Hokkaido to sat LOFT YAM-6 at 2025-12-18 06:15:16.089871,
 Event Uplink, station KSAT Svalbard to sat AEROCUBE 18B at 2025-12-18 06:38:54.929979,
 Event Uplink, station KSAT Punta Arenas to sat LOFT YAM-6 at 2025-12-18 07:00:49.533891,
 Event Uplink, station KSAT Panama to sat LOFT YAM-10 at 2025-12-18 07:10:56.934042,
 Event Uplink, station KSAT Panama to sat LOFT YAM-10 at 2025-12-18 07:10:56.934042,
 Event Uplink, station KSAT Panama to sat LOFT YAM-6 at 2025-12-18 07:17:09.313580,
 Event Uplink, station KSAT Panama to sat LOFT YAM-6 at 2025-12-18 07:17:09.313580,
 Event Uplink, station KSAT Panama to sat LOFT YAM-6 at 2025-12-18 07:17:09.313580,
 Event Uplink, station KSAT Panama to sat LOFT YAM-6 at 2025-12-18 07:17:09.313580,
 Event Uplink, station KSAT Punta Arenas to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 07:50:40.627887,
 Event Uplink, station KSAT Punta Arenas to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 07:50:40.627887,
 Event Uplink, station KSAT Panama to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 08:06:20.153089,
 Event Uplink, station KSAT Panama to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 08:06:20.153089,
 Event Uplink, station KSAT Panama to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 08:06:20.153089,
 Event Uplink, station KSAT Panama to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 08:06:20.153089,
 Event Uplink, station KSAT Punta Arenas to sat LOFT YAM-6 at 2025-12-18 08:33:52.700544,
 Event Uplink, station KSAT Troll to sat LOFT YAM-6 at 2025-12-18 09:56:48.005099,
 Event Uplink, station KSAT Troll to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 10:42:25.000837,
 Event Uplink, station KSAT Troll to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 10:42:25.000837,
 Event Uplink, station KSAT Vardo to sat LOFT YAM-6 at 2025-12-18 12:24:54.614510,
 Event Uplink, station KSAT Vardo to sat LOFT YAM-6 at 2025-12-18 12:24:54.614510,
 Event Uplink, station KSAT Nuuk to sat AEROCUBE 18B at 2025-12-18 12:53:17.869522,
 Event Uplink, station KSAT Nuuk to sat AEROCUBE 18A at 2025-12-18 13:59:42.565382,
 Event Uplink, station KSAT Nuuk to sat AEROCUBE 18A at 2025-12-18 13:59:42.565382,
 Event Uplink, station KSAT Nuuk to sat AEROCUBE 18A at 2025-12-18 13:59:42.565382,
 Event Uplink, station KSAT Nuuk to sat AEROCUBE 18A at 2025-12-18 13:59:42.565382,
 Event Uplink, station KSAT Vardo to sat LOFT YAM-10 at 2025-12-18 14:02:55.626752,
 Event Uplink, station KSAT Vardo to sat LOFT YAM-10 at 2025-12-18 14:02:55.626752,
 Event Uplink, station KSAT Vardo to sat LOFT YAM-10 at 2025-12-18 14:02:55.626752,
 Event Uplink, station KSAT Nuuk to sat AEROCUBE 18B at 2025-12-18 14:27:41.316494,
 Event Uplink, station KSAT Nuuk to sat AEROCUBE 18B at 2025-12-18 14:27:41.316494,
 Event Uplink, station KSAT Nuuk to sat AEROCUBE 18B at 2025-12-18 14:27:41.316494,
 Event Uplink, station KSAT Nuuk to sat AEROCUBE 18B at 2025-12-18 14:27:41.316494,
 Event Uplink, station KSAT Nuuk to sat AEROCUBE 18B at 2025-12-18 14:27:41.316494,
 Event Uplink, station KSAT Nuuk to sat AEROCUBE 18B at 2025-12-18 14:27:41.316494,
 Event Uplink, station KSAT Vardo to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 14:38:31.382996,
 Event Uplink, station KSAT Panama to sat AEROCUBE 18A at 2025-12-18 15:20:16.946387,
 Event Uplink, station KSAT Panama to sat AEROCUBE 18A at 2025-12-18 15:20:16.946387,
 Event Uplink, station KSAT Panama to sat AEROCUBE 18A at 2025-12-18 15:20:16.946387,
 Event Uplink, station KSAT Panama to sat AEROCUBE 18A at 2025-12-18 15:20:16.946387,
 Event Uplink, station KSAT Vardo to sat LOFT YAM-6 at 2025-12-18 15:31:00.697285,
 Event Uplink, station KSAT Vardo to sat LOFT YAM-6 at 2025-12-18 15:31:00.697285,
 Event Uplink, station KSAT Panama to sat AEROCUBE 18B at 2025-12-18 15:47:59.563714,
 Event Uplink, station KSAT Vardo to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 16:09:10.203239,
 Event Uplink, station KSAT Vardo to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 16:09:10.203239,
 Event Uplink, station KSAT Vardo to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 16:09:10.203239,
 Event Uplink, station KSAT Punta Arenas to sat LOFT YAM-10 at 2025-12-18 16:14:55.093450,
 Event Uplink, station KSAT Punta Arenas to sat AEROCUBE 18A at 2025-12-18 16:37:37.213532,
 Event Uplink, station KSAT Punta Arenas to sat AEROCUBE 18A at 2025-12-18 16:37:37.213532,
 Event Uplink, station KSAT Okinawa to sat LOFT YAM-10 at 2025-12-18 16:54:50.413831,
 Event Uplink, station KSAT Okinawa to sat LOFT YAM-10 at 2025-12-18 16:54:50.413831,
 Event Uplink, station KSAT Punta Arenas to sat AEROCUBE 18B at 2025-12-18 17:05:07.064558,
 Event Uplink, station KSAT Punta Arenas to sat AEROCUBE 18B at 2025-12-18 17:05:07.064558,
 Event Uplink, station KSAT Punta Arenas to sat AEROCUBE 18B at 2025-12-18 17:05:07.064558,
 Event Uplink, station KSAT Punta Arenas to sat LOFT YAM-6 at 2025-12-18 17:39:27.335845,
 Event Uplink, station KSAT Punta Arenas to sat LOFT YAM-6 at 2025-12-18 17:39:27.335845,
 Event Uplink, station KSAT Punta Arenas to sat LOFT YAM-6 at 2025-12-18 17:39:27.335845,
 Event Uplink, station KSAT Punta Arenas to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 18:14:50.070425,
 Event Uplink, station KSAT Punta Arenas to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 18:14:50.070425,
 Event Uplink, station KSAT Punta Arenas to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 18:14:50.070425,
 Event Uplink, station KSAT Singapore to sat LOFT YAM-10 at 2025-12-18 18:24:43.423802,
 Event Uplink, station KSAT Singapore to sat LOFT YAM-10 at 2025-12-18 18:24:43.423802,
 Event Uplink, station KSAT Singapore to sat LOFT YAM-10 at 2025-12-18 18:24:43.423802,
 Event Uplink, station KSAT Troll to sat AEROCUBE 18B at 2025-12-18 18:28:44.008604,
 Event Uplink, station KSAT Troll to sat AEROCUBE 18B at 2025-12-18 18:28:44.008604,
 Event Uplink, station KSAT Nuuk to sat LOFT YAM-6 at 2025-12-18 18:42:03.864938,
 Event Uplink, station KSAT Nuuk to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 19:16:05.862783,
 Event Downlink, station KSAT Troll from sat AEROCUBE 18B at 2025-12-19 19:39:39.774691,
 Event Downlink, station KSAT Troll from sat AEROCUBE 18B at 2025-12-19 19:39:39.774691,
 Event Downlink, station KSAT Troll from sat AEROCUBE 18B at 2025-12-19 19:39:39.774691,
 Event Downlink, station KSAT Troll from sat AEROCUBE 18B at 2025-12-19 19:39:39.774691,
 Event Downlink, station KSAT Nuuk from sat Ubotica CogniSat-6 HAMMER at 2025-12-19 19:41:40.295339,
 Event Downlink, station KSAT Nuuk from sat Ubotica CogniSat-6 HAMMER at 2025-12-19 19:41:40.295339,
 Event Downlink, station KSAT Nuuk from sat Ubotica CogniSat-6 HAMMER at 2025-12-19 19:41:40.295339,
 Event Downlink, station KSAT Nuuk from sat Ubotica CogniSat-6 HAMMER at 2025-12-19 19:41:40.295339,
 Event Downlink, station KSAT Panama from sat LOFT YAM-6 at 2025-12-19 19:56:15.179336,
 Event Downlink, station KSAT Panama from sat LOFT YAM-6 at 2025-12-19 19:56:15.179336,
 Event Downlink, station KSAT Panama from sat Ubotica CogniSat-6 HAMMER at 2025-12-19 19:56:31.011770,
 Event Downlink, station KSAT Panama from sat Ubotica CogniSat-6 HAMMER at 2025-12-19 19:56:31.011770,
 Event Downlink, station KSAT Svalbard from sat LOFT YAM-10 at 2025-12-19 20:27:09.467629,
 Event Downlink, station KSAT Troll from sat AEROCUBE 18A at 2025-12-19 20:45:18.664140,
 Event Downlink, station KSAT Troll from sat AEROCUBE 18A at 2025-12-19 20:45:18.664140,
 Event Downlink, station KSAT Svalbard from sat Ubotica CogniSat-6 HAMMER at 2025-12-19 21:06:25.645028,
 Event Downlink, station KSAT Svalbard from sat Ubotica CogniSat-6 HAMMER at 2025-12-19 21:06:25.645028,
 Event Downlink, station KSAT Svalbard from sat Ubotica CogniSat-6 HAMMER at 2025-12-19 21:06:25.645028,
 Event Downlink, station KSAT Svalbard from sat Ubotica CogniSat-6 HAMMER at 2025-12-19 21:06:25.645028,
 Event Downlink, station KSAT Svalbard from sat Ubotica CogniSat-6 HAMMER at 2025-12-19 21:06:25.645028,
 Event Downlink, station KSAT Troll from sat AEROCUBE 18B at 2025-12-19 21:13:21.132827,
 Event Downlink, station KSAT Troll from sat AEROCUBE 18B at 2025-12-19 21:13:21.132827,
 Event Downlink, station KSAT Svalbard from sat LOFT YAM-10 at 2025-12-19 22:02:44.652028,
 Event Downlink, station KSAT Svalbard from sat LOFT YAM-10 at 2025-12-19 22:02:44.652028,
 Event Downlink, station KSAT Svalbard from sat LOFT YAM-10 at 2025-12-19 22:02:44.652028,
 Event Downlink, station KSAT Svalbard from sat LOFT YAM-10 at 2025-12-19 22:02:44.652028,
 Event Downlink, station KSAT Troll from sat AEROCUBE 18A at 2025-12-19 22:20:17.091490,
 Event Downlink, station KSAT Troll from sat AEROCUBE 18A at 2025-12-19 22:20:17.091490,
 Event Downlink, station KSAT Troll from sat AEROCUBE 18A at 2025-12-19 22:20:17.091490,
 Event Downlink, station KSAT Svalbard from sat Ubotica CogniSat-6 HAMMER at 2025-12-19 22:36:58.959717,
 Event Downlink, station KSAT Svalbard from sat Ubotica CogniSat-6 HAMMER at 2025-12-19 22:36:58.959717,
 Event Downlink, station KSAT Svalbard from sat Ubotica CogniSat-6 HAMMER at 2025-12-19 22:36:58.959717,
 Event Downlink, station KSAT Svalbard from sat Ubotica CogniSat-6 HAMMER at 2025-12-19 22:36:58.959717,
 Event Downlink, station KSAT Svalbard from sat LOFT YAM-6 at 2025-12-19 22:40:40.063771,
 Event Downlink, station KSAT Svalbard from sat LOFT YAM-6 at 2025-12-19 22:40:40.063771,
 Event Downlink, station KSAT Troll from sat AEROCUBE 18B at 2025-12-19 22:49:07.879488,
 Event Downlink, station KSAT Troll from sat AEROCUBE 18B at 2025-12-19 22:49:07.879488,
 Event Downlink, station KSAT Troll from sat AEROCUBE 18B at 2025-12-19 22:49:07.879488,
 Event Downlink, station KSAT Troll from sat AEROCUBE 18B at 2025-12-19 22:49:07.879488,
 Event Downlink, station KSAT Svalbard from sat Ubotica CogniSat-6 HAMMER at 2025-12-20 00:08:03.350385,
 Event Downlink, station KSAT Svalbard from sat Ubotica CogniSat-6 HAMMER at 2025-12-20 00:08:03.350385,
 Event Downlink, station KSAT Svalbard from sat LOFT YAM-6 at 2025-12-20 00:14:06.896826,
 Event Downlink, station KSAT Svalbard from sat LOFT YAM-6 at 2025-12-20 00:14:06.896826,
 Event Downlink, station KSAT Svalbard from sat LOFT YAM-6 at 2025-12-20 00:14:06.896826,
 Event Downlink, station KSAT Troll from sat LOFT YAM-10 at 2025-12-20 00:35:55.044821,
 Event Downlink, station KSAT Nuuk from sat AEROCUBE 18B at 2025-12-20 01:22:53.359544,
 Event Downlink, station KSAT Nuuk from sat AEROCUBE 18B at 2025-12-20 01:22:53.359544,
 Event Downlink, station KSAT Svalbard from sat Ubotica CogniSat-6 HAMMER at 2025-12-20 01:40:12.534339,
 Event Downlink, station KSAT Svalbard from sat Ubotica CogniSat-6 HAMMER at 2025-12-20 01:40:12.534339,
 Event Downlink, station KSAT Svalbard from sat Ubotica CogniSat-6 HAMMER at 2025-12-20 01:40:12.534339,
 Event Downlink, station KSAT Svalbard from sat Ubotica CogniSat-6 HAMMER at 2025-12-20 01:40:12.534339,
 Event Downlink, station KSAT Svalbard from sat LOFT YAM-6 at 2025-12-20 01:48:43.866995,
 Event Downlink, station KSAT Nuuk from sat AEROCUBE 18A at 2025-12-20 02:27:55.492160,
 Event Downlink, station KSAT Nuuk from sat AEROCUBE 18B at 2025-12-20 02:55:51.444017,
 Event Downlink, station KSAT Punta Arenas from sat AEROCUBE 18B at 2025-12-20 03:27:50.028152,
 Event Downlink, station KSAT Punta Arenas from sat AEROCUBE 18B at 2025-12-20 03:27:50.028152,
 Event Downlink, station KSAT Punta Arenas from sat AEROCUBE 18B at 2025-12-20 03:27:50.028152,
 Event Downlink, station KSAT Troll from sat LOFT YAM-10 at 2025-12-20 03:46:50.123882,
 Event Downlink, station KSAT Panama from sat AEROCUBE 18A at 2025-12-20 04:17:32.845838,
 Event Downlink, station KSAT Nuuk from sat LOFT YAM-10 at 2025-12-20 04:24:47.916189,
 Event Downlink, station KSAT Nuuk from sat AEROCUBE 18B at 2025-12-20 04:30:27.546937,
 Event Downlink, station KSAT Nuuk from sat AEROCUBE 18B at 2025-12-20 04:30:27.546937,
 Event Downlink, station KSAT Nuuk from sat AEROCUBE 18B at 2025-12-20 04:30:27.546937,
 Event Downlink, station KSAT Nuuk from sat Ubotica CogniSat-6 HAMMER at 2025-12-20 04:40:07.101968,
 Event Downlink, station KSAT Punta Arenas from sat LOFT YAM-10 at 2025-12-20 05:30:38.299599,
 Event Downlink, station KSAT Punta Arenas from sat LOFT YAM-10 at 2025-12-20 05:30:38.299599,
 Event Downlink, station KSAT Panama from sat LOFT YAM-10 at 2025-12-20 05:47:16.966058,
 Event Downlink, station KSAT Troll from sat LOFT YAM-6 at 2025-12-20 05:48:52.594971,
 Event Downlink, station KSAT Troll from sat LOFT YAM-6 at 2025-12-20 05:48:52.594971,
 Event Downlink, station KSAT Nuuk from sat Ubotica CogniSat-6 HAMMER at 2025-12-20 06:11:35.250544,
 Event Downlink, station KSAT Singapore from sat LOFT YAM-6 at 2025-12-20 06:57:11.712566,
 Event Downlink, station KSAT Punta Arenas from sat LOFT YAM-10 at 2025-12-20 07:05:42.947182,
 Event Downlink, station KSAT Punta Arenas from sat LOFT YAM-10 at 2025-12-20 07:05:42.947182,
 Event Downlink, station KSAT Troll from sat Ubotica CogniSat-6 HAMMER at 2025-12-20 07:06:51.620758,
 Event Downlink, station KSAT Troll from sat Ubotica CogniSat-6 HAMMER at 2025-12-20 07:06:51.620758,
 Event Downlink, station KSAT Troll from sat Ubotica CogniSat-6 HAMMER at 2025-12-20 07:06:51.620758,
 Event Downlink, station KSAT Troll from sat Ubotica CogniSat-6 HAMMER at 2025-12-20 07:06:51.620758,
 Event Downlink, station KSAT Troll from sat LOFT YAM-6 at 2025-12-20 07:22:02.421901,

In [40]:
retcode = 1
while (retcode !=0):
    retcode = world_with_schedulers.tick()
    # retcode = world_with_schedulers.tick(print_forbidden_prefixes=["Downlink", "End of downlink", "Unlock uplink", "Unlock satellite after obs"])

Executing Event Uplink, station KSAT Punta Arenas to sat LOFT YAM-6 at 2025-12-17 19:43:33.284779
Executing Event Uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-17 19:43:35.672242
Executing Event Uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-17 19:43:35.672242
Executing Event Uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-17 19:43:35.672242
Executing Event Uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-17 19:43:35.672242
Executing Event Unlock uplink, station KSAT Punta Arenas to sat LOFT YAM-6 at 2025-12-17 19:44:11.283001
Executing Event Unlock uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-17 19:45:10.483266
Executing Event Unlock uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-17 19:45:10.483266
Executing Event Unlock uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-17 19:45:10.483266
Executing Event Unlock uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-17 19:45:10.483266
Executing Event Uplink, station KSAT Singapore to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 19:50:12.223878
Executing Event Uplink, station KSAT Singapore to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 19:50:12.223878
Executing Event Uplink, station KSAT Singapore to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 19:50:12.223878
Executing Event Uplink, station KSAT Singapore to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 19:50:12.223878
Executing Event Uplink, station KSAT Singapore to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 19:50:12.223878
Executing Event Obs, sat AEROCUBE 18B at 2025-12-17 19:52:05.924837
Executing Event Unlock uplink, station KSAT Singapore to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 19:52:21.716540
Executing Event Unlock uplink, station KSAT Singapore to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 19:52:21.716540
Executing Event Unlock uplink, station KSAT Singapore to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 19:52:21.716540
Executing Event Unlock uplink, station KSAT Singapore to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 19:52:21.716540
Executing Event Unlock uplink, station KSAT Singapore to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 19:52:21.716540
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-17 19:52:41.784043
Executing Event Unlock satellite after obs, sat AEROCUBE 18B at 2025-12-17 19:53:05.924837
Executing Event Obs, sat AEROCUBE 18B at 2025-12-17 19:53:07.878218
Executing Event Unlock satellite after obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-17 19:53:41.784043
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-17 19:54:05.232969
Executing Event Unlock satellite after obs, sat AEROCUBE 18B at 2025-12-17 19:54:07.878218
Executing Event Unlock satellite after obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-17 19:55:05.232969
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-17 19:56:32.711106
Executing Event Unlock satellite after obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-17 19:57:32.711106
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-17 19:57:59.877140
Executing Event Unlock satellite after obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-17 19:58:59.877140
Executing Event Obs, sat AEROCUBE 18B at 2025-12-17 19:59:38.284210
Executing Event Unlock satellite after obs, sat AEROCUBE 18B at 2025-12-17 20:00:38.284210
Executing Event Obs, sat AEROCUBE 18B at 2025-12-17 20:02:50.444817
Executing Event Unlock satellite after obs, sat AEROCUBE 18B at 2025-12-17 20:03:50.444817
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-17 20:04:10.866625
Executing Event Unlock satellite after obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-17 20:05:10.866625
Executing Event Uplink, station KSAT Nuuk to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 20:18:15.798808
Executing Event Unlock uplink, station KSAT Nuuk to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 20:20:00.308253
Executing Event Obs, sat LOFT YAM-6 at 2025-12-17 20:22:45.857667
Executing Event Unlock satellite after obs, sat LOFT YAM-6 at 2025-12-17 20:23:45.857667
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-17 20:24:53.435323
Executing Event Unlock satellite after obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-17 20:25:53.435323
Executing Event Uplink, station KSAT Panama to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 20:33:01.575060
Executing Event Uplink, station KSAT Panama to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 20:33:01.575060
Executing Event Uplink, station KSAT Panama to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 20:33:01.575060
Executing Event Uplink, station KSAT Panama to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 20:33:01.575060
Executing Event Uplink, station KSAT Panama to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 20:33:01.575060
Executing Event Unlock uplink, station KSAT Panama to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 20:34:52.896217
Executing Event Unlock uplink, station KSAT Panama to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 20:34:52.896217
Executing Event Unlock uplink, station KSAT Panama to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 20:34:52.896217
Executing Event Unlock uplink, station KSAT Panama to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 20:34:52.896217
Executing Event Unlock uplink, station KSAT Panama to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 20:34:52.896217
Executing Event Uplink, station KSAT Nuuk to sat LOFT YAM-6 at 2025-12-17 20:45:23.279075
Executing Event Unlock uplink, station KSAT Nuuk to sat LOFT YAM-6 at 2025-12-17 20:46:26.700323
Executing Event Uplink, station KSAT Vardo to sat AEROCUBE 18A at 2025-12-17 20:50:20.511755
Executing Event Uplink, station KSAT Vardo to sat AEROCUBE 18A at 2025-12-17 20:50:20.511755
Executing Event Unlock uplink, station KSAT Vardo to sat AEROCUBE 18A at 2025-12-17 20:53:10.718372
Executing Event Unlock uplink, station KSAT Vardo to sat AEROCUBE 18A at 2025-12-17 20:53:10.718372
Executing Event Obs, sat LOFT YAM-6 at 2025-12-17 20:53:54.165330
Executing Event Unlock satellite after obs, sat LOFT YAM-6 at 2025-12-17 20:54:54.165330
Executing Event Obs, sat AEROCUBE 18A at 2025-12-17 20:57:56.720111
Executing Event Unlock satellite after obs, sat AEROCUBE 18A at 2025-12-17 20:58:56.720111
Executing Event Obs, sat AEROCUBE 18A at 2025-12-17 21:00:15.589637
Executing Event Unlock satellite after obs, sat AEROCUBE 18A at 2025-12-17 21:01:15.589637
Executing Event Uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-17 21:18:08.395048
Executing Event Uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-17 21:18:08.395048
Executing Event Unlock uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-17 21:21:02.805122
Executing Event Unlock uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-17 21:21:02.805122
Executing Event Obs, sat AEROCUBE 18B at 2025-12-17 21:22:03.737578
Executing Event Unlock satellite after obs, sat AEROCUBE 18B at 2025-12-17 21:23:03.737578
Executing Event Obs, sat AEROCUBE 18B at 2025-12-17 21:24:49.201304
Executing Event Uplink, station KSAT Mauritius to sat LOFT YAM-10 at 2025-12-17 21:24:56.797471
Executing Event Unlock satellite after obs, sat AEROCUBE 18B at 2025-12-17 21:25:49.201304
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-17 21:26:44.496762
Executing Event Unlock satellite after obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-17 21:27:44.496762
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-17 21:27:44.667451
Executing Event Unlock uplink, station KSAT Mauritius to sat LOFT YAM-10 at 2025-12-17 21:28:16.574767
Executing Event Unlock satellite after obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-17 21:28:44.667451
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-17 21:28:53.774889
Executing Event Unlock satellite after obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-17 21:29:53.774889
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-17 21:30:42.829571
Executing Event Unlock satellite after obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-17 21:31:42.829571
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-17 21:36:03.160573
Executing Event Unlock satellite after obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-17 21:37:03.160573
Executing Event Obs, sat LOFT YAM-10 at 2025-12-17 21:39:59.264828
Executing Event Unlock satellite after obs, sat LOFT YAM-10 at 2025-12-17 21:40:59.264828
Executing Event Uplink, station KSAT Svalbard to sat LOFT YAM-10 at 2025-12-17 21:51:37.976371
Executing Event Uplink, station KSAT Svalbard to sat LOFT YAM-10 at 2025-12-17 21:51:37.976371
Executing Event Uplink, station KSAT Svalbard to sat LOFT YAM-10 at 2025-12-17 21:51:37.976371
Executing Event Uplink, station KSAT Svalbard to sat LOFT YAM-10 at 2025-12-17 21:51:37.976371
Executing Event Unlock uplink, station KSAT Svalbard to sat LOFT YAM-10 at 2025-12-17 21:55:10.103102
Executing Event Unlock uplink, station KSAT Svalbard to sat LOFT YAM-10 at 2025-12-17 21:55:10.103102
Executing Event Unlock uplink, station KSAT Svalbard to sat LOFT YAM-10 at 2025-12-17 21:55:10.103102
Executing Event Unlock uplink, station KSAT Svalbard to sat LOFT YAM-10 at 2025-12-17 21:55:10.103102
Executing Event Uplink, station KSAT Vardo to sat AEROCUBE 18A at 2025-12-17 22:24:16.144589
Executing Event Uplink, station KSAT Vardo to sat AEROCUBE 18A at 2025-12-17 22:24:16.144589
Executing Event Uplink, station KSAT Vardo to sat AEROCUBE 18A at 2025-12-17 22:24:16.144589
Executing Event Unlock uplink, station KSAT Vardo to sat AEROCUBE 18A at 2025-12-17 22:27:11.222613
Executing Event Unlock uplink, station KSAT Vardo to sat AEROCUBE 18A at 2025-12-17 22:27:11.222613
Executing Event Unlock uplink, station KSAT Vardo to sat AEROCUBE 18A at 2025-12-17 22:27:11.222613
Executing Event Obs, sat AEROCUBE 18A at 2025-12-17 22:27:45.356093
Executing Event Unlock satellite after obs, sat AEROCUBE 18A at 2025-12-17 22:28:45.356093
Executing Event Obs, sat AEROCUBE 18A at 2025-12-17 22:30:04.720043
Executing Event Unlock satellite after obs, sat AEROCUBE 18A at 2025-12-17 22:31:04.720043
Executing Event Obs, sat AEROCUBE 18A at 2025-12-17 22:41:56.682333
Executing Event Unlock satellite after obs, sat AEROCUBE 18A at 2025-12-17 22:42:56.682333
Executing Event Uplink, station KSAT Mauritius to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 22:48:24.297365
Executing Event Uplink, station KSAT Mauritius to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 22:48:24.297365
Executing Event Uplink, station KSAT Mauritius to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 22:48:24.297365
Executing Event Uplink, station KSAT Mauritius to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 22:48:24.297365
Executing Event Unlock uplink, station KSAT Mauritius to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 22:50:17.301852
Executing Event Unlock uplink, station KSAT Mauritius to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 22:50:17.301852
Executing Event Unlock uplink, station KSAT Mauritius to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 22:50:17.301852
Executing Event Unlock uplink, station KSAT Mauritius to sat Ubotica CogniSat-6 HAMMER at 2025-12-17 22:50:17.301852
Executing Event Uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-17 22:51:46.616338
Executing Event Uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-17 22:51:46.616338
Executing Event Uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-17 22:51:46.616338
Executing Event Uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-17 22:51:46.616338
Executing Event Unlock uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-17 22:54:30.718134
Executing Event Unlock uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-17 22:54:30.718134
Executing Event Unlock uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-17 22:54:30.718134
Executing Event Unlock uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-17 22:54:30.718134
Executing Event Obs, sat AEROCUBE 18B at 2025-12-17 22:55:43.622553
Executing Event Unlock satellite after obs, sat AEROCUBE 18B at 2025-12-17 22:56:43.622553
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-17 23:00:01.959551
Executing Event Unlock satellite after obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-17 23:01:01.959551
Executing Event Obs, sat AEROCUBE 18B at 2025-12-17 23:01:18.575689
Executing Event Unlock satellite after obs, sat AEROCUBE 18B at 2025-12-17 23:02:18.575689
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-17 23:02:48.150011
Executing Event Unlock satellite after obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-17 23:03:48.150011
Executing Event Obs, sat LOFT YAM-10 at 2025-12-17 23:03:51.135991
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-17 23:04:20.404870
Executing Event Unlock satellite after obs, sat LOFT YAM-10 at 2025-12-17 23:04:51.135991
Executing Event Unlock satellite after obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-17 23:05:20.404870
Executing Event Obs, sat LOFT YAM-10 at 2025-12-17 23:05:27.723430
Executing Event Unlock satellite after obs, sat LOFT YAM-10 at 2025-12-17 23:06:27.723430
Executing Event Obs, sat AEROCUBE 18B at 2025-12-17 23:07:43.393333
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-17 23:07:58.959919
Executing Event Unlock satellite after obs, sat AEROCUBE 18B at 2025-12-17 23:08:43.393333
Executing Event Unlock satellite after obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-17 23:08:58.959919
Executing Event Obs, sat AEROCUBE 18B at 2025-12-17 23:09:03.299707
Executing Event Unlock satellite after obs, sat AEROCUBE 18B at 2025-12-17 23:10:03.299707
Executing Event Obs, sat LOFT YAM-10 at 2025-12-17 23:14:36.068501
Executing Event Unlock satellite after obs, sat LOFT YAM-10 at 2025-12-17 23:15:36.068501
Executing Event Uplink, station KSAT Mauritius to sat LOFT YAM-6 at 2025-12-17 23:19:10.839353
Executing Event Uplink, station KSAT Mauritius to sat LOFT YAM-6 at 2025-12-17 23:19:10.839353
Executing Event Unlock uplink, station KSAT Mauritius to sat LOFT YAM-6 at 2025-12-17 23:21:21.845855
Executing Event Unlock uplink, station KSAT Mauritius to sat LOFT YAM-6 at 2025-12-17 23:21:21.845855
Executing Event Obs, sat LOFT YAM-10 at 2025-12-17 23:22:00.586346
Executing Event Unlock satellite after obs, sat LOFT YAM-10 at 2025-12-17 23:23:00.586346
Executing Event Obs, sat LOFT YAM-6 at 2025-12-17 23:33:49.980189
Executing Event Unlock satellite after obs, sat LOFT YAM-6 at 2025-12-17 23:34:49.980189
Executing Event Obs, sat LOFT YAM-6 at 2025-12-17 23:37:24.129230
Executing Event Unlock satellite after obs, sat LOFT YAM-6 at 2025-12-17 23:38:24.129230
Executing Event Uplink, station KSAT Svalbard to sat LOFT YAM-6 at 2025-12-17 23:45:27.122649
Executing Event Unlock uplink, station KSAT Svalbard to sat LOFT YAM-6 at 2025-12-17 23:48:18.927204
Executing Event Uplink, station KSAT Troll to sat LOFT YAM-10 at 2025-12-18 00:24:00.070497
Executing Event Uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-18 00:24:53.404986
Executing Event Uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-18 00:24:53.404986
Executing Event Unlock uplink, station KSAT Troll to sat LOFT YAM-10 at 2025-12-18 00:26:21.250506
Executing Event Unlock uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-18 00:26:27.412969
Executing Event Unlock uplink, station KSAT Vardo to sat AEROCUBE 18B at 2025-12-18 00:26:27.412969
Executing Event Uplink, station KSAT Nemea to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 00:35:09.574550
Executing Event Uplink, station KSAT Nemea to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 00:35:09.574550
Executing Event Unlock uplink, station KSAT Nemea to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 00:37:06.234421
Executing Event Unlock uplink, station KSAT Nemea to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 00:37:06.234421
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 00:37:36.619171
Executing Event Unlock satellite after obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 00:38:36.619171
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 00:38:37.868183
Executing Event Unlock satellite after obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 00:39:37.868183
Executing Event Obs, sat LOFT YAM-10 at 2025-12-18 00:44:48.876740
Executing Event Uplink, station KSAT Svalbard to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 00:45:10.745029
Executing Event Uplink, station KSAT Svalbard to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 00:45:10.745029
Executing Event Uplink, station KSAT Svalbard to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 00:45:10.745029
Executing Event Uplink, station KSAT Svalbard to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 00:45:10.745029
Executing Event Unlock satellite after obs, sat LOFT YAM-10 at 2025-12-18 00:45:48.876740
Executing Event Unlock uplink, station KSAT Svalbard to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 00:47:11.148030
Executing Event Unlock uplink, station KSAT Svalbard to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 00:47:11.148030
Executing Event Unlock uplink, station KSAT Svalbard to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 00:47:11.148030
Executing Event Unlock uplink, station KSAT Svalbard to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 00:47:11.148030
Executing Event Obs, sat LOFT YAM-6 at 2025-12-18 00:58:02.200260
Executing Event Unlock satellite after obs, sat LOFT YAM-6 at 2025-12-18 00:59:02.200260
Executing Event Uplink, station KSAT Nemea to sat LOFT YAM-6 at 2025-12-18 01:08:23.977744
Executing Event Uplink, station KSAT Nemea to sat LOFT YAM-6 at 2025-12-18 01:08:23.977744
Executing Event Unlock uplink, station KSAT Nemea to sat LOFT YAM-6 at 2025-12-18 01:10:39.830867
Executing Event Unlock uplink, station KSAT Nemea to sat LOFT YAM-6 at 2025-12-18 01:10:39.830867
Executing Event Obs, sat LOFT YAM-6 at 2025-12-18 01:12:01.204149
Executing Event Unlock satellite after obs, sat LOFT YAM-6 at 2025-12-18 01:13:01.204149
Executing Event Obs, sat LOFT YAM-6 at 2025-12-18 01:13:27.274485
Executing Event Unlock satellite after obs, sat LOFT YAM-6 at 2025-12-18 01:14:27.274485
Executing Event Obs, sat AEROCUBE 18B at 2025-12-18 01:40:32.926630
Executing Event Unlock satellite after obs, sat AEROCUBE 18B at 2025-12-18 01:41:32.926630
Executing Event Obs, sat AEROCUBE 18B at 2025-12-18 01:42:59.752623
Executing Event Unlock satellite after obs, sat AEROCUBE 18B at 2025-12-18 01:43:59.752623
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 01:59:03.330725
Executing Event Unlock satellite after obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 02:00:03.330725
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 02:05:52.711052
Executing Event Unlock satellite after obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 02:06:52.711052
Executing Event Uplink, station KSAT Punta Arenas to sat AEROCUBE 18A at 2025-12-18 02:07:12.518686
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 02:08:18.021092
Executing Event Unlock satellite after obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 02:09:18.021092
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 02:09:57.628967
Executing Event Unlock uplink, station KSAT Punta Arenas to sat AEROCUBE 18A at 2025-12-18 02:10:10.087523
Executing Event Unlock satellite after obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 02:10:57.628967
Executing Event Uplink, station KSAT Troll to sat LOFT YAM-6 at 2025-12-18 02:13:59.294897
Executing Event Unlock uplink, station KSAT Troll to sat LOFT YAM-6 at 2025-12-18 02:16:11.886990
Executing Event Obs, sat AEROCUBE 18A at 2025-12-18 02:46:02.627532
Executing Event Obs, sat LOFT YAM-6 at 2025-12-18 02:46:11.087367
Executing Event Unlock satellite after obs, sat AEROCUBE 18A at 2025-12-18 02:47:02.627532
Executing Event Unlock satellite after obs, sat LOFT YAM-6 at 2025-12-18 02:47:11.087367
Executing Event Uplink, station KSAT Singapore to sat AEROCUBE 18B at 2025-12-18 03:08:46.571953

In [41]:
def request_statistics(requests_pd):
    total_requests = len(requests_pd)
    all_statuses = set(requests_pd.status.values)    
    for s in all_statuses:
        # matching_statuses = sum([1 if (r['status']==s) else 0 for r in requests.values()])
        matching_statuses = len(requests_pd[requests_pd.status==s])
        print("{}/{} ({}%) of requests are in status {}".format(matching_statuses,total_requests, matching_statuses/total_requests*100, s))

In [42]:
print("LOFT")
request_statistics(scheduler_LOFT._requests)

print("Ubotica")
request_statistics(scheduler_ubotica._requests)

print("AC")
request_statistics(scheduler_aerospace._requests)

LOFT
47/50 (94.0%) of requests are in status OK! Data received
3/50 (6.0%) of requests are in status No timely contact
Ubotica
43/50 (86.0%) of requests are in status OK! Data received
7/50 (14.000000000000002%) of requests are in status All observation opportunities are conflicting
AC
50/50 (100.0%) of requests are in status OK! Data received

In [ ]:
class Broker():
    def __init__(self, constellations: list[ConstellationGroundScheduler], world: World, name="Broker"):
        self.name = name
        self.constellations = constellations
        # self.known_satellites = known_satellites
        self.world = world
        self._requests = pd.DataFrame(columns=['request', 'requested_pass', 'requested_constellation', 'requested_satellite', 'constellation', 'satellite', 'assigned_pass', 'assigned_downlink', 'status', 'data_product', 'scheduled_callback', 'unscheduled_callback', 'ready_callback'])

        # self.requests = {}

    # Broadly, look at the ephemerides, find the best option, find the corresponding constellation, give them a window around that.
    def schedule_request(
            self,
            request: ObservationRequest,
            current_time: dt.datetime=dt.datetime.now(dt.timezone.utc).replace(tzinfo=None),
            number_of_submissions: int=1,
            ):
        # Pick the best satellite to fulfill this. This is where we'll need to be smarter. Or not! Just pick something starting the day after.
        print("[{}] scheduling request {}".format(self.name, request))
        # self.requests[request] = {


        _known_satellites = []
        _known_satellites_by_constellation = {}
        for constellation in self.constellations:
            _known_satellites += constellation.satellites
            for _sat in constellation.satellites:
                _known_satellites_by_constellation[_sat] = constellation

        _opportunities = find_observation_opportunities(
            [request,],
            satellites=_known_satellites,
            passes_error_s=60,
            passes_horizon_deg=MIN_HORIZON_ANGLE_FOR_OBS_DEG
        )
        # self.requests[request]['opportunities'] = _opportunities
        # self._requests.loc[self._requests['request']==request, 'opportunities'] = _opportunities

        passes = _opportunities[request]

        if len(passes):
            
            # TODO sort passes with key observation_quality(passes[s][p_index].highest)
            sorted_passes = [(satellite, satpass) for satellite, satpasses in passes.items() for satpass in satpasses]
            # Sort by quality
            sorted_passes.sort(key=lambda x: observation_quality(x[1].highest), reverse=True)
            # print("Sorted passes: ", sorted_passes)
            
            _best_satellite = sorted_passes[0][0]
            _best_pass = sorted_passes[0][1]
            _best_quality = observation_quality(_best_pass.highest)

            # for satellite, satpasses in passes.items():
            #     for satpass in satpasses:
            #         _quality = observation_quality(satpass.highest)
            #         if _quality > _best_quality:
            #             assert False, "How did I find a better pass?"
            #             _best_quality = _quality
            #             _best_satellite = satellite
            #             _best_pass = satpass
            #         # print("{}: quality {}".format(satpass.highest, observation_quality(satpass.highest)))
            # # best_request = (_best_satellite, _best_pass)
            # assert _best_satellite==sorted_passes[0][0], "ERROR: disagreement on best satellite"
            # assert _best_pass==sorted_passes[0][1], "ERROR: disagreement on best pass"

            print("Best request: {} with {}".format(_best_pass, _best_satellite))
        else:
            print("No observation opportunities here")
            # self.requests[request]['status'] = "No observation opportunities";
            _request_dict = {
                'request': request,
                'requested_pass' : None,
                'requested_constellation' : None,
                'requested_satellite' : None,
                'constellation': None,
                'satellite': None,
                'assigned_pass': None,
                'assigned_downlink': None,
                'status': "No observation opportunities",
                'data_product': None,
                'scheduled_callback': lambda x: None,
                'unscheduled_callback': lambda x: None,
                'ready_callback': lambda x: None,
            }
            _pdrequest = pd.DataFrame([_request_dict])
            self._requests = pd.concat([self._requests, _pdrequest], ignore_index=True)

            # self._requests.loc[self._requests['request']==request, 'status'] = "No observation opportunities"
            return -1

        for opportunity_ix in range(min(number_of_submissions, len(sorted_passes))):
            _best_pass = sorted_passes[opportunity_ix][1]
            _best_satellite = sorted_passes[opportunity_ix][0]

            if (_best_pass is not None) and (_best_satellite is not None):
                _best_constellation = _known_satellites_by_constellation[_best_satellite]

                def callback_request_scheduled(assigned_pass):
                    print(" [{}] confirmed scheduling of request {} from {}".format(self.name, request, _best_constellation))
                    # TODO also filter by best_pass.
                    self._requests.loc[((self._requests['request']==request) & (self._requests['requested_pass']==_best_pass)), 'assigned_pass'] = assigned_pass
                    self._requests.loc[((self._requests['request']==request) & (self._requests['requested_pass']==_best_pass)), 'status'] = "Scheduled"
                    self._requests.loc[((self._requests['request']==request) & (self._requests['requested_pass']==_best_pass)), 'constellation'] = _best_constellation
                    self._requests.loc[((self._requests['request']==request) & (self._requests['requested_pass']==_best_pass)), 'satellite'] = _best_satellite
                    return
                
                def callback_request_unscheduled(reason):
                    print(" [{}] received UNscheduling of request {} from {}".format(self.name, request, _best_constellation))
                    # TODO also filter by best_pass.
                    self._requests.loc[((self._requests['request']==request) & (self._requests['requested_pass']==_best_pass)), 'assigned_pass'] = None
                    self._requests.loc[((self._requests['request']==request) & (self._requests['requested_pass']==_best_pass)), 'status'] = reason
                    self._requests.loc[((self._requests['request']==request) & (self._requests['requested_pass']==_best_pass)), 'constellation'] = None
                    self._requests.loc[((self._requests['request']==request) & (self._requests['requested_pass']==_best_pass)), 'satellite'] = None
                    return
                
                def callback_request_ready(data_product):
                    print(" [{}: ] data ready for request {} from {}".format(self.name, request, _best_constellation))
                    # self._requests.loc[self._requests['request']==request, 'assigned_pass'] = None
                    # TODO also filter by best_pass.
                    self._requests.loc[((self._requests['request']==request) & (self._requests['requested_pass']==_best_pass)), 'status'] = "Completed"
                    # self._requests.loc[self._requests['request']==request, 'constellation'] = None
                    # self._requests.loc[self._requests['request']==request, 'satellite'] = None
                    self._requests.loc[((self._requests['request']==request) & (self._requests['requested_pass']==_best_pass)), 'data_product'] = data_product
                    return

                _constellation_request = ObservationRequest(
                    lon_deg=request.lon_deg,
                    lat_deg=request.lat_deg,
                    min_time=_best_pass.rise.time-dt.timedelta(minutes=1), # This is the magic, we constrain the request to the constellation AND TIME that we like.
                    max_time=_best_pass.fall.time+dt.timedelta(minutes=1),
                    alt_km=request.alt_km,
                    instrument=request.instrument,
                    request_name=request.name,
                )

                _request_dict = {
                    'request': request,
                    'requested_pass' : _best_pass,
                    'requested_constellation' : _best_constellation,
                    'requested_satellite' :_best_satellite,
                    'constellation': None,
                    'satellite': None,
                    'assigned_pass': None,
                    'assigned_downlink': None,
                    'status': "Submitted",
                    'data_product': None,
                    'scheduled_callback': lambda x: None,
                    'unscheduled_callback': lambda x: None,
                    'ready_callback': lambda x: None,
                }
                _pdrequest = pd.DataFrame([_request_dict])
                self._requests = pd.concat([self._requests, _pdrequest], ignore_index=True)

                # Submit the request to the relevant constellation
                _best_constellation.schedule_request(
                    request=_constellation_request,
                    current_time=current_time,
                    callback_request_scheduled=callback_request_scheduled,
                    callback_request_unscheduled=callback_request_unscheduled,
                    callback_request_ready=callback_request_ready,
                )
                


    # Do the silly thing: decompose the workflow deterministically, then assign ALL those requests...
    def schedule_workflow(
            self,
            workflow,
            current_time: dt.datetime=dt.datetime.now(dt.timezone.utc).replace(tzinfo=None),
    ):
        pass

In [115]:
sim_start_time = dt.datetime.now(dt.timezone.utc).replace(tzinfo=None)

satellites_LOFT = [
    Satellite("LOFT YAM-6", Orbital("YAM-6", tle_file="TLEs.txt")),
    Satellite("LOFT YAM-10", Orbital("YAM-10", tle_file="TLEs.txt")),
]

satellites_ubotica = [
    Satellite("Ubotica CogniSat-6 HAMMER", Orbital("HAMMER", tle_file="TLEs.txt")),
    ]

satellites_aerospace = [
        Satellite("AEROCUBE 18A", Orbital("AEROCUBE 18A", tle_file="TLEs.txt")),
        Satellite("AEROCUBE 18B", Orbital("AEROCUBE 18B", tle_file="TLEs.txt")),   
]

satellites_multischedulers = satellites_LOFT+satellites_ubotica+satellites_aerospace

In [116]:
world_with_brokers = World(satellites = satellites_multischedulers, phenomena=phenomena_cities)

N_BACKGROUND_SAMPLES = 0

scheduler_LOFT = ConstellationGroundScheduler(satellites=satellites_LOFT, ground_stations=ground_stations, world=world_with_brokers, name="LOFT")
scheduler_ubotica = ConstellationGroundScheduler(satellites=satellites_ubotica, ground_stations=ground_stations, world=world_with_brokers, name="UBOTICA")
scheduler_aerospace = ConstellationGroundScheduler(satellites=satellites_aerospace, ground_stations=ground_stations, world=world_with_brokers, name="AC")

world_with_brokers.add_constellation(scheduler_LOFT)
world_with_brokers.add_constellation(scheduler_ubotica)
world_with_brokers.add_constellation(scheduler_aerospace)

sampled_world_cities_LOFT = cities_of_the_world.sample(n=N_BACKGROUND_SAMPLES,weights='population',axis=0, random_state=0)
sampled_world_cities_ubotica = cities_of_the_world.sample(n=N_BACKGROUND_SAMPLES,weights='population',axis=0, random_state=1)
sampled_world_cities_aerospace = cities_of_the_world.sample(n=N_BACKGROUND_SAMPLES,weights='population',axis=0, random_state=2)
obs_request_LOFT = [
    ObservationRequest(city[1].lng, city[1].lat, min_time=min_time, max_time=max_time, alt_km=0.307, request_name=city[1].city,)
    for city in sampled_world_cities_LOFT.iterrows()
]
obs_request_ubotica = [
    ObservationRequest(city[1].lng, city[1].lat, min_time=min_time, max_time=max_time, alt_km=0.307, request_name=city[1].city,)
    for city in sampled_world_cities_ubotica.iterrows()
]
obs_request_aerospace = [
    ObservationRequest(city[1].lng, city[1].lat, min_time=min_time, max_time=max_time, alt_km=0.307, request_name=city[1].city,)
    for city in sampled_world_cities_aerospace.iterrows()
]


for request in obs_request_LOFT:
    scheduler_LOFT.schedule_request(
        request=request,
        current_time=sim_start_time,
        callback_request_scheduled=lambda obs: print("[LOFT] Request {} scheduled for observation {}!".format(request, obs)),
        callback_request_ready=lambda dp: print("[LOFT] Request {} ready with DP {}!".format(request, dp)),
        )
    
for request in obs_request_ubotica:
    scheduler_ubotica.schedule_request(
        request=request,
        current_time=sim_start_time,
        callback_request_scheduled=lambda obs: print("[UBOTICA] Request {} scheduled for observation {}!".format(request, obs)),
        callback_request_ready=lambda dp: print("[UBOTICA] Request {} ready with DP {}!".format(request, dp)),
        )
    
for request in obs_request_aerospace:
    scheduler_aerospace.schedule_request(
        request=request,
        current_time=sim_start_time,
        callback_request_scheduled=lambda obs: print("[AC] Request {} scheduled for observation {}!".format(request, obs)),
        callback_request_ready=lambda dp: print("[AC] Request {} ready with DP {}!".format(request, dp)),
        )
    
# scheduler_LOFT.schedule_downlinks(current_time=sim_start_time, max_time=sim_start_time+dt.timedelta(hours=36))
# scheduler_ubotica.schedule_downlinks(current_time=sim_start_time, max_time=sim_start_time+dt.timedelta(hours=36))
# scheduler_aerospace.schedule_downlinks(current_time=sim_start_time, max_time=sim_start_time+dt.timedelta(hours=36))

In [117]:
broker = Broker(constellations=[scheduler_LOFT, scheduler_ubotica, scheduler_aerospace], world=world_with_brokers)

world_with_brokers.add_broker(broker)

In [118]:
sampled_world_cities_broker = cities_of_the_world.sample(n=50,weights='population',axis=0, random_state=3)

number_of_submissions = 3

obs_requests_broker = [
    ObservationRequest(city[1].lng, city[1].lat, min_time=min_time, max_time=max_time, alt_km=0.307, request_name=city[1].city,)
    for city in sampled_world_cities_broker.iterrows()
]

for _req in obs_requests_broker:
    broker.schedule_request(_req, number_of_submissions=number_of_submissions)

[Broker] scheduling request Request Kaduna | Lon 7.4333°, lat 10.5167°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Sorted passes:  [(Ubotica CogniSat-6 HAMMER, Pass start: 2025-12-18 01:57:48.495494, highest: 2025-12-18 01:59:52.703176, fall: 2025-12-18 02:01:52.750226), (AEROCUBE 18B, Pass start: 2025-12-17 21:31:42.534577, highest: 2025-12-17 21:34:11.578807, fall: 2025-12-17 21:36:44.528583), (LOFT YAM-10, Pass start: 2025-12-18 00:42:33.962308, highest: 2025-12-18 00:45:52.597114, fall: 2025-12-18 00:49:08.485434), (AEROCUBE 18A, Pass start: 2025-12-17 22:38:38.444834, highest: 2025-12-17 22:40:10.606855, fall: 2025-12-17 22:41:44.652868), (LOFT YAM-6, Pass start: 2025-12-18 02:34:02.413058, highest: 2025-12-18 02:34:57.833228, fall: 2025-12-18 02:35:53.253398), (Ubotica CogniSat-6 HAMMER, Pass start: 2025-12-18 14:52:35.710388, highest: 2025-12-18 14:54:03.557671, fall: 2025-12-18 14:55:34.109513), (LOFT YAM-6, Pass start: 2025-12-18 14:11:27.215304, highest: 2025-12-18 14:14:03.636278, fall: 2025-12-18 14:16:48.341127), (AEROCUBE 18B, Pass start: 2025-12-18 09:27:14.048231, highest: 2025-12-18 09:29:56.604231, fall: 2025-12-18 09:32:38.899473), (LOFT YAM-10, Pass start: 2025-12-18 12:40:35.107707, highest: 2025-12-18 12:43:57.572097, fall: 2025-12-18 12:47:22.250892)]
Best request: Pass start: 2025-12-18 01:57:48.495494, highest: 2025-12-18 01:59:52.703176, fall: 2025-12-18 02:01:52.750226 with Ubotica CogniSat-6 HAMMER
[UBOTICA] Scheduling request Request Kaduna | Lon 7.4333°, lat 10.5167°, alt 0.307 km from 2025-12-18 01:56:48.495494 to 2025-12-18 02:02:52.750226 with RGB
Best request: Pass start: 2025-12-18 01:57:48.495494, highest: 2025-12-18 01:59:50.086991, fall: 2025-12-18 02:01:52.750226 with Ubotica CogniSat-6 HAMMER
No timely contact! Maybe we were too greedy
 [Broker] received UNscheduling of request Request Kaduna | Lon 7.4333°, lat 10.5167°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB from <__main__.ConstellationGroundScheduler object at 0x1492970e0>
[AC] Scheduling request Request Kaduna | Lon 7.4333°, lat 10.5167°, alt 0.307 km from 2025-12-17 21:30:42.534577 to 2025-12-17 21:37:44.528583 with RGB
Best request: Pass start: 2025-12-17 21:31:42.534577, highest: 2025-12-17 21:34:13.821606, fall: 2025-12-17 21:36:44.528583 with AEROCUBE 18B
No timely contact! Maybe we were too greedy
 [Broker] received UNscheduling of request Request Kaduna | Lon 7.4333°, lat 10.5167°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB from <__main__.ConstellationGroundScheduler object at 0x14ac0d6a0>
[LOFT] Scheduling request Request Kaduna | Lon 7.4333°, lat 10.5167°, alt 0.307 km from 2025-12-18 00:41:33.962308 to 2025-12-18 00:50:08.485434 with RGB
Best request: Pass start: 2025-12-18 00:42:33.962308, highest: 2025-12-18 00:45:47.739092, fall: 2025-12-18 00:49:08.485434 with LOFT YAM-10
No timely contact! Maybe we were too greedy
 [Broker] received UNscheduling of request Request Kaduna | Lon 7.4333°, lat 10.5167°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB from <__main__.ConstellationGroundScheduler object at 0x13bedd010>
[Broker] scheduling request Request Wayaobu | Lon 109.6752°, lat 37.1427°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Sorted passes:  [(Ubotica CogniSat-6 HAMMER, Pass start: 2025-12-18 18:54:12.848704, highest: 2025-12-18 18:56:16.891198, fall: 2025-12-18 18:58:30.228458), (AEROCUBE 18A, Pass start: 2025-12-18 15:52:07.698399, highest: 2025-12-18 15:54:49.393340, fall: 2025-12-18 15:57:27.188809), (LOFT YAM-6, Pass start: 2025-12-18 18:19:25.819288, highest: 2025-12-18 18:21:57.044215, fall: 2025-12-18 18:24:28.732644), (LOFT YAM-10, Pass start: 2025-12-18 16:55:18.805545, highest: 2025-12-18 16:58:27.583380, fall: 2025-12-18 17:01:36.852053), (AEROCUBE 18B, Pass start: 2025-12-18 14:46:31.758269, highest: 2025-12-18 14:48:47.246443, fall: 2025-12-18 14:51:00.076487), (AEROCUBE 18B, Pass start: 2025-12-18 16:21:06.786159, highest: 2025-12-18 16:22:18.040043, fall: 2025-12-18 16:23:30.510074), (LOFT YAM-6, Pass start: 2025-12-18 07:48:46.688890, highest: 2025-12-18 07:51:20.184119, fall: 2025-12-18 07:53:57.330218), (Ubotica CogniSat-6 HAMMER, Pass start: 2025-12-18 08:39:22.320669, highest: 2025-12-18 08:39:49.347683, fall: 2025-12-18 08:40:16.374697), (AEROCUBE 18B, Pass start: 2025-12-18 03:15:17.903328, highest: 2025-12-18 03:17:42.293873, fall: 2025-12-18 03:20:04.202589), (AEROCUBE 18A, Pass start: 2025-12-18 02:47:04.014484, highest: 2025-12-18 02:49:58.720821, fall: 2025-12-18 02:52:58.513758), (AEROCUBE 18B, Pass start: 2025-12-18 01:43:49.591647, highest: 2025-12-18 01:44:11.344582, fall: 2025-12-18 01:44:33.097517), (LOFT YAM-10, Pass start: 2025-12-18 06:07:26.693138, highest: 2025-12-18 06:10:54.945395, fall: 2025-12-18 06:14:16.686949)]
Best request: Pass start: 2025-12-18 18:54:12.848704, highest: 2025-12-18 18:56:16.891198, fall: 2025-12-18 18:58:30.228458 with Ubotica CogniSat-6 HAMMER
[UBOTICA] Scheduling request Request Wayaobu | Lon 109.6752°, lat 37.1427°, alt 0.307 km from 2025-12-18 18:53:12.848704 to 2025-12-18 18:59:30.228458 with RGB
Best request: Pass start: 2025-12-18 18:54:12.848704, highest: 2025-12-18 18:56:17.831876, fall: 2025-12-18 18:58:30.228458 with Ubotica CogniSat-6 HAMMER
 [Broker] confirmed scheduling of request Request Wayaobu | Lon 109.6752°, lat 37.1427°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB from <__main__.ConstellationGroundScheduler object at 0x1492970e0>
[AC] Scheduling request Request Wayaobu | Lon 109.6752°, lat 37.1427°, alt 0.307 km from 2025-12-18 15:51:07.698399 to 2025-12-18 15:58:27.188809 with RGB
Best request: Pass start: 2025-12-18 15:52:07.698399, highest: 2025-12-18 15:54:50.126424, fall: 2025-12-18 15:57:27.188809 with AEROCUBE 18A
 [Broker] confirmed scheduling of request Request Wayaobu | Lon 109.6752°, lat 37.1427°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB from <__main__.ConstellationGroundScheduler object at 0x14ac0d6a0>
[LOFT] Scheduling request Request Wayaobu | Lon 109.6752°, lat 37.1427°, alt 0.307 km from 2025-12-18 18:18:25.819288 to 2025-12-18 18:25:28.732644 with RGB
Best request: Pass start: 2025-12-18 18:19:25.819288, highest: 2025-12-18 18:21:57.781548, fall: 2025-12-18 18:24:28.732644 with LOFT YAM-6
 [Broker] confirmed scheduling of request Request Wayaobu | Lon 109.6752°, lat 37.1427°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB from <__main__.ConstellationGroundScheduler object at 0x13bedd010>
[Broker] scheduling request Request Luzhou | Lon 105.442°, lat 28.871°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Sorted passes:  [(AEROCUBE 18A, Pass start: 2025-12-18 15:54:17.728441, highest: 2025-12-18 15:57:03.863098, fall: 2025-12-18 15:59:54.267661), (Ubotica CogniSat-6 HAMMER, Pass start: 2025-12-17 19:55:02.982090, highest: 2025-12-17 19:56:52.963169, fall: 2025-12-17 19:58:40.961401), (Ubotica CogniSat-6 HAMMER, Pass start: 2025-12-18 18:53:43.933464, highest: 2025-12-18 18:54:36.102088, fall: 2025-12-18 18:55:27.414147), (AEROCUBE 18B, Pass start: 2025-12-18 16:23:07.241944, highest: 2025-12-18 16:24:39.925151, fall: 2025-12-18 16:26:10.706057), (LOFT YAM-10, Pass start: 2025-12-18 16:54:51.615148, highest: 2025-12-18 16:56:40.502539, fall: 2025-12-18 16:58:28.082585), (LOFT YAM-6, Pass start: 2025-12-18 18:19:35.084485, highest: 2025-12-18 18:20:11.269630, fall: 2025-12-18 18:20:47.454775), (LOFT YAM-10, Pass start: 2025-12-18 18:29:36.675341, highest: 2025-12-18 18:31:55.299926, fall: 2025-12-18 18:34:14.201297), (AEROCUBE 18B, Pass start: 2025-12-18 14:49:45.482667, highest: 2025-12-18 14:51:02.946534, fall: 2025-12-18 14:52:21.237452), (Ubotica CogniSat-6 HAMMER, Pass start: 2025-12-18 08:41:01.215009, highest: 2025-12-18 08:42:03.912784, fall: 2025-12-18 08:43:07.906927), (LOFT YAM-6, Pass start: 2025-12-18 07:50:57.402428, highest: 2025-12-18 07:53:44.620398, fall: 2025-12-18 07:56:20.243679), (AEROCUBE 18A, Pass start: 2025-12-18 02:45:20.483250, highest: 2025-12-18 02:48:04.677053, fall: 2025-12-18 02:50:54.962425), (AEROCUBE 18B, Pass start: 2025-12-18 03:12:46.222148, highest: 2025-12-18 03:15:46.067193, fall: 2025-12-18 03:18:36.431546), (LOFT YAM-10, Pass start: 2025-12-18 06:09:49.621097, highest: 2025-12-18 06:13:07.614946, fall: 2025-12-18 06:16:34.172229)]
Best request: Pass start: 2025-12-18 15:54:17.728441, highest: 2025-12-18 15:57:03.863098, fall: 2025-12-18 15:59:54.267661 with AEROCUBE 18A
[AC] Scheduling request Request Luzhou | Lon 105.442°, lat 28.871°, alt 0.307 km from 2025-12-18 15:53:17.728441 to 2025-12-18 16:00:54.267661 with RGB
Best request: Pass start: 2025-12-18 15:54:17.728441, highest: 2025-12-18 15:57:08.972209, fall: 2025-12-18 15:59:54.267661 with AEROCUBE 18A
 [Broker] confirmed scheduling of request Request Luzhou | Lon 105.442°, lat 28.871°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB from <__main__.ConstellationGroundScheduler object at 0x14ac0d6a0>
[UBOTICA] Scheduling request Request Luzhou | Lon 105.442°, lat 28.871°, alt 0.307 km from 2025-12-17 19:54:02.982090 to 2025-12-17 19:59:40.961401 with RGB
Best request: Pass start: 2025-12-17 19:55:02.982090, highest: 2025-12-17 19:56:54.101076, fall: 2025-12-17 19:58:40.961401 with Ubotica CogniSat-6 HAMMER
No timely contact! Maybe we were too greedy
 [Broker] received UNscheduling of request Request Luzhou | Lon 105.442°, lat 28.871°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB from <__main__.ConstellationGroundScheduler object at 0x1492970e0>
[UBOTICA] Scheduling request Request Luzhou | Lon 105.442°, lat 28.871°, alt 0.307 km from 2025-12-18 18:52:43.933464 to 2025-12-18 18:56:27.414147 with RGB
Best request: Pass start: 2025-12-18 18:53:43.933464, highest: 2025-12-18 18:54:35.673805, fall: 2025-12-18 18:55:27.414147 with Ubotica CogniSat-6 HAMMER
 [Broker] confirmed scheduling of request Request Luzhou | Lon 105.442°, lat 28.871°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB from <__main__.ConstellationGroundScheduler object at 0x1492970e0>
[Broker] scheduling request Request Islamabad | Lon 73.0639°, lat 33.6931°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Sorted passes:  [(AEROCUBE 18A, Pass start: 2025-12-18 17:28:08.898463, highest: 2025-12-18 17:30:56.718642, fall: 2025-12-18 17:33:43.800319), (Ubotica CogniSat-6 HAMMER, Pass start: 2025-12-17 21:28:02.884764, highest: 2025-12-17 21:30:08.250756, fall: 2025-12-17 21:32:28.201498), (AEROCUBE 18B, Pass start: 2025-12-18 17:55:40.032229, highest: 2025-12-18 17:58:45.034811, fall: 2025-12-18 18:01:36.673915), (LOFT YAM-10, Pass start: 2025-12-17 19:59:20.353504, highest: 2025-12-17 20:02:48.261143, fall: 2025-12-17 20:06:08.338358), (LOFT YAM-6, Pass start: 2025-12-17 20:25:26.881722, highest: 2025-12-17 20:26:35.907699, fall: 2025-12-17 20:27:43.617263), (LOFT YAM-6, Pass start: 2025-12-17 21:57:49.343899, highest: 2025-12-17 21:59:24.304392, fall: 2025-12-17 22:01:00.150814), (Ubotica CogniSat-6 HAMMER, Pass start: 2025-12-18 10:10:57.538416, highest: 2025-12-18 10:13:03.777969, fall: 2025-12-18 10:15:23.981293), (LOFT YAM-6, Pass start: 2025-12-18 09:24:24.931054, highest: 2025-12-18 09:26:44.774181, fall: 2025-12-18 09:28:59.958546), (AEROCUBE 18B, Pass start: 2025-12-18 04:49:14.735554, highest: 2025-12-18 04:51:59.504321, fall: 2025-12-18 04:54:47.092919), (AEROCUBE 18A, Pass start: 2025-12-18 04:22:57.741108, highest: 2025-12-18 04:24:33.259768, fall: 2025-12-18 04:26:07.536878), (AEROCUBE 18A, Pass start: 2025-12-18 05:56:30.246242, highest: 2025-12-18 05:58:07.705386, fall: 2025-12-18 05:59:47.094689), (LOFT YAM-10, Pass start: 2025-12-18 09:21:50.487402, highest: 2025-12-18 09:24:00.993056, fall: 2025-12-18 09:26:11.806833), (LOFT YAM-10, Pass start: 2025-12-18 07:46:24.871449, highest: 2025-12-18 07:48:43.001273, fall: 2025-12-18 07:50:58.731927)]
Best request: Pass start: 2025-12-18 17:28:08.898463, highest: 2025-12-18 17:30:56.718642, fall: 2025-12-18 17:33:43.800319 with AEROCUBE 18A
[AC] Scheduling request Request Islamabad | Lon 73.0639°, lat 33.6931°, alt 0.307 km from 2025-12-18 17:27:08.898463 to 2025-12-18 17:34:43.800319 with RGB
Best request: Pass start: 2025-12-18 17:28:08.898463, highest: 2025-12-18 17:30:59.363162, fall: 2025-12-18 17:33:43.800319 with AEROCUBE 18A
 [Broker] confirmed scheduling of request Request Islamabad | Lon 73.0639°, lat 33.6931°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB from <__main__.ConstellationGroundScheduler object at 0x14ac0d6a0>
[UBOTICA] Scheduling request Request Islamabad | Lon 73.0639°, lat 33.6931°, alt 0.307 km from 2025-12-17 21:27:02.884764 to 2025-12-17 21:33:28.201498 with RGB
Best request: Pass start: 2025-12-17 21:28:02.884764, highest: 2025-12-17 21:30:09.482672, fall: 2025-12-17 21:32:28.201498 with Ubotica CogniSat-6 HAMMER
No timely contact! Maybe we were too greedy
 [Broker] received UNscheduling of request Request Islamabad | Lon 73.0639°, lat 33.6931°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB from <__main__.ConstellationGroundScheduler object at 0x1492970e0>
[AC] Scheduling request Request Islamabad | Lon 73.0639°, lat 33.6931°, alt 0.307 km from 2025-12-18 17:54:40.032229 to 2025-12-18 18:02:36.673915 with RGB
Best request: Pass start: 2025-12-18 17:55:40.032229, highest: 2025-12-18 17:58:39.352988, fall: 2025-12-18 18:01:36.673915 with AEROCUBE 18B
 [Broker] confirmed scheduling of request Request Islamabad | Lon 73.0639°, lat 33.6931°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB from <__main__.ConstellationGroundScheduler object at 0x14ac0d6a0>
[Broker] scheduling request Request Haomen | Lon 101.5871°, lat 37.3619°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Sorted passes:  [(AEROCUBE 18B, Pass start: 2025-12-18 16:20:00.423568, highest: 2025-12-18 16:22:49.172319, fall: 2025-12-18 16:25:32.926995), (Ubotica CogniSat-6 HAMMER, Pass start: 2025-12-17 19:57:02.465719, highest: 2025-12-17 19:59:03.900438, fall: 2025-12-17 20:01:12.437054), (Ubotica CogniSat-6 HAMMER, Pass start: 2025-12-18 18:56:23.732891, highest: 2025-12-18 18:56:52.649004, fall: 2025-12-18 18:57:21.565115), (AEROCUBE 18A, Pass start: 2025-12-18 15:52:08.818621, highest: 2025-12-18 15:55:03.054189, fall: 2025-12-18 15:58:07.515819), (LOFT YAM-10, Pass start: 2025-12-18 18:31:28.681310, highest: 2025-12-18 18:34:16.859059, fall: 2025-12-18 18:37:08.588244), (LOFT YAM-10, Pass start: 2025-12-18 16:57:18.947839, highest: 2025-12-18 16:59:04.159127, fall: 2025-12-18 17:00:50.421545), (Ubotica CogniSat-6 HAMMER, Pass start: 2025-12-18 08:38:05.078291, highest: 2025-12-18 08:40:08.424846, fall: 2025-12-18 08:42:23.007366), (LOFT YAM-6, Pass start: 2025-12-18 07:48:59.286084, highest: 2025-12-18 07:51:46.160202, fall: 2025-12-18 07:54:22.184247), (AEROCUBE 18A, Pass start: 2025-12-18 02:47:46.407616, highest: 2025-12-18 02:50:27.999453, fall: 2025-12-18 02:53:09.713166), (LOFT YAM-10, Pass start: 2025-12-18 06:08:08.634234, highest: 2025-12-18 06:11:05.819103, fall: 2025-12-18 06:14:04.318797), (AEROCUBE 18B, Pass start: 2025-12-18 03:15:02.690823, highest: 2025-12-18 03:17:58.277387, fall: 2025-12-18 03:20:59.370453), (LOFT YAM-10, Pass start: 2025-12-18 07:45:00.074997, highest: 2025-12-18 07:46:16.481183, fall: 2025-12-18 07:47:33.911364)]
Best request: Pass start: 2025-12-18 16:20:00.423568, highest: 2025-12-18 16:22:49.172319, fall: 2025-12-18 16:25:32.926995 with AEROCUBE 18B
[AC] Scheduling request Request Haomen | Lon 101.5871°, lat 37.3619°, alt 0.307 km from 2025-12-18 16:19:00.423568 to 2025-12-18 16:26:32.926995 with RGB
Best request: Pass start: 2025-12-18 16:20:00.423568, highest: 2025-12-18 16:22:49.735404, fall: 2025-12-18 16:25:32.926995 with AEROCUBE 18B
 [Broker] confirmed scheduling of request Request Haomen | Lon 101.5871°, lat 37.3619°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB from <__main__.ConstellationGroundScheduler object at 0x14ac0d6a0>
[UBOTICA] Scheduling request Request Haomen | Lon 101.5871°, lat 37.3619°, alt 0.307 km from 2025-12-17 19:56:02.465719 to 2025-12-17 20:02:12.437054 with RGB
Best request: Pass start: 2025-12-17 19:57:02.465719, highest: 2025-12-17 19:59:05.610743, fall: 2025-12-17 20:01:12.437054 with Ubotica CogniSat-6 HAMMER
No timely contact! Maybe we were too greedy
 [Broker] received UNscheduling of request Request Haomen | Lon 101.5871°, lat 37.3619°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB from <__main__.ConstellationGroundScheduler object at 0x1492970e0>
[UBOTICA] Scheduling request Request Haomen | Lon 101.5871°, lat 37.3619°, alt 0.307 km from 2025-12-18 18:55:23.732891 to 2025-12-18 18:58:21.565115 with RGB
No observation opportunities here
{Request Haomen | Lon 101.5871°, lat 37.3619°, alt 0.307 km from 2025-12-18 18:55:23.732891 to 2025-12-18 18:58:21.565115 with RGB: {}}
 [Broker] received UNscheduling of request Request Haomen | Lon 101.5871°, lat 37.3619°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB from <__main__.ConstellationGroundScheduler object at 0x1492970e0>
[Broker] scheduling request Request Tangancícuaro de Arista | Lon -102.208°, lat 19.887°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB
Sorted passes:  [(LOFT YAM-10, Pass start: 2025-12-18 07:12:02.380258, highest: 2025-12-18 07:14:56.185007, fall: 2025-12-18 07:17:50.114615), (Ubotica CogniSat-6 HAMMER, Pass start: 2025-12-18 09:38:46.757834, highest: 2025-12-18 09:40:55.630958, fall: 2025-12-18 09:43:02.871034), (LOFT YAM-6, Pass start: 2025-12-18 08:51:01.817075, highest: 2025-12-18 08:53:48.655370, fall: 2025-12-18 08:56:27.774644), (AEROCUBE 18A, Pass start: 2025-12-18 04:54:44.233253, highest: 2025-12-18 04:57:14.264156, fall: 2025-12-18 04:59:47.861454), (AEROCUBE 18B, Pass start: 2025-12-18 05:21:52.629559, highest: 2025-12-18 05:24:54.867710, fall: 2025-12-18 05:27:51.400780), (Ubotica CogniSat-6 HAMMER, Pass start: 2025-12-17 21:59:57.947423, highest: 2025-12-17 22:02:02.138526, fall: 2025-12-17 22:04:13.738290), (LOFT YAM-6, Pass start: 2025-12-17 20:56:52.123519, highest: 2025-12-17 20:59:00.484972, fall: 2025-12-17 21:01:09.891142), (AEROCUBE 18B, Pass start: 2025-12-18 17:22:44.231610, highest: 2025-12-18 17:25:18.878149, fall: 2025-12-18 17:27:57.637374), (AEROCUBE 18A, Pass start: 2025-12-18 16:54:43.687167, highest: 2025-12-18 16:57:46.935427, fall: 2025-12-18 17:00:37.144008), (LOFT YAM-10, Pass start: 2025-12-17 20:33:17.932138, highest: 2025-12-17 20:36:09.392176, fall: 2025-12-17 20:39:03.452944)]
Best request: Pass start: 2025-12-18 07:12:02.380258, highest: 2025-12-18 07:14:56.185007, fall: 2025-12-18 07:17:50.114615 with LOFT YAM-10
[LOFT] Scheduling request Request Tangancícuaro de Arista | Lon -102.208°, lat 19.887°, alt 0.307 km from 2025-12-18 07:11:02.380258 to 2025-12-18 07:18:50.114615 with RGB
Best request: Pass start: 2025-12-18 07:12:02.380258, highest: 2025-12-18 07:14:56.905610, fall: 2025-12-18 07:17:50.114615 with LOFT YAM-10
 [Broker] confirmed scheduling of request Request Tangancícuaro de Arista | Lon -102.208°, lat 19.887°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB from <__main__.ConstellationGroundScheduler object at 0x13bedd010>

In [119]:
retcode = 1
while (retcode !=0):
    # print("Tick!")
    retcode = world_with_brokers.tick(print_forbidden_prefixes=["Downlink", "End of downlink", "Unlock uplink", "Unlock satellite after obs"])
    # print(world_with_scheduler.events)

Executing Event Uplink, station KSAT Troll to sat LOFT YAM-6 at 2025-12-18 02:13:59.075817
Executing Event Obs, sat LOFT YAM-6 at 2025-12-18 02:34:05.059563
Executing Event Uplink, station KSAT Nuuk to sat AEROCUBE 18B at 2025-12-18 03:37:52.443869
Executing Event Obs, sat AEROCUBE 18B at 2025-12-18 03:54:19.008380
Executing Event Uplink, station KSAT Nuuk to sat AEROCUBE 18A at 2025-12-18 04:43:28.781856
Executing Event Uplink, station KSAT Nuuk to sat AEROCUBE 18A at 2025-12-18 04:43:28.781856
Executing Event Uplink, station KSAT Nuuk to sat AEROCUBE 18A at 2025-12-18 04:43:28.781856
Executing Event Uplink, station KSAT Nuuk to sat AEROCUBE 18A at 2025-12-18 04:43:28.781856
Executing Event Obs, sat AEROCUBE 18A at 2025-12-18 04:51:31.406483
Executing Event Obs, sat AEROCUBE 18A at 2025-12-18 04:51:31.406483
Executing Event Obs, sat AEROCUBE 18A at 2025-12-18 04:57:17.839411
Executing Event Obs, sat AEROCUBE 18A at 2025-12-18 04:57:17.839411
Executing Event Uplink, station KSAT Svalbard to sat AEROCUBE 18B at 2025-12-18 05:05:09.244837
Executing Event Uplink, station KSAT Svalbard to sat AEROCUBE 18B at 2025-12-18 05:05:09.244837
Executing Event Uplink, station KSAT Svalbard to sat AEROCUBE 18B at 2025-12-18 05:05:09.244837
Executing Event Uplink, station KSAT Svalbard to sat AEROCUBE 18B at 2025-12-18 05:05:09.244837
Executing Event Obs, sat AEROCUBE 18B at 2025-12-18 05:18:57.799832
Executing Event Obs, sat AEROCUBE 18B at 2025-12-18 05:18:57.799832
Executing Event Obs, sat AEROCUBE 18B at 2025-12-18 05:24:52.016742
Executing Event Obs, sat AEROCUBE 18B at 2025-12-18 05:24:52.016742
Executing Event Uplink, station KSAT Svalbard to sat AEROCUBE 18A at 2025-12-18 06:11:10.339924
Executing Event Uplink, station KSAT Svalbard to sat AEROCUBE 18A at 2025-12-18 06:11:10.339924
Executing Event Obs, sat AEROCUBE 18A at 2025-12-18 06:28:00.616446
Executing Event Obs, sat AEROCUBE 18A at 2025-12-18 06:28:00.616446
Executing Event Uplink, station KSAT Svalbard to sat AEROCUBE 18B at 2025-12-18 06:38:57.500016
Executing Event Uplink, station KSAT Svalbard to sat AEROCUBE 18B at 2025-12-18 06:38:57.500016
Executing Event Uplink, station KSAT Svalbard to sat AEROCUBE 18B at 2025-12-18 06:38:57.500016
Executing Event Obs, sat AEROCUBE 18B at 2025-12-18 06:53:27.989868
Executing Event Obs, sat AEROCUBE 18B at 2025-12-18 06:55:37.405563
Executing Event Obs, sat AEROCUBE 18B at 2025-12-18 06:55:37.405563
Executing Event Uplink, station KSAT Punta Arenas to sat LOFT YAM-6 at 2025-12-18 07:00:50.225641
Executing Event Uplink, station KSAT Punta Arenas to sat LOFT YAM-6 at 2025-12-18 07:00:50.225641
Executing Event Uplink, station KSAT Panama to sat LOFT YAM-10 at 2025-12-18 07:10:56.859245
Executing Event Uplink, station KSAT Panama to sat LOFT YAM-10 at 2025-12-18 07:10:56.859245
Executing Event Uplink, station KSAT Panama to sat LOFT YAM-10 at 2025-12-18 07:10:56.859245
Executing Event Obs, sat LOFT YAM-10 at 2025-12-18 07:12:48.668164
Executing Event Obs, sat LOFT YAM-10 at 2025-12-18 07:14:56.905610
Executing Event Obs, sat LOFT YAM-10 at 2025-12-18 07:14:56.905610
Executing Event Obs, sat LOFT YAM-6 at 2025-12-18 07:25:13.747439
Executing Event Obs, sat LOFT YAM-6 at 2025-12-18 07:25:13.747439
Executing Event Uplink, station KSAT Panama to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 08:06:17.907018
Executing Event Uplink, station KSAT Panama to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 08:06:17.907018
Executing Event Uplink, station KSAT Panama to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 08:06:17.907018
Executing Event Uplink, station KSAT Panama to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 08:06:17.907018
Executing Event Uplink, station KSAT Panama to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 08:06:17.907018
Executing Event Uplink, station KSAT Punta Arenas to sat LOFT YAM-6 at 2025-12-18 08:33:53.264830
Executing Event Uplink, station KSAT Punta Arenas to sat LOFT YAM-6 at 2025-12-18 08:33:53.264830
Executing Event Uplink, station KSAT Punta Arenas to sat LOFT YAM-6 at 2025-12-18 08:33:53.264830
Executing Event Obs, sat LOFT YAM-6 at 2025-12-18 08:53:49.436200
Executing Event Obs, sat LOFT YAM-6 at 2025-12-18 08:53:49.436200
Executing Event Obs, sat LOFT YAM-6 at 2025-12-18 08:59:32.552927
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 09:40:51.662104
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 09:40:51.662104
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 09:45:13.333495
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 09:45:13.333495
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 09:46:27.023304
Executing Event Uplink, station KSAT Troll to sat LOFT YAM-6 at 2025-12-18 09:56:48.721557
Executing Event Obs, sat LOFT YAM-6 at 2025-12-18 10:31:59.362971
Executing Event Uplink, station KSAT Nuuk to sat AEROCUBE 18B at 2025-12-18 12:53:14.751491
Executing Event Obs, sat AEROCUBE 18B at 2025-12-18 13:14:10.795189
Executing Event Uplink, station KSAT Vardo to sat LOFT YAM-10 at 2025-12-18 14:02:55.763037
Executing Event Uplink, station KSAT Hokkaido to sat AEROCUBE 18A at 2025-12-18 14:17:54.866851
Executing Event Uplink, station KSAT Hokkaido to sat AEROCUBE 18A at 2025-12-18 14:17:54.866851
Executing Event Uplink, station KSAT Hokkaido to sat AEROCUBE 18A at 2025-12-18 14:17:54.866851
Executing Event Uplink, station KSAT Hokkaido to sat AEROCUBE 18A at 2025-12-18 14:17:54.866851
Executing Event Obs, sat AEROCUBE 18A at 2025-12-18 14:20:35.265211
Executing Event Obs, sat AEROCUBE 18A at 2025-12-18 14:20:35.265211
Executing Event Obs, sat AEROCUBE 18A at 2025-12-18 14:22:52.627975
Executing Event Obs, sat AEROCUBE 18A at 2025-12-18 14:23:58.053159
Executing Event Uplink, station KSAT Nuuk to sat AEROCUBE 18B at 2025-12-18 14:27:42.234420
Executing Event Uplink, station KSAT Nuuk to sat AEROCUBE 18B at 2025-12-18 14:27:42.234420
Executing Event Uplink, station KSAT Nuuk to sat AEROCUBE 18B at 2025-12-18 14:27:42.234420
Executing Event Uplink, station KSAT Nuuk to sat AEROCUBE 18B at 2025-12-18 14:27:42.234420
Executing Event Uplink, station KSAT Nuuk to sat AEROCUBE 18B at 2025-12-18 14:27:42.234420
Executing Event Obs, sat AEROCUBE 18B at 2025-12-18 14:47:42.100557
Executing Event Obs, sat AEROCUBE 18B at 2025-12-18 14:49:27.362301
Executing Event Obs, sat AEROCUBE 18B at 2025-12-18 14:50:31.760098
Executing Event Obs, sat AEROCUBE 18B at 2025-12-18 14:52:27.706626
Executing Event Obs, sat AEROCUBE 18B at 2025-12-18 14:54:08.798972
Executing Event Uplink, station KSAT Panama to sat AEROCUBE 18A at 2025-12-18 15:20:15.423942
Executing Event Uplink, station KSAT Panama to sat AEROCUBE 18A at 2025-12-18 15:20:15.423942
Executing Event Uplink, station KSAT Panama to sat AEROCUBE 18A at 2025-12-18 15:20:15.423942
Executing Event Uplink, station KSAT Panama to sat AEROCUBE 18A at 2025-12-18 15:20:15.423942
Executing Event Uplink, station KSAT Panama to sat AEROCUBE 18A at 2025-12-18 15:20:15.423942
Executing Event Uplink, station KSAT Panama to sat AEROCUBE 18A at 2025-12-18 15:20:15.423942
Executing Event Obs, sat LOFT YAM-10 at 2025-12-18 15:21:13.762118
Executing Event Uplink, station KSAT Vardo to sat LOFT YAM-6 at 2025-12-18 15:31:00.333692
Executing Event Uplink, station KSAT Vardo to sat LOFT YAM-6 at 2025-12-18 15:31:00.333692
Executing Event Uplink, station KSAT Panama to sat AEROCUBE 18B at 2025-12-18 15:47:59.465644
Executing Event Uplink, station KSAT Panama to sat AEROCUBE 18B at 2025-12-18 15:47:59.465644
Executing Event Uplink, station KSAT Panama to sat AEROCUBE 18B at 2025-12-18 15:47:59.465644
Executing Event Uplink, station KSAT Panama to sat AEROCUBE 18B at 2025-12-18 15:47:59.465644
Executing Event Obs, sat AEROCUBE 18A at 2025-12-18 15:54:50.126424
Executing Event Obs, sat AEROCUBE 18A at 2025-12-18 15:54:50.126424
Executing Event Obs, sat AEROCUBE 18A at 2025-12-18 15:57:08.972209
Executing Event Obs, sat AEROCUBE 18A at 2025-12-18 15:57:08.972209
Executing Event Obs, sat AEROCUBE 18A at 2025-12-18 15:58:14.597587
Executing Event Obs, sat AEROCUBE 18A at 2025-12-18 15:59:33.869593
Executing Event Uplink, station KSAT Vardo to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 16:09:09.419820
Executing Event Uplink, station KSAT Vardo to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 16:09:09.419820
Executing Event Uplink, station KSAT Punta Arenas to sat LOFT YAM-10 at 2025-12-18 16:14:55.241287
Executing Event Uplink, station KSAT Punta Arenas to sat LOFT YAM-10 at 2025-12-18 16:14:55.241287
Executing Event Uplink, station KSAT Punta Arenas to sat LOFT YAM-10 at 2025-12-18 16:14:55.241287
Executing Event Obs, sat AEROCUBE 18B at 2025-12-18 16:22:49.735404
Executing Event Obs, sat AEROCUBE 18B at 2025-12-18 16:22:49.735404
Executing Event Obs, sat AEROCUBE 18B at 2025-12-18 16:25:47.328517
Executing Event Obs, sat AEROCUBE 18B at 2025-12-18 16:27:18.671949
Executing Event Uplink, station KSAT Punta Arenas to sat AEROCUBE 18A at 2025-12-18 16:37:38.277354
Executing Event Uplink, station KSAT Punta Arenas to sat AEROCUBE 18A at 2025-12-18 16:37:38.277354
Executing Event Uplink, station KSAT Punta Arenas to sat AEROCUBE 18A at 2025-12-18 16:37:38.277354
Executing Event Uplink, station KSAT Punta Arenas to sat AEROCUBE 18A at 2025-12-18 16:37:38.277354
Executing Event Uplink, station KSAT Punta Arenas to sat AEROCUBE 18A at 2025-12-18 16:37:38.277354
Executing Event Uplink, station KSAT Punta Arenas to sat AEROCUBE 18A at 2025-12-18 16:37:38.277354
Executing Event Obs, sat LOFT YAM-6 at 2025-12-18 16:47:22.006467
Executing Event Obs, sat LOFT YAM-6 at 2025-12-18 16:47:22.006467
Executing Event Obs, sat LOFT YAM-10 at 2025-12-18 16:54:40.061938
Executing Event Obs, sat LOFT YAM-10 at 2025-12-18 16:57:11.482848
Executing Event Obs, sat LOFT YAM-10 at 2025-12-18 16:58:18.296572
Executing Event Uplink, station KSAT Punta Arenas to sat AEROCUBE 18B at 2025-12-18 17:05:06.886863
Executing Event Uplink, station KSAT Punta Arenas to sat AEROCUBE 18B at 2025-12-18 17:05:06.886863
Executing Event Uplink, station KSAT Punta Arenas to sat AEROCUBE 18B at 2025-12-18 17:05:06.886863
Executing Event Uplink, station KSAT Punta Arenas to sat AEROCUBE 18B at 2025-12-18 17:05:06.886863
Executing Event Uplink, station KSAT Punta Arenas to sat AEROCUBE 18B at 2025-12-18 17:05:06.886863
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 17:23:49.623889
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 17:25:22.925327
Executing Event Obs, sat AEROCUBE 18A at 2025-12-18 17:27:46.182003
Executing Event Obs, sat AEROCUBE 18A at 2025-12-18 17:30:59.363162
Executing Event Obs, sat AEROCUBE 18A at 2025-12-18 17:30:59.363162
Executing Event Obs, sat AEROCUBE 18A at 2025-12-18 17:34:43.528068
Executing Event Obs, sat AEROCUBE 18A at 2025-12-18 17:34:43.528068
Executing Event Obs, sat AEROCUBE 18A at 2025-12-18 17:36:47.760775
Executing Event Uplink, station KSAT Mauritius to sat AEROCUBE 18A at 2025-12-18 17:45:28.187106
Executing Event Uplink, station KSAT Punta Arenas to sat LOFT YAM-10 at 2025-12-18 17:50:16.543418
Executing Event Obs, sat AEROCUBE 18B at 2025-12-18 17:58:39.352988
Executing Event Obs, sat AEROCUBE 18B at 2025-12-18 17:58:39.352988
Executing Event Obs, sat AEROCUBE 18B at 2025-12-18 18:02:23.344147
Executing Event Obs, sat AEROCUBE 18B at 2025-12-18 18:02:23.344147
Executing Event Obs, sat AEROCUBE 18B at 2025-12-18 18:04:22.582323
Executing Event Uplink, station KSAT Punta Arenas to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 18:14:51.323776
Executing Event Uplink, station KSAT Punta Arenas to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 18:14:51.323776
Executing Event Uplink, station KSAT Punta Arenas to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 18:14:51.323776
Executing Event Uplink, station KSAT Punta Arenas to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 18:14:51.323776
Executing Event Uplink, station KSAT Punta Arenas to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 18:14:51.323776
Executing Event Uplink, station KSAT Punta Arenas to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 18:14:51.323776
Executing Event Uplink, station KSAT Okinawa to sat LOFT YAM-6 at 2025-12-18 18:18:25.595190
Executing Event Uplink, station KSAT Okinawa to sat LOFT YAM-6 at 2025-12-18 18:18:25.595190
Executing Event Uplink, station KSAT Okinawa to sat LOFT YAM-6 at 2025-12-18 18:18:25.595190
Executing Event Obs, sat LOFT YAM-6 at 2025-12-18 18:20:54.151543
Executing Event Obs, sat LOFT YAM-6 at 2025-12-18 18:21:57.781548
Executing Event Obs, sat LOFT YAM-6 at 2025-12-18 18:21:57.781548
Executing Event Uplink, station KSAT Troll to sat AEROCUBE 18B at 2025-12-18 18:28:45.319599
Executing Event Obs, sat LOFT YAM-10 at 2025-12-18 18:30:56.816464
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 18:50:08.384640
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 18:52:42.500152
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 18:54:35.673805
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 18:54:35.673805
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 18:56:17.831876
Executing Event Obs, sat Ubotica CogniSat-6 HAMMER at 2025-12-18 18:56:17.831876
Executing Event Obs, sat AEROCUBE 18A at 2025-12-18 19:05:49.510943
Executing Event Obs, sat AEROCUBE 18B at 2025-12-18 19:32:21.833756
Spacecraft LOFT YAM-6 has 8 data products to download
  Downlinked Observation  at 2025-12-18 02:34:05.059563 with RGB. Look angle 258.2839897411559 | 32.921929308606934 az/dec deg, zenith angle 135.57021326154998 deg, range 806.6893633796532 km, duration 0:01:00
 [Broker: ] data ready for request Request Lagos | Lon 3.3841°, lat 6.455°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB from <__main__.ConstellationGroundScheduler object at 0x13bedd010>
  Downlinked Observation  at 2025-12-18 07:25:13.747439 with RGB. Look angle 71.56109877509641 | 41.90940000643703 az/dec deg, zenith angle 152.62133593143025 deg, range 678.7575214604044 km, duration 0:01:00
 [Broker: ] data ready for request Request Indianapolis | Lon -86.1458°, lat 39.7771°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB from <__main__.ConstellationGroundScheduler object at 0x14ac0d6a0>
  Downlinked Observation  at 2025-12-18 08:53:49.436200 with RGB. Look angle 71.61879516663757 | 53.29307933604995 az/dec deg, zenith angle 150.03448553134098 deg, range 576.5126536479669 km, duration 0:01:00
 [Broker: ] data ready for request Request Tangancícuaro de Arista | Lon -102.208°, lat 19.887°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB from <__main__.ConstellationGroundScheduler object at 0x13bedd010>
  Downlinked Observation  at 2025-12-18 08:59:32.552927 with RGB. Look angle 73.26393858685864 | 33.37150037940118 az/dec deg, zenith angle 153.4201947819824 deg, range 799.1155329949972 km, duration 0:01:00
 [Broker: ] data ready for request Request Clearfield | Lon -112.0238°, lat 41.103°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB from <__main__.ConstellationGroundScheduler object at 0x1492970e0>
  Downlinked Observation  at 2025-12-18 10:31:59.362971 with RGB. Look angle 262.6887098048875 | 39.708966503809926 az/dec deg, zenith angle 144.74570917643732 deg, range 704.5249335519446 km, duration 0:01:00
 [Broker: ] data ready for request Request Modesto | Lon -121.0028°, lat 37.6375°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB from <__main__.ConstellationGroundScheduler object at 0x13bedd010>
  Downlinked Observation  at 2025-12-18 16:47:22.006467 with RGB. Look angle 72.01596417852082 | 44.3868737825872 az/dec deg, zenith angle 153.299934575159 deg, range 651.2122037001275 km, duration 0:01:00
 [Broker: ] data ready for request Request Kōbe | Lon 135.1956°, lat 34.69°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB from <__main__.ConstellationGroundScheduler object at 0x13bedd010>
  Downlinked Observation  at 2025-12-18 18:20:54.151543 with RGB. Look angle 65.45503837115804 | 65.50912167193708 az/dec deg, zenith angle 151.27358237335318 deg, range 514.1560430005502 km, duration 0:01:00
 [Broker: ] data ready for request Request Zhoukou | Lon 114.7014°, lat 33.6367°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB from <__main__.ConstellationGroundScheduler object at 0x13bedd010>
  Downlinked Observation  at 2025-12-18 18:21:57.781548 with RGB. Look angle 73.36445709303375 | 37.76457990944221 az/dec deg, zenith angle 153.84721930845012 deg, range 730.1751983735251 km, duration 0:01:00
 [Broker: ] data ready for request Request Wayaobu | Lon 109.6752°, lat 37.1427°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB from <__main__.ConstellationGroundScheduler object at 0x13bedd010>
Spacecraft AEROCUBE 18B has 18 data products to download
  Downlinked Observation  at 2025-12-18 03:54:19.008380 with RGB. Look angle 282.0195077313904 | 29.71612260750655 az/dec deg, zenith angle 154.31430307264628 deg, range 925.5699511194322 km, duration 0:01:00
 [Broker: ] data ready for request Request Palermo | Lon -75.4375°, lat 2.8917°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB from <__main__.ConstellationGroundScheduler object at 0x13bedd010>
  Downlinked Observation  at 2025-12-18 05:18:57.799832 with RGB. Look angle 290.0397728918258 | 22.89081788869282 az/dec deg, zenith angle 162.95423142832743 deg, range 1109.7207300180555 km, duration 0:01:00
 [Broker: ] data ready for request Request Indianapolis | Lon -86.1458°, lat 39.7771°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB from <__main__.ConstellationGroundScheduler object at 0x14ac0d6a0>
  Downlinked Observation  at 2025-12-18 05:24:52.016742 with RGB. Look angle 279.7983972581786 | 51.94967008471096 az/dec deg, zenith angle 163.63996474072596 deg, range 627.9789452814276 km, duration 0:01:00
 [Broker: ] data ready for request Request Mexico City | Lon -99.1333°, lat 19.4333°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB from <__main__.ConstellationGroundScheduler object at 0x14ac0d6a0>
  Downlinked Observation  at 2025-12-18 06:53:27.989868 with RGB. Look angle 288.8109653302944 | 30.679680171981886 az/dec deg, zenith angle 161.1176869870831 deg, range 908.5712120741832 km, duration 0:01:00
 [Broker: ] data ready for request Request Clearfield | Lon -112.0238°, lat 41.103°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB from <__main__.ConstellationGroundScheduler object at 0x1492970e0>
  Downlinked Observation  at 2025-12-18 06:55:37.405563 with RGB. Look angle 282.0623342651672 | 48.48019436887401 az/dec deg, zenith angle 163.95797304065567 deg, range 658.3903018552668 km, duration 0:01:00
 [Broker: ] data ready for request Request Los Angeles | Lon -118.4068°, lat 34.1141°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB from <__main__.ConstellationGroundScheduler object at 0x14ac0d6a0>
  Downlinked Observation  at 2025-12-18 13:14:10.795189 with RGB. Look angle 102.17555276170957 | 57.57858898454288 az/dec deg, zenith angle 157.81739273090218 deg, range 591.8729344026643 km, duration 0:01:00
 [Broker: ] data ready for request Request Kazo | Lon 139.6018°, lat 36.1314°, alt 0.307 km from 2025-12-17 19:36:56.704608 to 2025-12-18 19:36:56.704608 with RGB from <__main__.ConstellationGroundScheduler object at 0x14ac0d6a0>
  Downlinked Observation  at 2025-12-18 14:47:42.100557 with RGB. Look angle 283.7282315678341 | 43.38980475191991 az/dec deg, zenith angle 161.5706623693596 deg, range 710.6798330630378 km, duration 0:01:00

In [120]:
request_statistics(broker._requests)

35/151 (23.178807947019866%) of requests are in status No timely contact
0/151 (0.0%) of requests are in status nan
1/151 (0.6622516556291391%) of requests are in status No observation opportunities
36/151 (23.841059602649008%) of requests are in status Scheduled
46/151 (30.4635761589404%) of requests are in status All observation opportunities are conflicting
32/151 (21.192052980132452%) of requests are in status Completed

In [121]:
def retell_history(world: World):
    for _chronicle in world.history:
        print("Time: {}. Event: {}".format(_chronicle['time'], _chronicle['event']))
        if type(_chronicle['event'])==ObservationEvent:
            print("Observation: sat {} and opportunity {}".format(_chronicle['event'].satellite, _chronicle['event'].opportunity))
        if type(_chronicle['event'])==CommunicationEvent:
            print("Communication: station {} to sat {} during pass {}".format(_chronicle['event'].station, _chronicle['event'].satellite, _chronicle['event'].comm_pass))

In [122]:
retell_history(world_with_brokers)

Time: 2025-12-18 02:13:59.075817. Event: Event Uplink, station KSAT Troll to sat LOFT YAM-6 at 2025-12-18 02:13:59.075817
Communication: station Location KSAT Troll | Lon 2.53219°, lat -72.01243°, alt 0 km to sat LOFT YAM-6 during pass Pass start: 2025-12-18 02:11:43.341037, highest: 2025-12-18 02:13:59.075817, fall: 2025-12-18 02:16:11.886990
Time: 2025-12-18 02:16:11.886990. Event: Event Unlock uplink, station KSAT Troll to sat LOFT YAM-6 at 2025-12-18 02:16:11.886990
Time: 2025-12-18 02:34:05.059563. Event: Event Obs, sat LOFT YAM-6 at 2025-12-18 02:34:05.059563
Observation: sat LOFT YAM-6 and opportunity Observation  at 2025-12-18 02:34:05.059563 with RGB. Look angle 258.2839897411559 | 32.921929308606934 az/dec deg, zenith angle 135.57021326154998 deg, range 806.6893633796532 km, duration 0:01:00
Time: 2025-12-18 02:35:05.059563. Event: Event Unlock satellite after obs, sat LOFT YAM-6 at 2025-12-18 02:35:05.059563
Time: 2025-12-18 03:37:52.443869. Event: Event Uplink, station KSAT Nuuk to sat AEROCUBE 18B at 2025-12-18 03:37:52.443869
Communication: station Location KSAT Nuuk | Lon -51.73363°, lat 64.182789°, alt 0 km to sat AEROCUBE 18B during pass Pass start: 2025-12-18 03:35:02.713177, highest: 2025-12-18 03:37:52.443869, fall: 2025-12-18 03:40:35.972086
Time: 2025-12-18 03:40:35.972086. Event: Event Unlock uplink, station KSAT Nuuk to sat AEROCUBE 18B at 2025-12-18 03:40:35.972086
Time: 2025-12-18 03:54:19.008380. Event: Event Obs, sat AEROCUBE 18B at 2025-12-18 03:54:19.008380
Observation: sat AEROCUBE 18B and opportunity Observation  at 2025-12-18 03:54:19.008380 with RGB. Look angle 282.0195077313904 | 29.71612260750655 az/dec deg, zenith angle 154.31430307264628 deg, range 925.5699511194322 km, duration 0:01:00
Time: 2025-12-18 03:55:19.008380. Event: Event Unlock satellite after obs, sat AEROCUBE 18B at 2025-12-18 03:55:19.008380
Time: 2025-12-18 04:43:28.781856. Event: Event Uplink, station KSAT Nuuk to sat AEROCUBE 18A at 2025-12-18 04:43:28.781856
Communication: station Location KSAT Nuuk | Lon -51.73363°, lat 64.182789°, alt 0 km to sat AEROCUBE 18A during pass Pass start: 2025-12-18 04:42:08.459136, highest: 2025-12-18 04:43:28.781856, fall: 2025-12-18 04:44:50.700625
Time: 2025-12-18 04:43:28.781856. Event: Event Uplink, station KSAT Nuuk to sat AEROCUBE 18A at 2025-12-18 04:43:28.781856
Communication: station Location KSAT Nuuk | Lon -51.73363°, lat 64.182789°, alt 0 km to sat AEROCUBE 18A during pass Pass start: 2025-12-18 04:42:08.459136, highest: 2025-12-18 04:43:28.781856, fall: 2025-12-18 04:44:50.700625
Time: 2025-12-18 04:43:28.781856. Event: Event Uplink, station KSAT Nuuk to sat AEROCUBE 18A at 2025-12-18 04:43:28.781856
Communication: station Location KSAT Nuuk | Lon -51.73363°, lat 64.182789°, alt 0 km to sat AEROCUBE 18A during pass Pass start: 2025-12-18 04:42:08.459136, highest: 2025-12-18 04:43:28.781856, fall: 2025-12-18 04:44:50.700625
Time: 2025-12-18 04:43:28.781856. Event: Event Uplink, station KSAT Nuuk to sat AEROCUBE 18A at 2025-12-18 04:43:28.781856
Communication: station Location KSAT Nuuk | Lon -51.73363°, lat 64.182789°, alt 0 km to sat AEROCUBE 18A during pass Pass start: 2025-12-18 04:42:08.459136, highest: 2025-12-18 04:43:28.781856, fall: 2025-12-18 04:44:50.700625
Time: 2025-12-18 04:44:50.700625. Event: Event Unlock uplink, station KSAT Nuuk to sat AEROCUBE 18A at 2025-12-18 04:44:50.700625
Time: 2025-12-18 04:44:50.700625. Event: Event Unlock uplink, station KSAT Nuuk to sat AEROCUBE 18A at 2025-12-18 04:44:50.700625
Time: 2025-12-18 04:44:50.700625. Event: Event Unlock uplink, station KSAT Nuuk to sat AEROCUBE 18A at 2025-12-18 04:44:50.700625
Time: 2025-12-18 04:44:50.700625. Event: Event Unlock uplink, station KSAT Nuuk to sat AEROCUBE 18A at 2025-12-18 04:44:50.700625
Time: 2025-12-18 04:51:31.406483. Event: Event Obs, sat AEROCUBE 18A at 2025-12-18 04:51:31.406483
Observation: sat AEROCUBE 18A and opportunity Observation  at 2025-12-18 04:51:31.406483 with RGB. Look angle 282.99094832345685 | 50.36091881569433 az/dec deg, zenith angle 160.5438081432149 deg, range 642.9794880942469 km, duration 0:01:00
Time: 2025-12-18 04:51:31.406483. Event: Event Obs, sat AEROCUBE 18A at 2025-12-18 04:51:31.406483
Observation: sat AEROCUBE 18A and opportunity Observation  at 2025-12-18 04:51:31.406483 with RGB. Look angle 282.99094832345685 | 50.36091881569433 az/dec deg, zenith angle 160.5438081432149 deg, range 642.9794880942469 km, duration 0:01:00
Time: 2025-12-18 04:52:31.406483. Event: Event Unlock satellite after obs, sat AEROCUBE 18A at 2025-12-18 04:52:31.406483
Time: 2025-12-18 04:52:31.406483. Event: Event Unlock satellite after obs, sat AEROCUBE 18A at 2025-12-18 04:52:31.406483
Time: 2025-12-18 04:57:17.839411. Event: Event Obs, sat AEROCUBE 18A at 2025-12-18 04:57:17.839411
Observation: sat AEROCUBE 18A and opportunity Observation  at 2025-12-18 04:57:17.839411 with RGB. Look angle 102.80144935262946 | 51.69991636236282 az/dec deg, zenith angle 157.3784982682583 deg, range 629.3218337477877 km, duration 0:01:00
Time: 2025-12-18 04:57:17.839411. Event: Event Obs, sat AEROCUBE 18A at 2025-12-18 04:57:17.839411
Observation: sat AEROCUBE 18A and opportunity Observation  at 2025-12-18 04:57:17.839411 with RGB. Look angle 102.80144935262946 | 51.69991636236282 az/dec deg, zenith angle 157.3784982682583 deg, range 629.3218337477877 km, duration 0:01:00
Time: 2025-12-18 04:58:17.839411. Event: Event Unlock satellite after obs, sat AEROCUBE 18A at 2025-12-18 04:58:17.839411
Time: 2025-12-18 04:58:17.839411. Event: Event Unlock satellite after obs, sat AEROCUBE 18A at 2025-12-18 04:58:17.839411
Time: 2025-12-18 05:05:09.244837. Event: Event Uplink, station KSAT Svalbard to sat AEROCUBE 18B at 2025-12-18 05:05:09.244837
Communication: station Location KSAT Svalbard | Lon 15.39964°, lat 78.22875°, alt 0 km to sat AEROCUBE 18B during pass Pass start: 2025-12-18 05:02:15.385487, highest: 2025-12-18 05:05:09.244837, fall: 2025-12-18 05:08:03.137654
Time: 2025-12-18 05:05:09.244837. Event: Event Uplink, station KSAT Svalbard to sat AEROCUBE 18B at 2025-12-18 05:05:09.244837
Communication: station Location KSAT Svalbard | Lon 15.39964°, lat 78.22875°, alt 0 km to sat AEROCUBE 18B during pass Pass start: 2025-12-18 05:02:15.385487, highest: 2025-12-18 05:05:09.244837, fall: 2025-12-18 05:08:03.137654
Time: 2025-12-18 05:05:09.244837. Event: Event Uplink, station KSAT Svalbard to sat AEROCUBE 18B at 2025-12-18 05:05:09.244837
Communication: station Location KSAT Svalbard | Lon 15.39964°, lat 78.22875°, alt 0 km to sat AEROCUBE 18B during pass Pass start: 2025-12-18 05:02:15.385487, highest: 2025-12-18 05:05:09.244837, fall: 2025-12-18 05:08:03.137654
Time: 2025-12-18 05:05:09.244837. Event: Event Uplink, station KSAT Svalbard to sat AEROCUBE 18B at 2025-12-18 05:05:09.244837
Communication: station Location KSAT Svalbard | Lon 15.39964°, lat 78.22875°, alt 0 km to sat AEROCUBE 18B during pass Pass start: 2025-12-18 05:02:15.385487, highest: 2025-12-18 05:05:09.244837, fall: 2025-12-18 05:08:03.137654
Time: 2025-12-18 05:08:03.137654. Event: Event Unlock uplink, station KSAT Svalbard to sat AEROCUBE 18B at 2025-12-18 05:08:03.137654
Time: 2025-12-18 05:08:03.137654. Event: Event Unlock uplink, station KSAT Svalbard to sat AEROCUBE 18B at 2025-12-18 05:08:03.137654
Time: 2025-12-18 05:08:03.137654. Event: Event Unlock uplink, station KSAT Svalbard to sat AEROCUBE 18B at 2025-12-18 05:08:03.137654
Time: 2025-12-18 05:08:03.137654. Event: Event Unlock uplink, station KSAT Svalbard to sat AEROCUBE 18B at 2025-12-18 05:08:03.137654
Time: 2025-12-18 05:18:57.799832. Event: Event Obs, sat AEROCUBE 18B at 2025-12-18 05:18:57.799832
Observation: sat AEROCUBE 18B and opportunity Observation  at 2025-12-18 05:18:57.799832 with RGB. Look angle 290.0397728918258 | 22.89081788869282 az/dec deg, zenith angle 162.95423142832743 deg, range 1109.7207300180555 km, duration 0:01:00
Time: 2025-12-18 05:18:57.799832. Event: Event Obs, sat AEROCUBE 18B at 2025-12-18 05:18:57.799832
Observation: sat AEROCUBE 18B and opportunity Observation  at 2025-12-18 05:18:57.799832 with RGB. Look angle 290.0397728918258 | 22.89081788869282 az/dec deg, zenith angle 162.95423142832743 deg, range 1109.7207300180555 km, duration 0:01:00
Time: 2025-12-18 05:19:57.799832. Event: Event Unlock satellite after obs, sat AEROCUBE 18B at 2025-12-18 05:19:57.799832
Time: 2025-12-18 05:19:57.799832. Event: Event Unlock satellite after obs, sat AEROCUBE 18B at 2025-12-18 05:19:57.799832
Time: 2025-12-18 05:24:52.016742. Event: Event Obs, sat AEROCUBE 18B at 2025-12-18 05:24:52.016742
Observation: sat AEROCUBE 18B and opportunity Observation  at 2025-12-18 05:24:52.016742 with RGB. Look angle 279.7983972581786 | 51.94967008471096 az/dec deg, zenith angle 163.63996474072596 deg, range 627.9789452814276 km, duration 0:01:00
Time: 2025-12-18 05:24:52.016742. Event: Event Obs, sat AEROCUBE 18B at 2025-12-18 05:24:52.016742
Observation: sat AEROCUBE 18B and opportunity Observation  at 2025-12-18 05:24:52.016742 with RGB. Look angle 279.7983972581786 | 51.94967008471096 az/dec deg, zenith angle 163.63996474072596 deg, range 627.9789452814276 km, duration 0:01:00
Time: 2025-12-18 05:25:52.016742. Event: Event Unlock satellite after obs, sat AEROCUBE 18B at 2025-12-18 05:25:52.016742
Time: 2025-12-18 05:25:52.016742. Event: Event Unlock satellite after obs, sat AEROCUBE 18B at 2025-12-18 05:25:52.016742
Time: 2025-12-18 06:11:10.339924. Event: Event Uplink, station KSAT Svalbard to sat AEROCUBE 18A at 2025-12-18 06:11:10.339924
Communication: station Location KSAT Svalbard | Lon 15.39964°, lat 78.22875°, alt 0 km to sat AEROCUBE 18A during pass Pass start: 2025-12-18 06:08:11.247560, highest: 2025-12-18 06:11:10.339924, fall: 2025-12-18 06:14:11.285451
Time: 2025-12-18 06:11:10.339924. Event: Event Uplink, station KSAT Svalbard to sat AEROCUBE 18A at 2025-12-18 06:11:10.339924
Communication: station Location KSAT Svalbard | Lon 15.39964°, lat 78.22875°, alt 0 km to sat AEROCUBE 18A during pass Pass start: 2025-12-18 06:08:11.247560, highest: 2025-12-18 06:11:10.339924, fall: 2025-12-18 06:14:11.285451
Time: 2025-12-18 06:14:11.285451. Event: Event Unlock uplink, station KSAT Svalbard to sat AEROCUBE 18A at 2025-12-18 06:14:11.285451
Time: 2025-12-18 06:14:11.285451. Event: Event Unlock uplink, station KSAT Svalbard to sat AEROCUBE 18A at 2025-12-18 06:14:11.285451
Time: 2025-12-18 06:28:00.616446. Event: Event Obs, sat AEROCUBE 18A at 2025-12-18 06:28:00.616446
Observation: sat AEROCUBE 18A and opportunity Observation  at 2025-12-18 06:28:00.616446 with RGB. Look angle 102.32211083232191 | 64.14572477392859 az/dec deg, zenith angle 159.09152242971615 deg, range 557.8725308964424 km, duration 0:01:00
Time: 2025-12-18 06:28:00.616446. Event: Event Obs, sat AEROCUBE 18A at 2025-12-18 06:28:00.616446
Observation: sat AEROCUBE 18A and opportunity Observation  at 2025-12-18 06:28:00.616446 with RGB. Look angle 102.32211083232191 | 64.14572477392859 az/dec deg, zenith angle 159.09152242971615 deg, range 557.8725308964424 km, duration 0:01:00
Time: 2025-12-18 06:29:00.616446. Event: Event Unlock satellite after obs, sat AEROCUBE 18A at 2025-12-18 06:29:00.616446
Time: 2025-12-18 06:29:00.616446. Event: Event Unlock satellite after obs, sat AEROCUBE 18A at 2025-12-18 06:29:00.616446
Time: 2025-12-18 06:38:57.500016. Event: Event Uplink, station KSAT Svalbard to sat AEROCUBE 18B at 2025-12-18 06:38:57.500016
Communication: station Location KSAT Svalbard | Lon 15.39964°, lat 78.22875°, alt 0 km to sat AEROCUBE 18B during pass Pass start: 2025-12-18 06:35:48.967290, highest: 2025-12-18 06:38:57.500016, fall: 2025-12-18 06:41:51.762472
Time: 2025-12-18 06:38:57.500016. Event: Event Uplink, station KSAT Svalbard to sat AEROCUBE 18B at 2025-12-18 06:38:57.500016
Communication: station Location KSAT Svalbard | Lon 15.39964°, lat 78.22875°, alt 0 km to sat AEROCUBE 18B during pass Pass start: 2025-12-18 06:35:48.967290, highest: 2025-12-18 06:38:57.500016, fall: 2025-12-18 06:41:51.762472
Time: 2025-12-18 06:38:57.500016. Event: Event Uplink, station KSAT Svalbard to sat AEROCUBE 18B at 2025-12-18 06:38:57.500016
Communication: station Location KSAT Svalbard | Lon 15.39964°, lat 78.22875°, alt 0 km to sat AEROCUBE 18B during pass Pass start: 2025-12-18 06:35:48.967290, highest: 2025-12-18 06:38:57.500016, fall: 2025-12-18 06:41:51.762472
Time: 2025-12-18 06:41:51.762472. Event: Event Unlock uplink, station KSAT Svalbard to sat AEROCUBE 18B at 2025-12-18 06:41:51.762472
Time: 2025-12-18 06:41:51.762472. Event: Event Unlock uplink, station KSAT Svalbard to sat AEROCUBE 18B at 2025-12-18 06:41:51.762472
Time: 2025-12-18 06:41:51.762472. Event: Event Unlock uplink, station KSAT Svalbard to sat AEROCUBE 18B at 2025-12-18 06:41:51.762472
Time: 2025-12-18 06:53:27.989868. Event: Event Obs, sat AEROCUBE 18B at 2025-12-18 06:53:27.989868
Observation: sat AEROCUBE 18B and opportunity Observation  at 2025-12-18 06:53:27.989868 with RGB. Look angle 288.8109653302944 | 30.679680171981886 az/dec deg, zenith angle 161.1176869870831 deg, range 908.5712120741832 km, duration 0:01:00
Time: 2025-12-18 06:54:27.989868. Event: Event Unlock satellite after obs, sat AEROCUBE 18B at 2025-12-18 06:54:27.989868
Time: 2025-12-18 06:55:37.405563. Event: Event Obs, sat AEROCUBE 18B at 2025-12-18 06:55:37.405563
Observation: sat AEROCUBE 18B and opportunity Observation  at 2025-12-18 06:55:37.405563 with RGB. Look angle 282.0623342651672 | 48.48019436887401 az/dec deg, zenith angle 163.95797304065567 deg, range 658.3903018552668 km, duration 0:01:00
Time: 2025-12-18 06:55:37.405563. Event: Event Obs, sat AEROCUBE 18B at 2025-12-18 06:55:37.405563
Observation: sat AEROCUBE 18B and opportunity Observation  at 2025-12-18 06:55:37.405563 with RGB. Look angle 282.0623342651672 | 48.48019436887401 az/dec deg, zenith angle 163.95797304065567 deg, range 658.3903018552668 km, duration 0:01:00
Time: 2025-12-18 06:56:37.405563. Event: Event Unlock satellite after obs, sat AEROCUBE 18B at 2025-12-18 06:56:37.405563
Time: 2025-12-18 06:56:37.405563. Event: Event Unlock satellite after obs, sat AEROCUBE 18B at 2025-12-18 06:56:37.405563
Time: 2025-12-18 07:00:50.225641. Event: Event Uplink, station KSAT Punta Arenas to sat LOFT YAM-6 at 2025-12-18 07:00:50.225641
Communication: station Location KSAT Punta Arenas | Lon -70.85021°, lat -52.93279°, alt 0 km to sat LOFT YAM-6 during pass Pass start: 2025-12-18 06:58:38.158955, highest: 2025-12-18 07:00:50.225641, fall: 2025-12-18 07:02:58.609874
Time: 2025-12-18 07:00:50.225641. Event: Event Uplink, station KSAT Punta Arenas to sat LOFT YAM-6 at 2025-12-18 07:00:50.225641
Communication: station Location KSAT Punta Arenas | Lon -70.85021°, lat -52.93279°, alt 0 km to sat LOFT YAM-6 during pass Pass start: 2025-12-18 06:58:38.158955, highest: 2025-12-18 07:00:50.225641, fall: 2025-12-18 07:02:58.609874
Time: 2025-12-18 07:02:58.609874. Event: Event Unlock uplink, station KSAT Punta Arenas to sat LOFT YAM-6 at 2025-12-18 07:02:58.609874
Time: 2025-12-18 07:02:58.609874. Event: Event Unlock uplink, station KSAT Punta Arenas to sat LOFT YAM-6 at 2025-12-18 07:02:58.609874
Time: 2025-12-18 07:10:56.859245. Event: Event Uplink, station KSAT Panama to sat LOFT YAM-10 at 2025-12-18 07:10:56.859245
Communication: station Location KSAT Panama | Lon -79.55°, lat 8.9833°, alt 0.028 km to sat LOFT YAM-10 during pass Pass start: 2025-12-18 07:10:06.005713, highest: 2025-12-18 07:10:56.859245, fall: 2025-12-18 07:11:47.595016
Time: 2025-12-18 07:10:56.859245. Event: Event Uplink, station KSAT Panama to sat LOFT YAM-10 at 2025-12-18 07:10:56.859245
Communication: station Location KSAT Panama | Lon -79.55°, lat 8.9833°, alt 0.028 km to sat LOFT YAM-10 during pass Pass start: 2025-12-18 07:10:06.005713, highest: 2025-12-18 07:10:56.859245, fall: 2025-12-18 07:11:47.595016
Time: 2025-12-18 07:10:56.859245. Event: Event Uplink, station KSAT Panama to sat LOFT YAM-10 at 2025-12-18 07:10:56.859245
Communication: station Location KSAT Panama | Lon -79.55°, lat 8.9833°, alt 0.028 km to sat LOFT YAM-10 during pass Pass start: 2025-12-18 07:10:06.005713, highest: 2025-12-18 07:10:56.859245, fall: 2025-12-18 07:11:47.595016
Time: 2025-12-18 07:11:47.595016. Event: Event Unlock uplink, station KSAT Panama to sat LOFT YAM-10 at 2025-12-18 07:11:47.595016
Time: 2025-12-18 07:11:47.595016. Event: Event Unlock uplink, station KSAT Panama to sat LOFT YAM-10 at 2025-12-18 07:11:47.595016
Time: 2025-12-18 07:11:47.595016. Event: Event Unlock uplink, station KSAT Panama to sat LOFT YAM-10 at 2025-12-18 07:11:47.595016
Time: 2025-12-18 07:12:48.668164. Event: Event Obs, sat LOFT YAM-10 at 2025-12-18 07:12:48.668164
Observation: sat LOFT YAM-10 and opportunity Observation  at 2025-12-18 07:12:48.668164 with RGB. Look angle 256.62751734593604 | 50.33736130033901 az/dec deg, zenith angle 159.4824988645976 deg, range 748.1028481405805 km, duration 0:01:00
Time: 2025-12-18 07:13:48.668164. Event: Event Unlock satellite after obs, sat LOFT YAM-10 at 2025-12-18 07:13:48.668164
Time: 2025-12-18 07:14:56.905610. Event: Event Obs, sat LOFT YAM-10 at 2025-12-18 07:14:56.905610
Observation: sat LOFT YAM-10 and opportunity Observation  at 2025-12-18 07:14:56.905610 with RGB. Look angle 75.1582248058237 | 33.185237009974664 az/dec deg, zenith angle 172.30503769952267 deg, range 992.5593448663045 km, duration 0:01:00
Time: 2025-12-18 07:14:56.905610. Event: Event Obs, sat LOFT YAM-10 at 2025-12-18 07:14:56.905610
Observation: sat LOFT YAM-10 and opportunity Observation  at 2025-12-18 07:14:56.905610 with RGB. Look angle 75.1582248058237 | 33.185237009974664 az/dec deg, zenith angle 172.30503769952267 deg, range 992.5593448663045 km, duration 0:01:00
Time: 2025-12-18 07:15:56.905610. Event: Event Unlock satellite after obs, sat LOFT YAM-10 at 2025-12-18 07:15:56.905610
Time: 2025-12-18 07:15:56.905610. Event: Event Unlock satellite after obs, sat LOFT YAM-10 at 2025-12-18 07:15:56.905610
Time: 2025-12-18 07:25:13.747439. Event: Event Obs, sat LOFT YAM-6 at 2025-12-18 07:25:13.747439
Observation: sat LOFT YAM-6 and opportunity Observation  at 2025-12-18 07:25:13.747439 with RGB. Look angle 71.56109877509641 | 41.90940000643703 az/dec deg, zenith angle 152.62133593143025 deg, range 678.7575214604044 km, duration 0:01:00
Time: 2025-12-18 07:25:13.747439. Event: Event Obs, sat LOFT YAM-6 at 2025-12-18 07:25:13.747439
Observation: sat LOFT YAM-6 and opportunity Observation  at 2025-12-18 07:25:13.747439 with RGB. Look angle 71.56109877509641 | 41.90940000643703 az/dec deg, zenith angle 152.62133593143025 deg, range 678.7575214604044 km, duration 0:01:00
Time: 2025-12-18 07:26:13.747439. Event: Event Unlock satellite after obs, sat LOFT YAM-6 at 2025-12-18 07:26:13.747439
Time: 2025-12-18 07:26:13.747439. Event: Event Unlock satellite after obs, sat LOFT YAM-6 at 2025-12-18 07:26:13.747439
Time: 2025-12-18 08:06:17.907018. Event: Event Uplink, station KSAT Panama to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 08:06:17.907018
Communication: station Location KSAT Panama | Lon -79.55°, lat 8.9833°, alt 0.028 km to sat Ubotica CogniSat-6 HAMMER during pass Pass start: 2025-12-18 08:04:11.138383, highest: 2025-12-18 08:06:17.907018, fall: 2025-12-18 08:08:41.120496
Time: 2025-12-18 08:06:17.907018. Event: Event Uplink, station KSAT Panama to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 08:06:17.907018
Communication: station Location KSAT Panama | Lon -79.55°, lat 8.9833°, alt 0.028 km to sat Ubotica CogniSat-6 HAMMER during pass Pass start: 2025-12-18 08:04:11.138383, highest: 2025-12-18 08:06:17.907018, fall: 2025-12-18 08:08:41.120496
Time: 2025-12-18 08:06:17.907018. Event: Event Uplink, station KSAT Panama to sat Ubotica CogniSat-6 HAMMER at 2025-12-18 08:06:17.907018

In [123]:
broker._requests

,request,requested_pass,requested_constellation,requested_satellite,constellation,satellite,assigned_pass,assigned_downlink,status,data_product,scheduled_callback,unscheduled_callback,ready_callback,opportunities
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,{LOFT YAM-6: [Pass start: 2025-12-18 02:34:02....
1,"Request Kaduna | Lon 7.4333°, lat 10.5167°, al...","Pass start: 2025-12-18 01:57:48.495494, highes...",<__main__.ConstellationGroundScheduler object ...,Ubotica CogniSat-6 HAMMER,None,None,None,None,No timely contact,None,<function Broker.schedule_request.<locals>.<la...,<function Broker.schedule_request.<locals>.<la...,<function Broker.schedule_request.<locals>.<la...,NaN
2,"Request Kaduna | Lon 7.4333°, lat 10.5167°, al...","Pass start: 2025-12-17 21:31:42.534577, highes...",<__main__.ConstellationGroundScheduler object ...,AEROCUBE 18B,None,None,None,None,No timely contact,None,<function Broker.schedule_request.<locals>.<la...,<function Broker.schedule_request.<locals>.<la...,<function Broker.schedule_request.<locals>.<la...,NaN
3,"Request Kaduna | Lon 7.4333°, lat 10.5167°, al...","Pass start: 2025-12-18 00:42:33.962308, highes...",<__main__.ConstellationGroundScheduler object ...,LOFT YAM-10,None,None,None,None,No timely contact,None,<function Broker.schedule_request.<locals>.<la...,<function Broker.schedule_request.<locals>.<la...,<function Broker.schedule_request.<locals>.<la...,NaN
4,"Request Wayaobu | Lon 109.6752°, lat 37.1427°,...","Pass start: 2025-12-18 18:54:12.848704, highes...",<__main__.ConstellationGroundScheduler object ...,Ubotica CogniSat-6 HAMMER,<__main__.ConstellationGroundScheduler object ...,Ubotica CogniSat-6 HAMMER,Observation at 2025-12-18 18:56:17.831876 wit...,None,Scheduled,None,<function Broker.schedule_request.<locals>.<la...,<function Broker.schedule_request.<locals>.<la...,<function Broker.schedule_request.<locals>.<la...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,"Request Yulin | Lon 110.181°, lat 22.654°, alt...","Pass start: 2025-12-18 14:49:52.031908, highes...",<__main__.ConstellationGroundScheduler object ...,AEROCUBE 18B,None,None,None,None,All observation opportunities are conflicting,None,<function Broker.schedule_request.<locals>.<la...,<function Broker.schedule_request.<locals>.<la...,<function Broker.schedule_request.<locals>.<la...,NaN
147,"Request Yulin | Lon 110.181°, lat 22.654°, alt...","Pass start: 2025-12-18 16:52:13.860307, highes...",<__main__.ConstellationGroundScheduler object ...,LOFT YAM-10,None,None,None,None,All observation opportunities are conflicting,None,<function Broker.schedule_request.<locals>.<la...,<function Broker.schedule_request.<locals>.<la...,<function Broker.schedule_request.<locals>.<la...,NaN
148,"Request Dalian | Lon 121.6°, lat 38.9°, alt 0....","Pass start: 2025-12-18 14:17:23.343656, highes...",<__main__.ConstellationGroundScheduler object ...,AEROCUBE 18A,None,None,None,None,All observation opportunities are conflicting,None,<function Broker.schedule_request.<locals>.<la...,<function Broker.schedule_request.<locals>.<la...,<function Broker.schedule_request.<locals>.<la...,NaN
149,"Request Dalian | Lon 121.6°, lat 38.9°, alt 0....","Pass start: 2025-12-18 18:19:19.179307, highes...",<__main__.ConstellationGroundScheduler object ...,LOFT YAM-6,None,None,None,None,All observation opportunities are conflicting,None,<function Broker.schedule_request.<locals>.<la...,<function Broker.schedule_request.<locals>.<la...,<function Broker.schedule_request.<locals>.<la...,NaN
150,"Request Dalian | Lon 121.6°, lat 38.9°, alt 0....","Pass start: 2025-12-18 16:55:07.062927, highes...",<__main__.ConstellationGroundScheduler object ...,LOFT YAM-10,<__main__.ConstellationGroundScheduler object ...,LOFT YAM-10,Observation at 2025-12-18 16:58:18.296572 wit...,None,Completed,Observation at 2025-12-18 16:58:18.296572 wit...,<function Broker.schedule_request.<locals>.<la...,<function Broker.schedule_request.<locals>.<la...,<function Broker.schedule_request.<locals>.<la...,NaN

In [110]:
def plot_event(_chronicle: dict, world: World, ax=None):
    if ax is None:
        figglobal = plt.figure(figsize=(10,5))
        ax = figglobal.add_subplot(1,1,1, projection=ccrs.Robinson())
        ax.set_global()
        ax.coastlines()

    _time_to_plot_ground_track = dt.timedelta(seconds=15*60)
    _dt_to_plot_ground_track = dt.timedelta(seconds=60)
    time_steps_for_plotting = [_chronicle['time']- _dt_to_plot_ground_track*i for i in range(int(math.ceil(_time_to_plot_ground_track/_dt_to_plot_ground_track)))]

    ax.text(0,0,"{}".format(_chronicle['time']), transform=ax.transAxes)

    # for satellite in world.satellites:
    #     _orbit = satellite.orbit
    #     _llas = [_orbit.get_lonlatalt(t) for t in time_steps_for_plotting]
    #     # ax.plot([lla[0] for lla in _llas],[lla[1] for lla in _llas],transform=ccrs.Geodetic())
    #     ax.plot([lla[0] for lla in _llas],[lla[1] for lla in _llas],transform=ccrs.Geodetic())
    
    constellation_palette = cmap['viridis'].resampled(len(world.constellations))

    for constellation_ix, constellation in enumerate(world.constellations):
        constellation_color = constellation_palette(constellation_ix/len(world.constellations))
        for ground_station in constellation.ground_stations:
            ax.plot(float(ground_station.lon_deg), float(ground_station.lat_deg), '*', transform=ccrs.PlateCarree(), color=constellation_color)

        for satellite in constellation.satellites:
            _orbit = satellite.orbit
            _llas = [_orbit.get_lonlatalt(t) for t in time_steps_for_plotting]
            # ax.plot([lla[0] for lla in _llas],[lla[1] for lla in _llas],transform=ccrs.Geodetic())
            ax.plot([lla[0] for lla in _llas],[lla[1] for lla in _llas],transform=ccrs.Geodetic(), color=constellation_color)
    
    if type(_chronicle['event'])==ObservationEvent:
        ax.plot(
            [_chronicle['event'].opportunity.lon_deg, _chronicle['event'].satellite.orbit.get_lonlatalt(_chronicle['time'])[0]],
            [_chronicle['event'].opportunity.lat_deg, _chronicle['event'].satellite.orbit.get_lonlatalt(_chronicle['time'])[1]],
            ':k',
            transform=ccrs.Geodetic()
        )
        ax.plot(
            _chronicle['event'].opportunity.lon_deg,
            _chronicle['event'].opportunity.lat_deg,
            'Dr',
            markersize=10,
            transform=ccrs.Geodetic()
        )
        ax.plot(
            _chronicle['event'].satellite.orbit.get_lonlatalt(_chronicle['time'])[0],
            _chronicle['event'].satellite.orbit.get_lonlatalt(_chronicle['time'])[1],
            '.',
            markersize=10,
            transform=ccrs.Geodetic()
        )

    elif type(_chronicle['event'])==CommunicationEvent:
        ax.plot(
            [_chronicle['event'].station.lon_deg, _chronicle['event'].satellite.orbit.get_lonlatalt(_chronicle['time'])[0]],
            [_chronicle['event'].station.lat_deg, _chronicle['event'].satellite.orbit.get_lonlatalt(_chronicle['time'])[1]],
            '-.k',
            transform=ccrs.Geodetic()
        )
        ax.plot(
            _chronicle['event'].station.lon_deg,
            _chronicle['event'].station.lat_deg,
            '*',
            markersize=10,
            transform=ccrs.Geodetic()
        )
        ax.plot(
            _chronicle['event'].satellite.orbit.get_lonlatalt(_chronicle['time'])[0],
            _chronicle['event'].satellite.orbit.get_lonlatalt(_chronicle['time'])[1],
            '.',
            markersize=10,
            transform=ccrs.Geodetic()
        )
    return ax


def plot_history(world: World):
    artists = []
    for _chronicle_ix, _chronicle in enumerate(world.history):
        _ax = plot_event(_chronicle, world)
        plt.savefig("FRAME_{:05d}.png".format(_chronicle_ix))
        # artists.append(_ax)
        
    # plt.show()
        # if type(_chronicle['event'])==ObservationEvent:
        #     print("Observation: sat {} and opportunity {}".format(_chronicle['event'].satellite, _chronicle['event'].opportunity))
        # if type(_chronicle['event'])==CommunicationEvent:
        #     print("Communication: station {} to sat {} during pass {}".format(_chronicle['event'].station, _chronicle['event'].satellite, _chronicle['event'].comm_pass))

In [111]:
# plot_history(world_with_brokers)
# # for i in range(10):
#     # plot_event(world_with_brokers.history[i], world_with_brokers)